### PR TITLE
Various improvements on the QC report and resampling module

### LINKED ISSUE #1778: add QC feature for sct_register_multimodal
### Description

The same visual as for `sct_register_to_template` would be fine.

### LINKED ISSUE #2014: QC generates blank images with sct_register_to_template
### Description

When using QC flag on `sct_register_to_template`, the output QC figures are empty. Note that it works on `sct_testing_data` so there must be something weird with these data. Maybe one thing to note is that `mt1_crop` and `mt1_seg` are not in the same space (although that should not matter because-- i think).

### Steps to Reproduce

SCT version: 6404c8b2bacd7cdd0f73ecbfbe7ce285c4811e17

Data: 
[data_test.zip](https://github.com/neuropoly/spinalcordtoolbox/files/2343542/data_test.zip)

Syntax:
~~~
sct_register_to_template -i mt1_crop.nii.gz -s mt1_seg.nii.gz -l label_vert.nii.gz -ref subject -c t2 -param step=1,type=seg,algo=centermass:step=2,type=im,algo=syn,metric=CC,slicewise=0,smooth=0,iter=3 -qc ./qc
~~~

### LINKED ISSUE #2091: Find another way to parse subject name
If a pipeline is launched across multiple BIDS datasets, there will be a duplication of "subject" ID (e.g. site1/sub-01, site2/sub-01).

To avoid this, `sct_qc` should be able to receive the "site" and "subject" as optional parameters.

### LINKED ISSUE #2138: Issue while generating QC
error only occurred on `rosenberg`

~~~
  File "/home/jcohen/code/sct/scripts/sct_deepseg_gm.py", line 161, in <module>
    run_main()
  File "/home/jcohen/code/sct/scripts/sct_deepseg_gm.py", line 151, in run_main
    generate_qc(input_filename, out_fname, sys.argv[1:], os.path.abspath(path_qc))
  File "/home/jcohen/code/sct/scripts/sct_deepseg_gm.py", line 116, in generate_qc
    qcslice_layout=lambda x: x.mosaic(),
  File "/home/jcohen/code/sct/spinalcordtoolbox/reports/qc.py", line 410, in add_entry
    layout(qcslice)
  File "/home/jcohen/code/sct/spinalcordtoolbox/reports/qc.py", line 206, in wrapped_f
    plt.figure()
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 76, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 68, in __init__
    _create_qApp()
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 138, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
Merge within groups: 100%|####################| 11/11 [00:15<00:00,  1.28s/iter]
Z=0/0: 100%|####################################| 1/1 [00:05<00:00,  5.16s/iter]
Z=0/0: 100%|##################################| 11/11 [00:14<00:00,  1.82s/iter]
Z=0/0: 100%|##################################| 33/33 [00:04<00:00,  8.16iter/s]
Traceback (most recent call last):
  File "/home/jcohen/code/sct/scripts/sct_propseg.py", line 649, in <module>
    res = main(arguments)
  File "/home/jcohen/code/sct/scripts/sct_propseg.py", line 640, in main
    generate_qc(fname_input_data, fname_seg, args, os.path.abspath(path_qc))
  File "/home/jcohen/code/sct/scripts/sct_propseg.py", line 370, in generate_qc
    qcslice_layout=lambda x: x.mosaic(),
  File "/home/jcohen/code/sct/spinalcordtoolbox/reports/qc.py", line 410, in add_entry
    layout(qcslice)
  File "/home/jcohen/code/sct/spinalcordtoolbox/reports/qc.py", line 206, in wrapped_f
    plt.figure()
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 76, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 68, in __init__
    _create_qApp()
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 138, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
FINISHED :-)
Started: 21/01/19_11:18:33 AM
Ended  : 21/01/19_12:29:42 PM
To open Quality Control (QC) report on a web-browser, run the following:\n
xdg-open /home/jcohen/data/spineGeneric_multiSubjects_qc/index.html
[jcohen@rosenberg spine_generic]$
[jcohen@rosenberg spine_generic]$ ll
~~~

### LINKED ISSUE #2148: QC report doesn't like uncompressed nii segmentation files
When generating QC report based on segmentation files that are not compressed (nii instead of nii.gz), it crashes (see below):

<details>

~~~
QC: layout with Sagittal slice
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_label_vertebrae.py", line 897, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_label_vertebrae.py", line 354, in main
    generate_qc(fname_in, labeled_seg_file, args, path_qc)
  File "/Users/julien/code/sct/scripts/sct_label_vertebrae.py", line 408, in generate_qc
    qcslice_layout=lambda x: x.single(),
  File "/Users/julien/code/sct/spinalcordtoolbox/reports/qc.py", line 410, in add_entry
    layout(qcslice)
  File "/Users/julien/code/sct/spinalcordtoolbox/reports/qc.py", line 177, in wrapped_f
    img, mask = func(sct_slice, *args)
  File "/Users/julien/code/sct/spinalcordtoolbox/reports/qc.py", line 408, in layout
    return qcslice_layout(qslice)
  File "/Users/julien/code/sct/scripts/sct_label_vertebrae.py", line 408, in <lambda>
    qcslice_layout=lambda x: x.single(),
  File "/Users/julien/code/sct/spinalcordtoolbox/reports/slice.py", line 265, in single
    index = self.get_center_spit()
  File "/Users/julien/code/sct/spinalcordtoolbox/reports/slice.py", line 317, in get_center_spit
    x, y = self._axial_center(image)
  File "/Users/julien/code/sct/spinalcordtoolbox/reports/slice.py", line 202, in _axial_center
    centers_x[i], centers_y[i] = ndimage.measurements.center_of_mass(aslice)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/scipy/ndimage/measurements.py", line 1289, in center_of_mass
    return [tuple(v) for v in numpy.array(results).T]
TypeError: 'numpy.float64' object is not iterable
Total processing time: 0 min 16 s
~~~

</details><p>

To reproduce:
~~~
sct_download_data -d sct_testing_data
cd sct_testing_data/t2
fslchfiletype NIFTI t2_seg.nii.gz
sct_label_vertebrae -i t2.nii.gz -s t2_seg.nii -c t2 -initz 34,4 -qc ./qc
~~~

This bug is related to #1706. For some reasons, when using .nii instead of .nii.gz, when calling image.data, the type is a memmap instead of a np.array. A workaround is to cast `np.array()` when calling `image.data`.

### PR DESCRIPTION
**Pull request by jcohenadad**
Various improvements, including:
- Moved `spinalcordtoolbox/resample/nipy_resample.py` --> `spinalcordtoolbox/resample.py` for simplicity (folder was not needed)
- Made it possible in `sct_register_multimodal` to have flag dseg without flag iseg (for QC).
- Added QC feature for `sct_register_multimodal`. Fixes #1778
- QC folder name now includes milliseconds to avoid overwritting (happens when running with parallel processing)
- Now retrieve `dataset` and `subject`, according to BIDS convention, and display both in the QC report. Fixes #2091
- Increased kernel size for CLAHE method (was too aggressive). Also implemented `contrast_stretching` histogram equalization method.
- Fixed: QC generates blank images with sct_register_to_template. Fixes #2014
- QC report now compatible with uncompressed NIFTI segmentation files. Fixes #2148.
- Centralized generate_qc() within spinalcordtoolbox/reports/qc.py
- Added APRL in first image
- Use matplotlib OOP API instead of pyplot and select the backend by hand to prevent crash on headless machines. Fixes #2138

### CODE REVIEW

**Comment by jcohenadad** [comment]
@zougloub I would like to pass the new [stretch_contrast_method](https://github.com/neuropoly/spinalcordtoolbox/blob/dff0d10e8757c623740ccb5b582c564131450795/spinalcordtoolbox/reports/qc.py#L70) as input param from the SCT function calling `generate_qc()` (e.g., [here](https://github.com/neuropoly/spinalcordtoolbox/blob/dff0d10e8757c623740ccb5b582c564131450795/scripts/sct_propseg.py#L343)). The problem is: I don't want to add a parameter to `generate_qc()` and then to [add_entry](https://github.com/neuropoly/spinalcordtoolbox/blob/dff0d10e8757c623740ccb5b582c564131450795/spinalcordtoolbox/reports/qc.py#L404). I'm sure there is a more elegant way of doing this. Any tips?

**Comment by zougloub** [comment]
@jcohenadad we can use keyword arguments (`**kw`) to have less code written, but it's more painful for the users as the API is less explicit (eg. IDE auto-completion doesn't work, documentation is less easy to access).

```
def a(**kw):
  """
  :param kw: see b()
  """
  ...
  b(**kw)
  ...

def b(**kw):
  """
  :param kw: see c()
  """
  ...
  c(**kw)
  ...

def c(p0=1, p1=2, p2=3):
  """
  :param p0: ...
  """

```

**Comment by jcohenadad** [comment]
I'm having issues with matplotlib's automatic adjustment of figure size upon saving. Namely, the code below (in `reports/qc/_save()`) does not crop identically across input examples, depending on the size:
```python
        plt.savefig(img_path,
                    format=format,
                    bbox_inches=bbox_inches,
                    pad_inches=pad_inches,
                    transparent=True,
                    dpi=dpi)
``` 
Resulting in issues like this where the image and the segmentation is not cropped the same way (highly problematic...):
screen shot 2019-02-24 at 11 34 11

**Comment by jcohenadad** [comment]
@zougloub @perone Regarding the "WARNING" (https://github.com/neuropoly/spinalcordtoolbox/pull/2157#issue-252407428) about manually deleting the **resample/** folder after a `git pull` (because git keeps track of files, not folders), I'm afraid this will cause a lot of trouble in our users. Can you recommend something to deal with this problem? E.g. added some code in the installation to delete empty folders, etc.

**Comment by zougloub** [comment]
I have no clean solution, just workarounds (eg. renaming the new module `resampling` or leaving stuff in the `__init__.py`...), and IMO doing something in the installer is worse.

**Comment by charleygros** [comment]
```
* Moved `spinalcordtoolbox/resample/nipy_resample.py` --> `spinalcordtoolbox/resample.py` for simplicity (folder was not needed)
```
--> Tested with `sct_resample` and `sct_deepseg_sc`, seems all good to me.

```
* QC folder name now includes milliseconds to avoid overwritting (happens when running with parallel processing)
```
--> Tested, seems good to me.

```
* Now retrieve `dataset` and `subject`, according to BIDS convention, and display both in the QC report. Fixes #2091
```
--> Tested on a dataset with BIDS convention, works!!

```
* QC report now compatible with uncompressed NIFTI segmentation files. Fixes #2148.
```
--> Tested, works well.

```
* Added APRL in first image
```
--> Tested, really Nice.

**Pull request merged**
