### PR TITLE
Remove tensorboard==1.14.0 version pinning from requirements.txt

### LINKED ISSUE #3145: Tensorboard version mismatch between requirements.txt and actual installed version
In #3041, the version of tensorboard was pinned to `1.14.0`.

https://github.com/neuropoly/spinalcordtoolbox/blob/d64af23b69dbc396322cdc963a90a899b73736e0/requirements.txt#L43

Also in #3041, tensorboard gets reinstalled, which was as part of a fix for #3035. (See https://github.com/neuropoly/spinalcordtoolbox/pull/3034#discussion_r527004400 for rationale.) 

https://github.com/neuropoly/spinalcordtoolbox/blob/d64af23b69dbc396322cdc963a90a899b73736e0/install_sct#L614-L620

But because we simply specify `pip install tensorboard`, the newest version (`2.4.0`) gets installed , and we get this warning:

```
Check if tensorboard (1.14.0) is installed..........[WARNING] (2.4.0 != 1.14.0 mandated version))
```

### PR DESCRIPTION
**Pull request by joshuacwnewton**
#### GitHub

- [X] I've given this PR a concise, self-descriptive, and meaningful title
- [X] I've linked relevant issues in the PR body
- [X] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [X] I've assigned a reviewer

#### PR contents

- [ ] I've consulted [SCT's internal developer documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki) to ensure my contribution is in line with any relevant design decisions
- [ ] I've added [relevant tests](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Tests) for my contribution
- [ ] I've updated the [relevant documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description

This pinned version:

* Does nothing (because it is overridden anyway)
* Wasn't needed in the first place, and 
* Causes an ugly error in `sct_check_dependencies`

So, remove it!

## Linked issues

Fixes #3145.

### CODE REVIEW

**Comment by kousu** [comment]
Omg finally yay

**Review by kousu — COMMENTED** [review]
I wonder if we should remove this too

https://github.com/neuropoly/spinalcordtoolbox/blob/c6dce15dac53af206931727499e01940da25f77e/install_sct#L614-L620

I haven't had a chance to try yet, but I'm putting the thought out there so at least one of us remembers to try

**Comment by kousu** [comment]
Is this what you meant by "overridden anyway"?

**Comment by joshuacwnewton** [comment]
> I wonder if we should remove this too

I tried doing that a while back (I'll see if I can find the pull request where I tested it), but doing so caused CI to fail, so I think it's necessary.

> Is this what you meant by "overridden anyway"?

Exactly, yeah. It reinstalls the newest version.

**Comment by joshuacwnewton** [comment]
See https://github.com/neuropoly/spinalcordtoolbox/pull/3082/commits/b431f9c5e3cb62fcef7e26b003a86132537a4ec3.

**Comment by joshuacwnewton** [comment]
Oh! Wait, scratch that. Writing comment, one sec...

**Comment by joshuacwnewton** [comment]
Good catch. We still need `pip uninstall -y tensorflow-tensorboard`, but I have a feeling the other two lines can go.

**Comment by joshuacwnewton** [comment]
It looks like the reinstall of `tensorboard` is necessary after all. 

Not a big deal, though. That was just a quick test. :slightly_smiling_face:

**Review by kousu — APPROVED** [review]
Weird, but thanks for the fix: https://github.com/neuropoly/spinalcordtoolbox/issues/3145#issuecomment-765490951

**Pull request merged**
