### PR TITLE
sct_get_centerline: fixup image refactoring issues

### LINKED ISSUE #2002: crash when using viewer
data: sct_testing_data/t2

syntax+error:
~~~
sct_get_centerline -i t2.nii.gz -method viewer

--
Spinal Cord Toolbox (master/9ae6ad657f2788948e6ef06c31eeab09c8943b8f)
Running /Users/julien/code/sct/scripts/sct_get_centerline.py -i t2.nii.gz -method viewer
cp /Users/julien/sct_testing_data/t2/t2.nii.gz /var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20180816163038.642716-AJAvF5
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_get_centerline.py", line 259, in <module>
    run_main()
  File "/Users/julien/code/sct/scripts/sct_get_centerline.py", line 175, in run_main
    x_centerline_fit, y_centerline_fit, z_centerline, x_centerline_deriv, y_centerline_deriv, z_centerline_deriv = smooth_centerline(image_points_RPI, algo_fitting='nurbs', nurbs_pts_number=3000, phys_coordinates=True, verbose=verbose, all_slices=False)
NameError: global name 'image_points_RPI' is not defined
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
No handlers could be found for logger "sentry.errors"
Note: you can opt out of Sentry reporting by editing the file ${SCT_DIR}/bin/sct_launcher and delete the line starting with "export SENTRY_DSN"
Total processing time: 0 min 13 s
~~~

### PR DESCRIPTION
**Pull request by zougloub**
Fixes #2002

### CODE REVIEW

**Comment by jcohenadad** [comment]
hum, i got this:
~~~
julien-macbook:~ $ cd sct_testing_data/t2
julien-macbook:~/sct_testing_data/t2 $ sct_get_centerline -i t2.nii.gz -method viewer

--
Spinal Cord Toolbox (cJ/2002-typo/813dd1186455c08334611d093a661b715bd31190)
Running /Users/julien/code/sct/scripts/sct_get_centerline.py -i t2.nii.gz -method viewer
cp /Users/julien/sct_testing_data/t2/t2.nii.gz /var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20180816185553.068345-pX8z5k
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_get_centerline.py", line 263, in <module>
    run_main()
  File "/Users/julien/code/sct/scripts/sct_get_centerline.py", line 173, in run_main
    fname_points = viewer_centerline(image_reoriented, interslice_gap=interslice_gap, verbose=verbose)
  File "/Users/julien/code/sct/scripts/sct_get_centerline.py", line 24, in viewer_centerline
    viewer = ClickViewerPropseg(image_input_reoriented)
  File "/Users/julien/code/sct/scripts/sct_viewer.py", line 814, in __init__
    input_type=input_type)
  File "/Users/julien/code/sct/scripts/sct_viewer.py", line 507, in __init__
    ax = self.fig.add_subplot(gs[0, 1:], facecolor='k')
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/matplotlib/figure.py", line 1005, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/matplotlib/axes/_subplots.py", line 73, in __init__
    self._axes_class.__init__(self, fig, self.figbox, **kwargs)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 537, in __init__
    self.update(kwargs)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/matplotlib/artist.py", line 856, in update
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property facecolor
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
No handlers could be found for logger "sentry.errors"
Note: you can opt out of Sentry reporting by editing the file ${SCT_DIR}/bin/sct_launcher and delete the line starting with "export SENTRY_DSN"
Total processing time: 0 min 2 s
~~~

**Comment by zougloub** [comment]
I have updated the matplotlib installation requirement to use a newer version (`matplotlib==1.5.1 -> matplotlib=2.2.3`) ; haven't checked if it's available on Conda, let's see what the CI says.

**Comment by zougloub** [comment]
I've been using Matplotlib 2.2.2 for a while now with SCT (except in the context of the viewer which I haven't used until this issue), it shouldn't be a problem.

**Comment by jcohenadad** [comment]
should we take this opportunity to switch the old viewer to the new one? https://github.com/neuropoly/spinalcordtoolbox/issues/1837

**Comment by jcohenadad** [comment]
after fresh re-installation:

~~~
julien-macbook:~/sct_example_data/t2 $ sct_get_centerline -i t2.nii.gz -method viewer

--
Spinal Cord Toolbox (cJ/2002-typo/6cee87b37c2ccd3c38966de9a45ecf34e50cf74f)
Running /Users/julien/code/sct/scripts/sct_get_centerline.py -i t2.nii.gz -method viewer
cp /Users/julien/sct_example_data/t2/t2.nii.gz /var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20180819122449.840208-oNqfoA
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_get_centerline.py", line 263, in <module>
    run_main()
  File "/Users/julien/code/sct/scripts/sct_get_centerline.py", line 173, in run_main
    fname_points = viewer_centerline(image_reoriented, interslice_gap=interslice_gap, verbose=verbose)
  File "/Users/julien/code/sct/scripts/sct_get_centerline.py", line 39, in viewer_centerline
    sct.run(["sct_label_utils", "-i", image_fname, "-create", mask_points, "-o", mask_filename], verbose=False)
  File "/Users/julien/code/sct/scripts/sct_utils.py", line 476, in run
    raise RunError(output)
sct_utils.RunError: Running /Users/julien/code/sct/scripts/sct_label_utils.py -i /Users/julien/sct_example_data/t2/./t2_sal.nii.gz -create 24,166,36,1:36,162,36,1:48,163,35,1:60,168,36,1:72,177,35,1:84,181,33,1:96,184,32,1:108,186,33,1:120,186,32,1:132,187,31,1:144,188,32,1:156,190,31,1:168,192,32,1:180,197,32,1:192,199,33,1:204,201,33,1:216,202,33,1:228,205,33,1:240,206,32,1:252,210,32,1:264,214,31,1:276,216,32,1:288,220,32,1 -o /Users/julien/sct_example_data/t2/./t2_sal_mask_viewer.nii.gz

DESCRIPTION
Utility function for label image.

USAGE
sct_label_utils -i <file>

MANDATORY ARGUMENTS
-i <file>                    Input image.

OPTIONAL ARGUMENTS
-add <int>                   Add value to all labels. Value can be negative.
-create <list of: Coordinate>Create labels in a new image. List labels as:
x1,y1,z1,value1:x2,y2,z2,value2, ...
-create-add <list of: Coordinate>Same as "-create", but add labels to the input image instead of
creating a new image.
-create-seg <list of: str>   Create labels along cord segmentation (or centerline) defined by
"-i". First value is "z", second is the value of the label. Separate
labels with ":". Example: 5,1:14,2:23,3. To select the mid-point in
the superior-inferior direction, set z to "-1". For example if you
know that C2-C3 disc is centered in the S-I direction, then enter:
-1,3
-create-viewer <list of: int>Manually label from a GUI a list of labels IDs, separated with ",".
Example: 2,3,4,5
-cross <int>                 Create a cross around each non-zero value. Input cross radius in mm.
-cubic-to-point              Compute the center-of-mass for each label value.
-display                     Display all labels (i.e. non-zero values).
-increment                   Takes all non-zero values, sort them along the inverse z direction,
and attributes the values 1, 2, 3, etc.
-vert-body <list of: int>    From vertebral labeling, create points that are centered at the
mid-vertebral levels. Separate desired levels with ",". To get all
levels, enter "0".
-vert-continuous             Convert discrete vertebral labeling to continuous vertebral labeling.
-MSE <file>                  Compute Mean Square Error between labels from input and reference
image. Specify reference image here.
-remove <file>               Remove labels from input image (-i) that are not in reference image
(specified here).
-remove-sym <file>           Remove labels from input image (-i) and reference image (specified
here) that don't match. You must provide two output names separated
by ",".
MISC
-msg <str>                   Display a message to explain the labeling task. Use with
-create-viewer.
-o <list of: file_output>    Output image(s). Default value = labels.nii.gz
-v {0,1,2}                   Verbose. 0: nothing. 1: basic. 2: extended. Default value = 1

Command-line usage error: Option -i file doesn't exist: /Users/julien/sct_example_data/t2/./t2_sal.nii.gz
Aborted...
Total processing time: 0 min 2 s
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
No handlers could be found for logger "sentry.errors"
Note: you can opt out of Sentry reporting by editing the file ${SCT_DIR}/bin/sct_launcher and delete the line starting with "export SENTRY_DSN"
Total processing time: 0 min 35 s
~~~

**Comment by zougloub** [comment]
Other bugs were lurking around. The code was taking shortcuts like reusing variables and I didn't take time to clean-it up, should have.

**Comment by jcohenadad** [comment]
sanity checking: batch_processing results (5f9a6ab830404fda21e583827acd09f89b4c9678):
~~~
t2/CSA:   78.871618, 1.654855
mt/MTR:   2018/08/22 - 11:26:43,/Users/julien/sct_example_data/mt/mtr.nii.gz,map,"2,3,4,5","15,16,17,11,12,13,14,8,9,10,4,5,6,7",51,white matter,979.48489179,54.1930136678,0
t2s/CSA_GM:   13.282941, 3.440752
t2s/CSA_WM:   65.160860, 3.175766
dmri/FA:  2018/08/22 - 11:33:09,/Users/julien/sct_example_data/dmri/dti_FA.nii.gz,wa,Unknown,"2,3,4,5,6,7,8,9,10,11,12,13,14",4,WM left lateral corticospinal tract,81.0884509681,0.769648430657,0.160504257652
dmri/FA:  2018/08/22 - 11:33:09,/Users/julien/sct_example_data/dmri/dti_FA.nii.gz,wa,Unknown,"2,3,4,5,6,7,8,9,10,11,12,13,14",5,WM right lateral corticospinal tract,80.6086908219,0.783261121565,0.15069892177
~~~

#1948 (cJ/more-image-374e8d0)
~~~
t2/CSA:   78.703221, 1.760750
mt/MTR:   2018/08/08 - 15:52:32,/home/jcohen/sct_example_data/mt/mtr.nii.gz,map,"2,3,4,5","15,16,17,11,12,13,14,8,9,10,4,5,6,7",51,white matter,980.883843843,54.1147920284,0
t2s/CSA_GM:   13.240696, 3.370950
t2s/CSA_WM:   65.202414, 3.112070
dmri/FA:  2018/08/08 - 15:57:04,/home/jcohen/sct_example_data/dmri/dti_FA.nii.gz,wa,Unknown,"2,3,4,5,6,7,8,9,10,11,12,13,14",4,WM left lateral corticospinal tract,80.5077761052,0.758846851538,0.167810495669
dmri/FA:  2018/08/08 - 15:57:04,/home/jcohen/sct_example_data/dmri/dti_FA.nii.gz,wa,Unknown,"2,3,4,5,6,7,8,9,10,11,12,13,14",5,WM right lateral corticospinal tract,81.3368825917,0.785060184288,0.143668976472
~~~

**Pull request merged**
