### PR TITLE
Add retrying to QC JSON reading

### PR DESCRIPTION
**Pull request by cfhammill**
Should solve the flaky test bug in #2683

Adds retrying as a dependency, which I think is lightweight enough, but happy to refactor to avoid the added dependency. As noted in the issue thread, I was unable to reproduce the failures locally, but I'm reasonably confident this will fix the error we've observed in CI.

### CODE REVIEW

**Comment by cfhammill** [comment]
@kousu would you mind giving this a quick review?

**Comment by kousu** [comment]
I have one idea for a more robust but still pretty basic solution: the reader uses glob to decide what files to load, so we can make sure the output file isn't marked ready for reading until it's fully written, the same way Firefox and Chrome do, with this:

```
        # Create json file
        with open(self.qc_params.qc_results+".tmp", 'w+') as qc_file:
            json.dump(output, qc_file, indent=1)
        os.rename(self.qc_params.qc_results+".tmp", self.qc_params.qc_results)
```
(assuming `rename()` is atomic, which it is on most systems).

This would stop the crash but it wouldn't deal with the basic problem that the reader isn't blocking on the writers like it should be -- so it would make the reader lose some data.

My next thought would be to set up a queue of results from the writers to the readers -- which should be easy; in fact that's pretty much exactly what `multiprocessing.Pool.map()`. But I am going to keep reading the code to see why/why not that may be possible here.

**Comment by jcohenadad** [comment]
for the records, we did use file locking in the past (https://github.com/neuropoly/spinalcordtoolbox/pull/2206), introduced the function `open_with_exclusive_lock()`, but then it was dropped [here](https://github.com/neuropoly/spinalcordtoolbox/commit/7d7e0d868653f1be400f74f8f23a6796d503e9e2#diff-cd0ed16d3a599345c58ea8bbd2fe675d) because it didn't solve the issue-- the solution (which, as we now today was not a solution), was to split the single `qc_results.json` file into separate files per process.

**Comment by kousu** [comment]
I do like `retrying` though; it's a very elegant little decorator.

**Comment by kousu** [comment]
> for the records, we did use file locking in the past (#2206), introduced the function `open_with_exclusive_lock()`, but then it was dropped [here](https://github.com/neuropoly/spinalcordtoolbox/commit/7d7e0d868653f1be400f74f8f23a6796d503e9e2#diff-cd0ed16d3a599345c58ea8bbd2fe675d) because it didn't solve the issue-- the solution (which, as we know today was not a solution), was to split the single `qc_results.json` file into separate files per process.

Ah that's good context! That solution is halfway there. The problem is that after writing the per-process output, each process immediately goes and re-reads *all* the output files.

If I was actually doing this I would do something like:

```
cat jobs.csv | parallel -n 2 generate_qc | generate_qc_summary
```

In this phrasing, the bug is because `generate_qc_summary` is embedded inside of `generate_qc`.

**Pull request closed without merging**
