### PR TITLE
Address issues #692, #694, #736 and #781

### PR DESCRIPTION
**Pull request by slevyrosetti**

### CODE REVIEW

**Comment by jcohenadad** [comment]
Simon, could you please run batch_processing on master and your branch, and copy/paste the results in this discussion (CSA, FA, MTR, etc.), so that we can compare the integrity as well.
Thanks!

**Comment by slevyrosetti** [comment]
Sure. However, the batch_processing (from master) crashes because of the variable SCT_DIR that does not exist anymore and that is called several times from different folders...

**Comment by jcohenadad** [comment]
i’ve created a new function **sct_env** (on master), that declares SCT_DIR. I've added the command on batch_processing. It should work (haven't tested it yet)

**Comment by jcohenadad** [comment]
Results of batch_processing on branch master (a72c7aca542dd691bae3b01ebb0e3b7d18573868):
~~~
# --> Mean CSA: 77.233663906 +/- 1.99475778691 mm^2
# --> Volume (in volume.txt): 2396.0 mm^3
# --> MTR = 34.2184255681
# --> Mean CSA of left CST: 5.14874876116 +/- 0.705719447293 mm^2
# --> Mean CSA of right CST: 4.92502099412 +/- 0.599001576209 mm^2
# --> Mean CSA of the left dorsal column: 9.80594348877 +/- 0.534758227893 mm^2
# --> 17, right lateral corticospinal tract:    0.797974493382
# --> 2, left lateral corticospinal tract:    0.753757041634
~~~

**Comment by slevyrosetti** [comment]
Results of batch_processing on branch sl_sct_extract_metric (b9cba14):
~~~
# --> Mean CSA: 77.233663906 +/- 1.99475778691 mm^2
# --> Volume (in volume.txt): 2396.0 mm^3
# --> MTR = 34.2184255681
# --> Mean CSA of left CST: 5.14874876116 +/- 0.705719447293 mm^2
# --> Mean CSA of right CST: 4.92502099412 +/- 0.599001576209 mm^2
# --> Mean CSA of the left dorsal column: 9.80594348877 +/- 0.534758227893 mm^2
# --> FA in: 17, right lateral corticospinal tract =     0.797974493382
# --> FA in: 2, left lateral corticospinal tract =     0.753757041634
~~~

**Pull request merged**
