### PR TITLE
Generate a changelog from GitHub

### PR DESCRIPTION
**Pull request by peristeri**

### CODE REVIEW

**Comment by jcohenadad** [comment]
i've tried it. This is a very helpful command, however i am wondering how we can display changes for beta releases?

**Comment by jcohenadad** [comment]
also, please do chmod on the function to be able to call it with ./

**Comment by peristeri** [comment]
In this iteration, I only focused on changes done in the latest release because it depends on the tags of the PR, and some commits don't have PR. Are you referring to previous releases? (such as 3.0_beta9)

**Comment by jcohenadad** [comment]
for example: next release will be beta_32. So, if we use this command, it will show up as "milestone 3.0", not beta_32.

**Comment by peristeri** [comment]
You are pointing out a problem in the name of milestone. I will change the name of the milestone. And this will force of milestone correctly.

**Comment by jcohenadad** [comment]
ok I agree with that approach

**Comment by jcohenadad** [comment]
would it be possible to change the title to be consistent with previous entries. Example:

Replace
Milestone "Release 3.0_beta32"

With:
3.0_beta32 (2017-02-10)

**Comment by jcohenadad** [comment]
also: the "compare branches" brings to a page with nothing to compare:
https://github.com/neuropoly/spinalcordtoolbox/compare/v3.0_beta31...3.0_beta32

**Pull request merged**
