### PR TITLE
Add CSA results on QC report 

### PR DESCRIPTION
**Pull request by jcohenadad**
This PR features a new entry to the QC report: CSA results. 

This report would also facilitate the optimization of default parameter for `get_centerline` (used for angle correction in CSA computation), see https://github.com/neuropoly/spinalcordtoolbox/pull/2299

To test:
```bash
sct_download_data -d sct_testing_data
cd sct_testing_data/t2
sct_process_segmentation -i t2_seg.nii.gz -qc qc-csa
```

### CODE REVIEW

**Comment by jcohenadad** [comment]
hum, strange. Can you go back to the master version and run `sct_testing`?

**Comment by YangHee-Min** [comment]
After running `sct_testing` on the master branch, all scripts get result `[OK]` except for `sct_process_segmentation` that fails. [Here is the full log](https://pastebin.com/WpmwYsT9)

**Comment by jcohenadad** [comment]
ah! interesting (only on Sierra build):
https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/542929536#L903

**Comment by YangHee-Min** [comment]
bug on Sierra likely related to: https://stackoverflow.com/questions/49414841/process-finished-with-exit-code-139-interrupted-by-signal-11-sigsegv

**Pull request merged**
