### PR TITLE
Restore previously deprecated sct_concat_transfo.py

### PR DESCRIPTION
**Pull request by Drulex**
#### GitHub

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [x] I've assigned a reviewer

#### PR contents

- [x] I've consulted [SCT's internal developer documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki) to ensure my contribution is in line with any relevant design decisions
- [x] I've added [relevant tests](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Tests) for my contribution
- [ ] I've updated the [relevant documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description
`sct_concat_transfo.py` was recently obsoleted, but after user feedback it was decided to un-deprecate and restore the script. https://github.com/neuropoly/spinalcordtoolbox/issues/2912#issuecomment-761897967

## Linked issues
#2912

### CODE REVIEW

**Review by jcohenadad — CHANGES_REQUESTED** [review]
Would it be possible to keep the default behaviour that we have in our other CLIs, when calling the function without the -h flag, that would run the help, instead of this reduced usage:
~~~
julien-macbook:~/sct_testing_data/mt $ sct_concat_transfo 

--
Spinal Cord Toolbox (git-aj/2912-revert-sct_concat_transfo-7e91387020b92ea38404d7dfd4a5877208d606b4)

sct_concat_transfo 
--

usage: sct_concat_transfo -d <file> -w <file> [<file> ...] [-winv [<file> [<file> ...]]] [-h] [-o <str>] [-v {0,1,2}]
sct_concat_transfo: error: the following arguments are required: -d, -w
~~~

I know that many of our users are not familiar with the Terminal, and they will not catch the "-h" in this reduced usage. If we immediately show the full usage, it would be better from UX standpoint. 

Tagging @joshuacwnewton because he was recently working on similar refactoring (related to argpars and argv default input for main())

**Review by jcohenadad — CHANGES_REQUESTED** [review]
I'm getting this error, even when the input image is 3d:
~~~
ERROR: Destination data must be 3d
~~~

To reproduce:
~~~
sct_download_data -d sct_testing_data
cd sct_testing_data/mt
sct_concat_transfo -d mt1.nii.gz -w warp_template2mt.nii.gz
~~~

Probably something funky with [check_dim()](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/image.py#L1409) function.

Despite this error, it seems like the processing goes on (which is also unexpected).

**Comment by joshuacwnewton** [comment]
Thanks for the tag, @jcohenadad.

@Drulex While you were away, we [subclassed `ArgumentParser`](https://github.com/neuropoly/spinalcordtoolbox/blob/9dec9dfd0d37c64c337008c30d0a301a422cf230/spinalcordtoolbox/utils/shell.py#L102-L140) in https://github.com/neuropoly/spinalcordtoolbox/pull/3139. This let us fix #3137, and allowed us centralize all of the parser config settings we were repeating across every script.

We also standardized the init steps for each script in https://github.com/neuropoly/spinalcordtoolbox/pull/3091. The new guidelines have been written [on this Wiki page](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-CLI-script-conventions-(structure,-argparse)).

**Comment by Drulex** [comment]
Ah ok I had not noticed. Thanks for the pointers, I will adapt immediately after lunch.

**Comment by Drulex** [comment]
> Would it be possible to keep the default behaviour that we have in our other CLIs, when calling the function without the -h flag, that would run the help, instead of this reduced usage:

So after fixing that I decided to add a unit test to check that all scripts don't return 0 if called without argument. To my surprise there was already a unit test that did just that (also exactly where I was planning on adding, but unfortunately it failed to detect this error.

https://github.com/neuropoly/spinalcordtoolbox/blob/9dec9dfd0d37c64c337008c30d0a301a422cf230/unit_testing/cli/test_cli.py#L37-L44

I suspect it has to do with the stacked decorators, though I haven't yet investigated. Will create an issue.

**Comment by joshuacwnewton** [comment]
Ahh, good catch, @Drulex. My use of `assert 'usage' in captured.err.lower()` was not specific enough. :sweat_smile: 

I was trying to keep it general enough to include our argparse-based scripts, and the scripts still not using argparse. But, I made it too general!

**Comment by Drulex** [comment]
> Ahh, good catch, @Drulex. My use of `assert 'usage' in captured.err.lower()` was not specific enough. sweat_smile
> 
> I was trying to keep it general enough to include our argparse-based scripts, and the scripts still not using argparse. But, I made it too general!

There is a `assert system_err.value.code is 2` which is appropriate. The scripts was returning 0 so there must be another problem.

**Comment by Drulex** [comment]
https://github.com/neuropoly/spinalcordtoolbox/issues/3186

**Comment by Drulex** [comment]
> Probably something funky with [check_dim()](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/image.py#L1409) function.
> 
> Despite this error, it seems like the processing goes on (which is also unexpected).

Indeed `check_dim()` does not return anything (it raises internally) so there is no point checking the return..

**Comment by jcohenadad** [comment]
@Drulex struggling with git-- i wanted to test your latest changes, so i did a `git pull`  (i was already on your branch), and ended up with conflicts:
~~~
julien-macbook:~/code/sct $ gs
M  spinalcordtoolbox/centerline/core.py
M  spinalcordtoolbox/gui/centerline.py
AA spinalcordtoolbox/scripts/sct_concat_transfo.py
~~~

**Comment by Drulex** [comment]
> @Drulex struggling with git-- i wanted to test your latest changes, so i did a `git pull` (i was already on your branch), and ended up with conflicts:
> 
> ```
> julien-macbook:~/code/sct $ gs
> M  spinalcordtoolbox/centerline/core.py
> M  spinalcordtoolbox/gui/centerline.py
> AA spinalcordtoolbox/scripts/sct_concat_transfo.py
> ```

```
git reset --hard origin/aj/2912-revert-sct_concat_transfo
```

**Review by jcohenadad — APPROVED** [review]
i'm approving it because this is a minor issue, but it would be nice to fix it either here or in a subsequent PR: the duplication of "Spinal Cord Toolbox (git-...)" and "File created: " 

<details><summary>here</summary>

```
julien-macbook:~/sct_testing_data/mt $ sct_concat_transfo -d mt1.nii.gz -w warp_template2mt.nii.gz -o pouf.nii.gz

--
Spinal Cord Toolbox (git-aj/2912-revert-sct_concat_transfo-4f1aa2ffdad1a3d441be8f415829e750f24e3280)

sct_concat_transfo -d mt1.nii.gz -w warp_template2mt.nii.gz -o pouf.nii.gz
--


--
Spinal Cord Toolbox (git-aj/2912-revert-sct_concat_transfo-4f1aa2ffdad1a3d441be8f415829e750f24e3280)


--
Spinal Cord Toolbox (git-aj/2912-revert-sct_concat_transfo-4f1aa2ffdad1a3d441be8f415829e750f24e3280)

sct_concat_transfo -d mt1.nii.gz -w warp_template2mt.nii.gz -o pouf.nii.gz
--

sct_concat_transfo -d mt1.nii.gz -w warp_template2mt.nii.gz -o pouf.nii.gz
--


Parse list of warping fields...

Check file existence...
  OK: mt1.nii.gz
  OK: warp_template2mt.nii.gz
/Users/julien/code/sct/bin/isct_ComposeMultiTransform 3 warp_final.nii.gz -R mt1.nii.gz warp_template2mt.nii.gz # in /Users/julien/sct_testing_data/mt

Generate output files...
File created: pouf.nii.gz
File created: pouf.nii.gz

```

</details>

**Comment by Drulex** [comment]
> i'm approving it because this is a minor issue, but it would be nice to fix it either here or in a subsequent PR: the duplication of "Spinal Cord Toolbox (git-...)" and "File created: "

Removed the code causing duplication + cleaned up the script a bit.

**Pull request merged**
