### PR TITLE
shell/sct_run_batch.sh: Added script to run batch files

### LINKED ISSUE #2329: Add bash script for batch processing
The script [run_process](https://github.com/sct-pipeline/spine-generic/blob/master/processing/run_process.sh), which has been developed for a few projects relying on SCT, proved to be very useful. Currently, there are different versions of this file across multiple projects, so the idea would be to create only one version and host it under SCT. Few questions:

- Where should we put it? One suggestion would be under a new folder `${SCT_DIR}/bash/`. The installer would then add this directory to the ${PATH}.

### PR DESCRIPTION
**Pull request by jcohenadad**
Added a wrapper `sct_run_batch.sh` to loop across multiple subjects and run batch files. This could ultimately be written in Python, but for now that's that.

Fixes #2329

Related issues to fix later: https://github.com/neuropoly/spinalcordtoolbox/issues/2387, #2388

### CODE REVIEW

**Comment by charleygros** [comment]
That's a great idea! Thank you.

I tried to use this as follows, but I am missing something:
```
charley@charley:~/sct/sct_course-beijing19/multi_subject$ ./../../shell/sct_run_batch.sh parameters.sh process_data.sh 
Processing:
/home/charley/sct/sct_course-beijing19/multi_subject/data/sub-05
/home/charley/sct/sct_course-beijing19/multi_subject/data/sub-03
/home/charley/sct/sct_course-beijing19/multi_subject/data/sub-01
GNU parallel is not installed. Processing subjects sequentially.

/home/charley/sct/sct_course-beijing19/multi_subject/process_data.sh: ligne 20 : cd: anat/: Aucun fichier ou dossier de ce type
...etc.
```
Is it the appropriate way to use it?

**Comment by jcohenadad** [comment]
Yes, it is the appropriate way but I have not updated the Beijing script accordingly yet. Will do it now

**Comment by jcohenadad** [comment]
also: i need to create a symlink to the sct/bin folder so it is in your PATH

**Comment by jcohenadad** [comment]
@charleygros can you please try again with the latest commit, reinstalling SCT (to get the symlinks), and re-downloading the Beijing data:
~~~
sct_download_data -d sct_course-beijing19
~~~
Thanks!!!

**Comment by charleygros** [comment]
Commit [2d48d25](https://github.com/neuropoly/spinalcordtoolbox/pull/2386/commits/2d48d25bbefc9738796231eb70d86de3995858f7) fixes the instability of test_deepseg_lesion.py::test_intensity_normalization.

Fixes #2312.

**Pull request merged**
