### PR TITLE
Obsolete -denoise functionality

### LINKED ISSUE #2976: Possibly erroneous call to sct_math in sct_label_vertebrae
`sct_label_vertebrae` makes the following subprocess call:

https://github.com/neuropoly/spinalcordtoolbox/blob/5743157e5c011529ca8e566e5f4e3dc554901958/scripts/sct_label_vertebrae.py#L409

But the argument to `denoise` is `h=0.05` which doesn't really makes sense given the description of the argument:

https://github.com/neuropoly/spinalcordtoolbox/blob/5743157e5c011529ca8e566e5f4e3dc554901958/scripts/sct_maths.py#L195-L202

I am wondering if the code is silently failing given that `denoise` has default values for `p` and `b`, thus the `h=0.05` is completely ignored:

https://github.com/neuropoly/spinalcordtoolbox/blob/5743157e5c011529ca8e566e5f4e3dc554901958/scripts/sct_maths.py#L366-L375

In the scope of #2975

### PR DESCRIPTION
**Pull request by Drulex**
After #2966

Closes #2976 

As per suggestion: https://github.com/neuropoly/spinalcordtoolbox/issues/2976#issuecomment-718058597

### CODE REVIEW

**Review by jcohenadad — COMMENTED** [review]
how come 87 files have changed for this PR? i assume it is undesired behaviour

**Comment by Drulex** [comment]
> how come 87 files have changed for this PR? i assume it is undesired behaviour

This is to be merged after #2966 (as mentioned in the description). I branched off that to avoid future conflicts since I changed the import statements all over the place.

I should leave it in draft to avoid confusion sorry.

**Comment by jcohenadad** [comment]
> This is to be merged after #2966 (as mentioned in the description). I branched off that to avoid future conflicts since I changed the import statements all over the place.

ah! ok got it. I've never created PR out of non-master branches so I was a bit confused, but it makes perfect sense. I'll know for the future 👍

**Comment by Drulex** [comment]
> ah! ok got it. I've never created PR out of non-master branches so I was a bit confused, but it makes perfect sense. I'll know for the future +1

@jcohenadad you can give it another look, it is rebased properly now

**Review by jcohenadad — APPROVED** [review]

**Comment by jcohenadad** [comment]
@Drulex i've updated the title otherwise the automatic label-based changelog would show: `sct_label_vertebrae: sct_label_vertebrae: Obsolete -denoise functionality`

**Comment by Drulex** [comment]
> @Drulex i've updated the title otherwise the automatic label-based changelog would show: `sct_label_vertebrae: sct_label_vertebrae: Obsolete -denoise functionality`

Good point, will keep in mind next time.

**Pull request merged**
