### PR TITLE
[FEATURE] Introduce QC report generation

### PR DESCRIPTION
**Pull request by peristeri**
For the commands `sct_propseg`, `sct_label_vertebrae` and
`sct_register_to_template`, an extra parameter is added. The parameter takes a
output path and generates png images of the input and segmentaion output as well
as log of output values.

Partial implements #1247

### CODE REVIEW

**Comment by jcohenadad** [comment]
is it ready to be tested?

**Comment by peristeri** [comment]
@jcohenadad yes it is.

**Comment by jcohenadad** [comment]
warning after propseg, then error after sct_qc:
~~~

Done! To view results, type:
fslview t2.nii.gz t2_seg.nii.gz -l Red -b 0,1 -t 0.7 &

/Users/julien/code/sct/python/lib/python2.7/site-packages/scipy/ndimage/measurements.py:1301: RuntimeWarning: invalid value encountered in double_scalars
  for dir in range(input.ndim)]
WARNING:/Users/julien/code/sct/spinalcordtoolbox/reports/qc.py:Can not get GIT hash value
Sucessfully generate the QC results in ~/qc_data/qc_results.json
Use "sct_qc -folder ~/qc_data" to see the results on a browser
julien-macbook:~/data/temp/sct_015/t2 $ sct_qc -folder ~/qc_data

--
Spinal Cord Toolbox (qc-generator/af8edf141656c541c5d75d7bad47387ae46d690b)
Running /Users/julien/code/sct/scripts/sct_qc.py -folder /Users/julien/qc_data
Check folder existence...
Can not start the quality control viewer. This is not a proper QC folder

/Users/julien/code/sct/scripts/sct_qc.pyNone
~~~

**Comment by peristeri** [comment]
@jcohenadad  can you list me the contents of the `~/qc_data` folder?

**Comment by jcohenadad** [comment]
it is empty

**Comment by jcohenadad** [comment]
I do this and nothing happens:
~~~
sct_qc -folder ~/qc_data/

--
Spinal Cord Toolbox (qc-generator/dcb7cbff9c58599894aa0ba145c1d0fa8ef9c5dc)
Running /Users/julien/code/sct/scripts/sct_qc.py -folder /Users/julien/qc_data/
Check folder existence...
QC viewer started on http://127.0.0.1:8888
Press "Ctrl" + "C" to stop sct_qc
~~~

**Comment by jcohenadad** [comment]
can you please make the segmentation blink twice as fast?

**Comment by jcohenadad** [comment]
I've added another command for the same subject (label_vertebrae), but when generating the report i only get the view for propseg.

**Comment by jcohenadad** [comment]
- [ ] error with label_vertebrae: /Users/julien/code/sct/python/lib/python2.7/site-packages/scipy/ndimage/measurements.py:1301: RuntimeWarning: invalid value encountered in double_scalars
  for dir in range(input.ndim)]
- [ ] get rid of the warning
- [ ] I've added another command for the same subject (label_vertebrae), but when generating the report i only get the view for propseg.
- [ ] can you please make the segmentation blink twice as fast?
- [ ] Sucessfully generate --> Sucessfully generated
- [ ] put in next line: sct_qc -folder /Users/julien/qc_data, and in green ('info' in printv)
- [ ] change sct_qc message for: "Please open a browser and copy/paste this link: [next line] sct_qc -folder /Users/julien/qc_data ('info' in printv)
- [ ] add small space between picture and table

**Comment by jcohenadad** [comment]
i unchecked some boxes after testing it:
~~~

**Pull request merged**
