### PR TITLE
Lint pull requests using flake8 GH Actions workflow

### LINKED ISSUE #1538: Integrate linters into TravisCI
In order to automatically catch small issues like unused imports, undefined variables, etc, we can just integrate tools such as [Flake8](http://flake8.pycqa.org/en/latest/index.html), [Pylinter](https://www.pylint.org/) and [PEP8](https://pypi.python.org/pypi/pep8) into the continuous integration. By doing that, pull-requests can be fixed before the review process, taking less time of reviewers and enforcing code-style conventions, etc.

### PR DESCRIPTION
**Pull request by joshuacwnewton**
#### GitHub

- [X] I've given this PR a concise, self-descriptive, and meaningful title
- [X] I've linked relevant issues in the PR body
- [X] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [ ] I've assigned a reviewer

#### PR contents

- [X] I've consulted [SCT's internal developer documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki) to ensure my contribution is in line with any relevant design decisions
- [ ] I've added [relevant tests](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Tests) for my contribution
- [ ] I've updated the [relevant documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description

This PR makes use of [Lintly](https://github.com/grantmcconnaughey/Lintly) and its `flake8` output parser to lint the diffs on PRs. Lintly also supports Black, Pylint, etc. so we can experiment depending on our tastes.

One detail to note is the use of `--fail-on new`. This causes only new violations to be reported, not all existing ones. If we ever spend the time to go through the codebase as a whole, this could be changed to `--fail-on any`.

Related to this: I tested one other tool, [`flake8-your-pr`](https://github.com/valentijnscholten/flake8-your-pr). It runs its linter across the entirety of any file that has changed. So, if you edit a file, it will report all existing linting violations within that file. This is like a halfway point between `lintly --fail-on new` and `lintly --fail-on any`, and could be valuable for nudging us to fix existing violations within PRs. But, that might expand the scope of PRs too greatly, so I've stuck with Lintly for now.

## Linked issues

Fixes #1538.

### CODE REVIEW

**Comment by joshuacwnewton** [comment]
I introduced a demo linting violation. To see what the output of Lintly looks like, check out:

* File annotations: https://github.com/neuropoly/spinalcordtoolbox/pull/3215/commits/3dd9549ee8ac4c084863f116514beb672cbaaf10
* https://github.com/neuropoly/spinalcordtoolbox/actions/runs/551892117

**Review by Drulex — COMMENTED** [review]
It's a good initiative to run linting on new code introduced.

Is there a way that we can put a config for `flake8` in the repo so that people who want to run linting locally can do so prior to pushing? It will also be useful for adding rules that we may want to ignore and also help with progressively fixing existing linting issues.

**Comment by joshuacwnewton** [comment]
> Is there a way that we can put a config for flake8 in the repo so that people who want to run linting locally can do so prior to pushing?

Yes, absolutely! Flake8 [picks up configuration settings](https://flake8.pycqa.org/en/latest/user/configuration.html#configuration-locations) in `setup.cfg` (or in other config files).

**Review by Drulex — APPROVED** [review]
:+1:

**Pull request merged**
