### PR TITLE
Add slightly modified PR template from shimming-toolbox

### LINKED ISSUE #3027: Add pull request template that mirrors shimming-toolbox
@jidicula created a great [PR template](https://github.com/shimming-toolbox/shimming-toolbox/blob/master/.github/pull_request_template.md) in `shimming-toolbox`. I propose that we add it to `SCT` as well, as it covers some important points. (I personally forget to add labels too often so this reminder would be good for me! :sweat_smile:)

### PR DESCRIPTION
**Pull request by joshuacwnewton**
### Related Issues/PRs

Fixes #3027.

### Description

~~Mirror of [`shimming-toolbox/pull_request_template.md`](https://github.com/shimming-toolbox/shimming-toolbox/blob/master/.github/pull_request_template.md).~~

Some changes have been made, mainly:
* Adding additional checklist items to ensure internal documentation is followed.
* Adding links to relevant internal documentation pages.
* Grouping checklist items by type.

### CODE REVIEW

**Comment by joshuacwnewton** [comment]
(I cancelled the CI intentionally. I do wish that GitHub's UI would properly reflect this instead of showing it as a failure!)

**Comment by joshuacwnewton** [comment]
I've tagged you @Drulex because I remembered that you created that excellent [PR checklist](https://github.com/neuropoly/spinalcordtoolbox/wiki/Contributing%3A-Pull-request-checklist) in the Wiki. I'm wondering if you have any thoughts about what our PR checklist should look like? :slightly_smiling_face:

**Review by Drulex — APPROVED** [review]
Looks good. Maybe one suggestion to add:
```
[ ] I've followed the contribution guidelines described in the wiki.
```
Or something similar. What do you think?

**Comment by joshuacwnewton** [comment]
Good idea, @Drulex! I've added that, and a few other tweaks that I think might be helpful. :)

**Comment by joshuacwnewton** [comment]
Ah, I think I might want to wait to merge this. I'd like to add a link to a "Documentation" page on our dev Wiki (that explains how to build docs locally, and talks about good practices), but it doesn't exist yet. So, I think I want to write that quickly then update the link, as I did in 04e3686 with the Tests dev wiki page.

**Review by Drulex — APPROVED** [review]

**Pull request merged**
