### PR TITLE
Changed source of nipy installation to fork

### LINKED ISSUE #2267: ImportError: cannot import name 'factorial' from 'scipy.misc'
New deprecation from nipy: https://github.com/nipy/nipy/issues/453

more info at: https://scipy.github.io/devdocs/release.1.3.0.html#scipy-interpolate-changes
Travis fail: https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/535398407#L1012

### PR DESCRIPTION
**Pull request by YangHee-Min**
In this PR, we are changing the source to the fork jcohenadad/nipy from nipy/nipy due to the new deprecation. (overcomes #2267)

We do this in order to keep an old version of nipy that still has the factorial function that is used in many of the scripts. 
 
At the moment, the PR is not working. Indeed, after using the function install_sct and verifying installation, we obtain the following log:
 Validate installation...
SCT info:
- version: git-HMY/2267-nipy-fork-79629ea34a2d61e335e8bf6dfedd87037bd909a7
- path: /Users/heyan_admin/2267/sct
OS: osx (Darwin-16.7.0-x86_64-i386-64bit)
CPU cores: Available: 4, Used by SCT: 4
RAM: Primary memory available: 12.00 gigabytes
Check Python executable.............................[OK]
  Using bundled python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] at /Users/heyan_admin/2267/sct/python/bin/python
Check if data are installed.........................[OK]
Check if numpy is installed.........................[OK] (1.16.3)
Check if cryptography is installed..................[OK] (2.6.1)
Check if dipy is installed..........................[OK] (0.16.0)
Check if futures is installed.......................[OK]
Check if h5py is installed..........................[OK] (2.9.0)
Check if Keras is installed.........................[OK] (2.2.4)
Check if matplotlib is installed....................[OK] (3.1.0)
Check if nibabel is installed.......................[OK] (2.4.0)
Check if pandas is installed........................[OK] (0.24.2)
Check if psutil is installed........................[OK] (5.6.2)
Check if pyqt5 is installed.........................[OK]
Check if raven is installed.........................[OK]
Check if requests is installed......................[OK] (2.21.0)
Check if scipy is installed.........................[OK] (1.3.0)
Check if scikit-image is installed..................[OK] (0.15.0)
Check if scikit-learn is installed..................[OK] (0.21.1)
Check if tensorflow is installed....................[OK] (1.13.1)
Check if xlrd is installed..........................[OK] (1.2.0)
Check if xlutils is installed.......................[OK]
Check if xlwt is installed..........................[OK] (1.3.0)
Check if tqdm is installed..........................[OK] (4.32.1)
Check if transforms3d is installed..................[OK] (0.3.1)
Check if urllib3[secure] is installed...............[OK] (1.24.1)
Check if git+https://github.com/jcohenadad/nipy.git is installed[FAIL]
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if figure can be opened.......................[OK]

Installation validation Failed!
Please copy the historic of this Terminal (starting with the command install_sct) and paste it in the SCT Help forum (create a new discussion):
http://forum.spinalcordmri.org/c/sct

Installation failed

The full log can be found in the pdf below:
[Issue 2267: installation log.pdf](https://github.com/neuropoly/spinalcordtoolbox/files/3208647/Issue.2267.installation.log.pdf)

### CODE REVIEW

**Comment by jcohenadad** [comment]
is this PR working? if not please describe the problem (and error you get)

**Comment by jcohenadad** [comment]
@YangHee-Min looks like the install is OK, but the error only comes from the way we check for the presence of module (by parsing the requirements). Could you pls make sure scipy and nipy are properly installed (activate python env, call python, import modules).

also please, don't upload pdf for sharing terminal output, instead use external website or collapsable markdown feature as described [here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/CONTRIBUTING.rst#issue-body).

**Comment by YangHee-Min** [comment]
@jcohenadad After calling the python environment within terminal, we were able to import scipy, but we were not able to import nipy. Therefore, scipy was properly installed, but nipy was not.

**Comment by jcohenadad** [comment]
> scipy was properly installed, but nipy was not.

this is what i did:
~~~
git checkout -b YangHee-Min-HMY/2267-temporary-fix master
git pull https://github.com/YangHee-Min/spinalcordtoolbox.git HMY/2267-temporary-fix
yes | ./install_sct
python/bin/python
import nipy
~~~
and the import went well, which is inconsistent with your test @YangHee-Min.

@YangHee-Min could you please describe precisely what you did?

**Comment by YangHee-Min** [comment]
This is what I did in a new folder starting from my sct folder:
`cd python/bin/python
python
import nipy`
And at that point it said that the module did not exist

**Comment by jcohenadad** [comment]
@YangHee-Min 
run this and pls copy/paste your terminal:
~~~
cd python/bin/python
python
~~~

i suspect you are not using the correct python (i.e. check your $PATH)

**Comment by YangHee-Min** [comment]
Oops I made a mistake: for my exact steps instead of cd `python/bin/python` I did `cd python/bin` and then did `python`

**Comment by YangHee-Min** [comment]
Here is what I get from my terminal.
```
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 

```
I suppose it has to do with the fact I need to use python3?

**Comment by jcohenadad** [comment]
@YangHee-Min i fixed check_dependencies here:
https://github.com/neuropoly/spinalcordtoolbox/commit/2421463cd5df71cb91a57728924df75ab59b49a5

please include to your branch (i cannot push, you've forked it). in the future, pls create a branch directly on this repos to allow team work.

**Comment by jcohenadad** [comment]
> Python 2.7.10

you are not using the correct python (you are using the one set in your $PATH). To call it directly, reproduce my steps. Anyway, there is no point in doing it now. Just so you know for the future.

**Pull request merged**
