### PR TITLE
e-mail fixups (#1701)

### PR DESCRIPTION
**Pull request by zougloub**
This PR brings (see #1701, #1414):
- allow sending from something else than GMail
- allow using a login different from the sender address
- use multipart/alternative when HTML is used
- encode text

### CODE REVIEW

**Comment by zougloub** [comment]
@fperdigon if you have something to add the branch is yours

**Comment by jcohenadad** [comment]
@zougloub this is a nice step forward, but to me it doesn't solve #1701 or #1414. Concretely, when we have to send an email (e.g. after running `sct_pipeline`), what server should we use? Those issues are specifically about that. Maybe there is no "good" existing solution, I don't know.

**Comment by zougloub** [comment]
If you want to send e-mails without authentication you would need to use the recipients SMTP server (an open server would be prone to abuse and quickly blacklisted), and even with that technique today, with DKIM & co, there's no guarantee that this way would work (ie. e-mails would most probably land in the spam folder). So what you'd like to have is unfortunately not possible.

**Comment by fperdigon** [comment]
@jcohenadad I understand your point, but technically it is not viable because what @zougloub  says happens. Maybe you can ask for an email to the university something like sct@polymtl.ca

**Comment by jcohenadad** [comment]
@zougloub @fperdigon: i am not trying to send an email without notification. I just wanted a suggestion for a good alternative to gmail (because even with authentification gmail is causing trouble), that everyone in the lab can use with the same credentials for homogenizing our debugging procedures. But I realize now that this is probably not a good idea, and that using our own credentials (with another smtp than gmail) is a viable alternative. I tried with polymtl and it works well so let's just use that in the future (for those who have a polymtl address).

I also fixed a [minor usage issue](https://github.com/neuropoly/spinalcordtoolbox/pull/1722/commits/c0b755c52a1507a001160cf946cc6ab7cb17d86f), so it should be ready for merge soon.

**Pull request merged**
