### PR TITLE
Used the absolute path to create the temporary label file in propseg

### LINKED ISSUE #1483: viewer broken
### Description

Viewer broken. The QT windows opens, then closes with error on Terminal.

### Steps to Reproduce

See below.

### State of spinalcordtoolbox

Spinal Cord Toolbox (master/69b28b03f6a615cf45ae8b3c734ef905afbd8e9e)

### Additional Information

~~~
sct_propseg -i avg.016.nii -c t2s -init-mask viewer

--
Spinal Cord Toolbox (master/69b28b03f6a615cf45ae8b3c734ef905afbd8e9e)
Running /Users/julien/code/sct/scripts/sct_propseg.py -i avg.016.nii -c t2s -init-mask viewer
/Users/julien/code/sct/python/lib/python2.7/site-packages/matplotlib/axes/_base.py:1215: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if aspect == 'normal':
/Users/julien/code/sct/python/lib/python2.7/site-packages/matplotlib/axes/_base.py:1220: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aspect in ('equal', 'auto'):
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_propseg.py", line 444, in <module>
    controller = launch_centerline_dialog(image, tmp_output_file, params)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/spinalcordtoolbox/gui/centerline.py", line 209, in launch_centerline_dialog
    dialog_ = Centerline(controller)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/spinalcordtoolbox/gui/centerline.py", line 109, in __init__
    super(Centerline, self).__init__(*args, **kwargs)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/spinalcordtoolbox/gui/base.py", line 100, in __init__
    self._init_ui()
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/spinalcordtoolbox/gui/base.py", line 112, in _init_ui
    self.setWindowTitle(self.params.dialog_title)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/spinalcordtoolbox/gui/base.py", line 54, in dialog_title
    self._title = '{}: manual labeling'.format(self.input_file_name)
AttributeError: 'AnatomicalParams' object has no attribute 'input_file_name'
~~~

### PR DESCRIPTION
**Pull request by peristeri**
### Description of the Change

The filename for the temporary label file did not match with the one used when cleaning up.

### Applicable Issues

Implements or Fixes #1483

### CODE REVIEW

**Comment by jcohenadad** [comment]
tested-- still failing. Should we reinstall sct?

**Comment by jcohenadad** [comment]
Tested the viewer. There is no crash, however the functionality is broken. Example here:
https://www.dropbox.com/s/ekeqwlfsgj7ihxt/20171013_bugViewer.m4v?dl=0

@peristeri: This is **HIGH** priority. If you cannot fix it today, please come back to the previous version of the viewer we had prior to introducing the QT version.

**Comment by peristeri** [comment]
the behavior is as expected. It allows maximum 3 points. If that's not the
case, I could remove the limit.

**Comment by jcohenadad** [comment]
@peristeri: this not correct. -init-mask asks for three points while -init-centerline asks for any number of points along the centerline.

**Comment by peristeri** [comment]
OK. I'll fix that soon.

**Comment by jcohenadad** [comment]
tested 5bcbd705c2dd5041a529cbdd45887ec81ff63583:
- init-mask: previous behaviour was that the first slice would be located in the middle slice (currently top slice)

**Comment by jcohenadad** [comment]
@peristeri: your latest commit 1e3775720df643e11419c9a802ce48ff70e6784c does not fix the issue i raised here: https://github.com/neuropoly/spinalcordtoolbox/pull/1487#issuecomment-336576746.
i'll take care of it.

**Pull request merged**
