### PR TITLE
Refactor things dealing with dataset `info_label.txt` metadata file

### PR DESCRIPTION
**Pull request by zougloub**
Some datasets available with SCT contain a metadata file called `info_label.txt`:
```
./data/sct_course-hawaii17/single_subject_processed/data/dmri/label/atlas/info_label.txt
./data/sct_course-hawaii17/single_subject_processed/data/dmri/label/template/info_label.txt
./data/sct_course-hawaii17/single_subject_processed/data/fmri/label/spinal_levels/info_label.txt
./data/sct_course-hawaii17/single_subject_processed/data/fmri/label/template/info_label.txt
./data/sct_course-hawaii17/single_subject_processed/data/mt/label/atlas/info_label.txt
./data/sct_course-hawaii17/single_subject_processed/data/mt/label/template/info_label.txt
./data/sct_course-hawaii17/single_subject_processed/data/t2/label/template/info_label.txt
./data/PAM50/atlas/info_label.txt
./data/PAM50/spinal_levels/info_label.txt
./data/PAM50/template/info_label.txt
./test-py2k/sct_testing_data/mt/label/atlas/info_label.txt
./test-py2k/sct_testing_data/mt/label/template/info_label.txt
./test-py2k/sct_testing_data/template/template/info_label.txt
./test-py2k/sct_example_data/dmri/label/template/info_label.txt
./test-py2k/sct_example_data/dmri/label/atlas/info_label.txt
./test-py2k/sct_example_data/mt/label/template/info_label.txt
./test-py2k/sct_example_data/mt/label/atlas/info_label.txt
./test-py2k/sct_example_data/mt/sct_testing_data/mt/label/atlas/info_label.txt
./test-py2k/sct_example_data/mt/sct_testing_data/mt/label/template/info_label.txt
./test-py2k/sct_example_data/mt/sct_testing_data/template/template/info_label.txt
./test-py2k/sct_example_data/t2/label/template/info_label.txt
./test-py2k/sct_example_data/t2/label/atlas/info_label.txt
```

The format is not documented and dealing with such files is done with ad-hoc code that is not located in one place.

This PR:

- Clarifies `info_label.txt` format
- Concentrates code to deal with such files

How:

- Introduce a sct module (called `metadata`, for lack of a better name) with code to deal with it, updating code to use it instead of local functions. There's a main `InfoLabel` class, and functions that were used before have become helper functions using this main class.

### CODE REVIEW

**Comment by zougloub** [comment]
Will submit for review once `sct_warp_template` QC and viewer syntax printout is re-enabled...

**Comment by zougloub** [comment]
@jcohenadad le [code de qc/display_viewer_syntax de sct_warp_template](https://github.com/neuropoly/spinalcordtoolbox/blob/cJ-infolabel/scripts/sct_warp_template.py#L235) fait référence à des labels qui n'existent pas nécessairement (eg. dans `sct_testing_data/template/template/info_label.txt`) et je me demande ce qui serait la bonne approche (pour faire rouler le QC ou le print de visu).

I'd propose to have a heuristic which find labels which look like something we'd want to see, and if not present, just skip QC and/or viewer syntax printout.

**Comment by zougloub** [comment]
yeah sorry :)

**Comment by jcohenadad** [comment]
Successfully tested `batch_processing` on 43ae3e1a34b30a0a3cf6d0aa4933f0ba77687b68:
~~~
t2/CSA:   77.336978, 1.698544
mt/MTR:   51, white matter, 2814.913787, 22.007195, 0.000000
mt/CSA_GM:   19.382674, 1.640991
mt/CSA_WM:   58.453443, 2.413917
dmri/FA:  4, WM left lateral corticospinal tract, 76.198243, 0.701325, 0.153041
dmri/FA:  5, WM right lateral corticospinal tract, 70.623472, 0.736442, 0.144799
~~~

**Pull request merged**
