### PR TITLE
Add qc params in sct_fmri_moco and sct_dmri_moco

### LINKED ISSUE #3274: Introduce qc parameters to sct_fmri_moco and sct_dmri_moco
Add the following entry parameters to sct_fmri_moco and sct_dmri_moco:

- -qc : path for QC report
- -qc-fps : float number, frame rate of the output gif images. Default value is 2 fps.
- -qc-dataset : string, dataset the process war run on
- -qc-subject : string, subject the process was run on

**Sub-issue from :** #3242

### PR DESCRIPTION
**Pull request by claragiroux**
#### GitHub

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [ ] I've applied a [release milestone](https://github.com/neuropoly/spinalcordtoolbox/milestones) (major, minor, patch) in line with [Semantic Versioning guidelines](https://github.com/neuropoly/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release#convention-for-naming-releases) 
- [x] I've assigned a reviewer

#### PR contents

- [x] I've consulted [SCT's internal developer documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki) to ensure my contribution is in line with any relevant design decisions
- [ ] I've added [relevant tests](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Tests) for my contribution
- [ ] I've updated the [relevant documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description

This PR adds the following entry parameters to sct_fmri_moco and sct_dmri_moco:
-qc : path for QC report
-qc-fps : float number, frame rate of the output gif images. Default value is 2 fps.
-qc-dataset : string, dataset the process war run on
-qc-subject : string, subject the process was run on

It also adds the call for the generate_qc in sct_fmri_moco and sct_dmri_moco.

In moco_wrapper, the parameter fname_moco is returned for use in qc_report.

## Linked issues
Fixes #3274

### CODE REVIEW

**Comment by jcohenadad** [comment]
Trying to review this PR, i did the following:
~~~
git checkout -b claragiroux-3274-add-qc-params-in-moco-functions master
# Switched to a new branch 'claragiroux-3274-add-qc-params-in-moco-functions'
sct_fmri_moco
~~~

<details><summary>Here is the usage of the function</summary>

```
--
Spinal Cord Toolbox (git-claragiroux-3274-add-qc-params-in-moco-functions-60ea08c9d664cf403f2982f8f5c8ae1cc5d704a3)

sct_fmri_moco 
--

sct_fmri_moco: error: the following arguments are required: -i

usage: sct_fmri_moco -i <file> [-h] [-g <int>] [-m <file>] [-param <list>] [-ofolder <folder>]
                     [-x {nn,linear,spline}] [-r <int>] [-v <int>]

Motion correction of fMRI data. Some robust features include:
  - group-wise (-g)
  - slice-wise regularized along z using polynomial function (-p)
    (For more info about the method, type: isct_antsSliceRegularizedRegistration)
  - masking (-m)
  - iterative averaging of target volume

The outputs of the motion correction process are:
  - the motion-corrected fMRI volumes
  - the time average of the corrected fMRI volumes
  - a time-series with 1 voxel in the XY plane, for the X and Y motion direction (two separate files), as required for FSL analysis.
  - a TSV file with the slice-wise average of the motion correction for XY (one file), that can be used for Quality Control.

MANDATORY ARGUMENTS:
  -i <file>             Input data (4D). Example: fmri.nii.gz

OPTIONAL ARGUMENTS:
  -h, --help            Show this help message and exit.
  -g <int>              Group nvols successive fMRI volumes for more robustness.
  -m <file>             Binary mask to limit voxels considered by the registration metric.
  -param <list>         Advanced parameters. Assign value with "="; Separate arguments with ",".
                          - poly [int]: Degree of polynomial function used for regularization along
                          Z. For no regularization set to 0. Default=2.
                          - smooth [mm]: Smoothing kernel. Default=0.
                          - iter [int]: Number of iterations. Default=10.
                          - metric {MI, MeanSquares, CC}: Metric used for registration.
                          Default=MeanSquares.
                          - gradStep [float]: Searching step used by registration algorithm. The
                          higher the more deformation allowed. Default=1.
                          - sampling [None or 0-1]: Sampling rate used for registration metric.
                          Default=None.
                          - numTarget [int]: Target volume or group (starting with 0). Default=0.
                          - iterAvg [int]: Iterative averaging: Target volume is a weighted average
                          of the previously-registered volumes. Default=1.
  -ofolder <folder>     Output path. (default: ./)
  -x {nn,linear,spline}
                        Final interpolation. (default: linear)
  -r <int>              Remove temporary files. O = no, 1 = yes (default: 1)
  -v <int>              Verbosity. 0: Display only errors/warnings, 1: Errors/warnings + info
                        messages, 2: Debug mode (default: 1)
```

</details>

I don't see the added "qc" flags, even though they are supposed to be present in this tested commit. I am wondering if something recently changed in the way we install SCT for devs? @joshuacwnewton @Drulex ?

**Comment by Drulex** [comment]
> I don't see the added "qc" flags, even though they are supposed to be present in this tested commit. I am wondering if something recently changed in the way we install SCT for devs? @joshuacwnewton @Drulex ?

You have to add the remote since this is not a branch in the sct repo, but a fork.

```console
$ git remote add claragiroux git@github.com:claragiroux/spinalcordtoolbox.git
$ git fetch claragiroux
$ git checkout --track claragiroux/3274-add-qc-params-in-moco-functions

$  sct_fmri_moco

--
Spinal Cord Toolbox (git-3274-add-qc-params-in-moco-functions-d13fb848e8ddf96a8ae22d40f10a44ef89a46ce3)

sct_fmri_moco 
--

sct_fmri_moco: error: the following arguments are required: -i

usage: sct_fmri_moco -i <file> [-h] [-g <int>] [-m <file>] [-param <list>] [-ofolder <folder>] [-x {nn,linear,spline}] [-r <int>] [-v <int>] [-qc <folder>] [-qc-fps <float>] [-qc-dataset <str>]
                     [-qc-subject <str>]

Motion correction of fMRI data. Some robust features include:
  - group-wise (-g)
  - slice-wise regularized along z using polynomial function (-p)
    (For more info about the method, type: isct_antsSliceRegularizedRegistration)
  - masking (-m)
  - iterative averaging of target volume

The outputs of the motion correction process are:
  - the motion-corrected fMRI volumes
  - the time average of the corrected fMRI volumes
  - a time-series with 1 voxel in the XY plane, for the X and Y motion direction (two separate files), as required for FSL analysis.
  - a TSV file with the slice-wise average of the motion correction for XY (one file), that can be used for Quality Control.

MANDATORY ARGUMENTS:
  -i <file>             Input data (4D). Example: fmri.nii.gz

OPTIONAL ARGUMENTS:
  -h, --help            Show this help message and exit.
  -g <int>              Group nvols successive fMRI volumes for more robustness.
  -m <file>             Binary mask to limit voxels considered by the registration metric.
  -param <list>         Advanced parameters. Assign value with "="; Separate arguments with ",".
                          - poly [int]: Degree of polynomial function used for regularization along Z. For no regularization set to 0. Default=2.
                          - smooth [mm]: Smoothing kernel. Default=0.
                          - iter [int]: Number of iterations. Default=10.
                          - metric {MI, MeanSquares, CC}: Metric used for registration. Default=MeanSquares.
                          - gradStep [float]: Searching step used by registration algorithm. The higher the more deformation allowed. Default=1.
                          - sampling [None or 0-1]: Sampling rate used for registration metric. Default=None.
                          - numTarget [int]: Target volume or group (starting with 0). Default=0.
                          - iterAvg [int]: Iterative averaging: Target volume is a weighted average of the previously-registered volumes. Default=1.
  -ofolder <folder>     Output path. (default: ./)
  -x {nn,linear,spline}
                        Final interpolation. (default: linear)
  -r <int>              Remove temporary files. O = no, 1 = yes (default: 1)
  -v <int>              Verbosity. 0: Display only errors/warnings, 1: Errors/warnings + info messages, 2: Debug mode (default: 1)
  -qc <folder>          The path where the quality control generated content will be saved.
  -qc-fps <float>       This float number is the frame rate of the output gif images. Default value is 2 fps. (default: 2)
  -qc-dataset <str>     If provided, this string will be mentioned in the QC report as the dataset the process was run on.
  -qc-subject <str>     If provided, this string will be mentioned in the QC report as the subject the process was run on.
```

If you don't use ssh for git clone you may need to add the `http` remote instead
```
git remote add claragiroux https://github.com/claragiroux/spinalcordtoolbox.git
```

**Comment by claragiroux** [comment]
For the next PRs is it better if I create a branch directly in the sct repo?

I followed the instructions here that suggest to fork the repo! https://www.neuro.polymtl.ca/tips_and_tricks/git

**Comment by jcohenadad** [comment]
> For the next PRs is it better if I create a branch directly in the sct repo?

yes pls-- much easier for me to review-- thanks!

**Comment by joshuacwnewton** [comment]
> I followed the instructions here that suggest to fork the repo! https://www.neuro.polymtl.ca/tips_and_tricks/git

Thanks for pointing this out! I didn't know it existed... it offers some different advice compared to our other "Contributing" page: https://www.neuro.polymtl.ca/software#contributing, so this is definitely misleading/confusing, and could be better organized.

**Pull request closed without merging**
