### PR TITLE
More pessimistic caching of outputs (see #1625)

### PR DESCRIPTION
**Pull request by zougloub**
Noted in #1625 that the caching was very optimistic, and this PR brings:

- A set of helpers to perform better® output caching
- Usage of the helpers in the code that does caching

Using the caching helpers looks like:
```python
cache_sig = sct.cache_signature(...)
cachefile = os.path.join(curdir, "name_of_the.cache")
if sct.cache_valid(cachefile, cache_sig) and other_test_that_outputs_exist():
    reuse_cached_outputs()
else:
    create_outputs()
    sct.cache_save(cachefile, cache_sig)
```

Notes:

- The caching is performed by hashing any content that could influence on the output (except SCT code and its dependencies...  that would be possible, but probably overkill)
- `sct_convert` doesn't produce reproducible outputs, so (until it's fixed?) avoid to use caching based on its outputs

### CODE REVIEW

**Comment by zougloub** [comment]
@benjamindeleener @jcohenadad even if this is not finished, if you can take a look at the code and provide preliminary comments, just to make sure that you agree on the approach.

**Comment by jcohenadad** [comment]
@zougloub i definitely like this approach. So, in the case of `sct_straightening_spinalcord`'s output (ie: warping field), which depends on (i) the centerline (mandatory), (ii) disc_label (optional) and (iii) the reference image (optional), we would have something like:
```python
cache_sig = cache_signature(input_data=[data_seg.nii.gz, disc_labels.nii.gz]):
```

What did you have in mind for the field `input_params={}`? In the example above, we could use strings like "classical" and "disc-based", although that sounds like a bad idea (if string changes, broken compatibility, etc.). Maybe caching the data only would work...

**Comment by zougloub** [comment]
Maybe this is a bad example for `input_params` because I didn't try to understand.. but I saw `-x spline` in an `sct_straighten_spinalcord` invocation, and stored this option in `input_params`. But even without a concrete usage example I'd have added the argument...

**Comment by zougloub** [comment]
OK, here we go.

- I am not 100% sure about what I did in `sct_make_ground_truth` (the call to `sct.run(['sct_concat_transfo', '-w', 'warp_straight2curve.nii.gz', '-d', ftmp_data, '-o', 'warp_straight2curve.nii.gz'])` is confusing me a little).
- For now there's no check on the outputs signature. This could be a problem today, if someone was to call `sct_straighten_spinalcord` directly, but so far I don't think it's likely. Going ahead and also storing outputs paths and signatures, so as to not reuse those if they changed, would take a bit more work.

**Pull request merged**
