### PR TITLE
Print actual numbers of jobs run in parallel.

### LINKED ISSUE #2956: Displayed number of jobs run in parallel is confusing
When running X subjects in parallel, the script shows the number of maximum jobs, not the actual number of subjects, which is confusing.

In the example below, the max number of jobs is 15 (16-1), but the actual number of jobs run in parallel is 7 (contrarily to what is indicated):

<details><summary>Full output</summary>

```bash
--
Spinal Cord Toolbox (git-master-f497c2f4cf512d184e07761f712631016d3e0454)

configuring
INFO SYSTEM
-----------
OS: osx (Darwin-19.6.0-x86_64-i386-64bit)
CPU cores: Available: 16 | Threads used by ITK Programs: 1
RAM: Total 16384 MB | Available 6504 MB | Used 8660 MB

INPUT ARGUMENTS
---------------
batch_log: sct_run_batch_log.txt
config: config_julien_run_batch.yml
continue_on_error: 1
email_from: null
email_host: smtp.gmail.com:587
email_to: null
exclude: null
exclude_list: null
include: null
include_list:
- sub-nwu05
- sub-pavia04
- sub-perform05
- sub-stanford05
- sub-tokyo750w01
- sub-unf07
- sub-unf04
itk_threads: 1
jobs: -1
path_data: /Users/julien/code/spine-generic/data-multi-subject
path_output: csa_atrophy_results
path_segmanual: .
script: /Users/julien/code/csa-atrophy/process_data.sh
script_args: /Users/julien/code/csa-atrophy/config_script_t1.yml
subject_prefix: sub-
zip: true

SCRIPT
------
git commit: 744ca79f1320ecf90d0aa8c8ac12f7ff40fe7770
git origin: https://github.com/sct-pipeline/csa-atrophy.git
Copying script to output folder...
/Users/julien/code/csa-atrophy/process_data.sh -> /Users/julien/code/csa-atrophy/csa_atrophy_results

DATA
----
git commit: 47a3bdcddeef8da0e5f19d15e9b1464bccf67b12
git origin: https://github.com/spine-generic/data-multi-subject.git

RUNNING
-------
Running 15 jobs in parallel.

Started at 14h15m51s: sub-stanford05. See log file /Users/julien/code/csa-atrophy/csa_atrophy_results/log/process_data_sub-stanford05.log
Started at 14h15m51s: sub-unf07. See log file /Users/julien/code/csa-atrophy/csa_atrophy_results/log/process_data_sub-unf07.log
Started at 14h15m51s: sub-pavia04. See log file /Users/julien/code/csa-atrophy/csa_atrophy_results/log/process_data_sub-pavia04.log
Started at 14h15m51s: sub-tokyo750w01. See log file /Users/julien/code/csa-atrophy/csa_atrophy_results/log/process_data_sub-tokyo750w01.log
Started at 14h15m51s: sub-unf04. See log file /Users/julien/code/csa-atrophy/csa_atrophy_results/log/process_data_sub-unf04.log
Started at 14h15m51s: sub-perform05. See log file /Users/julien/code/csa-atrophy/csa_atrophy_results/log/process_data_sub-perform05.log
Started at 14h15m51s: sub-nwu05. See log file /Users/julien/code/csa-atrophy/csa_atrophy_results/log/process_data_sub-nwu05.log
```

</details>

Suggestion: display the _actual_ number of jobs ran in parallel.

### PR DESCRIPTION
**Pull request by yanchunCoBIUS**
Will print "Processing 7 subjects in parallel. (Worker processes used: 15)", fix #2956

### CODE REVIEW

**Comment by jcohenadad** [comment]
@yanchunCoBIUS could you please add the [appropriate labels](https://www.neuro.polymtl.ca/software/contributing#submitting_a_pull_request), thank you

**Comment by yanchunCoBIUS** [comment]
> @yanchunCoBIUS could you please add the [appropriate labels](https://www.neuro.polymtl.ca/software/contributing#submitting_a_pull_request), thank you

Sorry about that, because I don't have write access to this repo, so I can't create a label.

**Comment by jcohenadad** [comment]
> > @yanchunCoBIUS could you please add the [appropriate labels](https://www.neuro.polymtl.ca/software/contributing#submitting_a_pull_request), thank you
> 
> Sorry about that, because I don't have write access to this repo, so I can't create a label.

ah! my bad 😬   you now have the proper permissions

**Review by jcohenadad — APPROVED** [review]
tested-- it works

**Pull request merged**
