### PR TITLE
README: Added link to Youtube tutorials

### PR DESCRIPTION
**Pull request by jcohenadad**
I suggest we redirect to the Youtube page instead of populating the README with embedded videos (more maintenance)

### CODE REVIEW

**Comment by alexfoias** [comment]
speaking of tutorial, do you want me to upload also [this one](https://v.youku.com/v_show/id_XNDMwMzQ1OTQ1Ng==.html) to youtube?

**Comment by jcohenadad** [comment]
> speaking of tutorial, do you want me to upload also [this one](https://v.youku.com/v_show/id_XNDMwMzQ1OTQ1Ng==.html) to youtube?

i cannot access the link-- can you pls put it somewhere on duke/temp 
thx

**Comment by alexfoias** [comment]
added under `duke/temp/jcohen/sct_installation_win10_home.mp4`

**Comment by jcohenadad** [comment]
> added under `duke/temp/jcohen/sct_installation_win10_home.mp4`

thx! i've uploaded it in the youtube channel

**Pull request merged**
