### PR TITLE
Update model and fixed default output suffix

### LINKED ISSUE #3278: sct_deepseg output data with suffix "-manual" which is confusing (and wrong)
### Description

Running this:
```console
Spinal Cord Toolbox (git-HEAD-79b2046831b02c5fb3ab742978777ba81e00ad49)

sct_deepseg -i dwi_1500_orient_dwi_mean.nii.gz -task seg_mice_gm-wm_dwi
--


WARNING: fname_roi has not been specified, then the entire volume is processed.

Loaded 512 axial slices.
^[[B
Done! To view results, type:
fsleyes dwi_1500_orient_dwi_mean.nii.gz -cm greyscale dwi_1500_orient_dwi_mean_gmseg_manual.nii.gz -cm red -a 70.0 &
```

As can be seen, the output segmentation is called with added suffix `_gmseg_manual`. Why the "manual", given this is an automatic segmentation? @charleygros maybe you have a clue?

### LINKED ISSUE #3279: Better performance of deepseg seg_mice_gm-wm_dwi model if A-P orientation is wrong
### Description

While working on a user's forum issue https://forum.spinalcordmri.org/t/registration-to-t1-ex-vivo-template-error/644/6, I noticed that `sct_deepseg`'s model `seg_mice_gm-wm_dwi` performs better if the image is (wrongly) flipped in the A-P direction. 

See below with the correct orientation, ie: we clearly see the dorsal horns pointing towards "A" whereas it should be "P":

https://user-images.githubusercontent.com/2482071/111055346-f64ecf00-8442-11eb-84af-a0a02f35bd18.mov

However, when fixing the wrong orientation of the image using the following function:
~~~
sct_image -i dwi_1500.nii.gz -setorient-data PSL -o dwi_1500_orient.nii.gz
~~~

Even though the image is now correctly oriented, the segmentation performance is largely decreased:

https://user-images.githubusercontent.com/2482071/111055362-1d0d0580-8443-11eb-892f-74a395698f0b.mov

Which makes me wonder if the model may have been trained on flipped data? (ie: A-P were mislabeled). @charleygros

### PR DESCRIPTION
**Pull request by charleygros**
#### GitHub

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [x] I've applied a [release milestone](https://github.com/neuropoly/spinalcordtoolbox/milestones) (major, minor, patch) in line with [Semantic Versioning guidelines](https://github.com/neuropoly/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release#convention-for-naming-releases) 
- [x] I've assigned a reviewer

#### PR contents

- [x] I've consulted [SCT's internal developer documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki) to ensure my contribution is in line with any relevant design decisions
- [ ] I've added [relevant tests](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Tests) for my contribution
- [x] I've updated the [relevant documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description
In this PR:
- [x] Correct the parser of `sct_deepseg -o` regarding the default output suffix
- [x] Add a new release of the [model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg](https://github.com/ivadomed/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg)
- [ ] ONNX instead of PT version in order to speed up segmentation process (see #3309) 

## Linked issues
Resolves #3278, Resolves #3279

### CODE REVIEW

**Comment by charleygros** [comment]
@jcohenadad & @joshuacwnewton: PR ready for review

Installation of model:
```
chgroc@rosenberg:~/spinalcordtoolbox$ sct_deepseg -install-task seg_exvivo_gm-wm_t2

--
Spinal Cord Toolbox (git-cg/i3278_deepseg_output_name-2d533ffc5d722ff951277df673f06154984826a3)

sct_deepseg -install-task seg_exvivo_gm-wm_t2
--


INSTALLING MODEL: model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg
Trying URL: https://github.com/ivadomed/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg/archive/r20210331.zip
Downloading: model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg-r20210331.zip
Status: 72.9MB [00:06, 12.0MB/s]
Creating temporary folder (/tmp/sct-20210330230855.113934-es10oz8_)
Unzip data to: /tmp/sct-20210330230855.113934-es10oz8_
Removing temporary folders...
```

At the moment I have an error with the ONNX model:
```
chgroc@rosenberg:~/spinalcordtoolbox$ sct_deepseg -i ../duke/projects/ivadomed/gm_t2_exvivo/sub-3902top/anat/sub-3902top_T2w.nii.gz -task seg_exvivo_gm-wm_t2

--
Spinal Cord Toolbox (git-cg/i3278_deepseg_output_name-2d533ffc5d722ff951277df673f06154984826a3)

sct_deepseg -i ../duke/projects/ivadomed/gm_t2_exvivo/sub-3902top/anat/sub-3902top_T2w.nii.gz -task seg_exvivo_gm-wm_t2
--


WARNING: fname_roi has not been specified, then the entire volume is processed.

Loaded 512 axial slices.
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg.py", line 245, in <module>
    main(sys.argv[1:])
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg.py", line 207, in main
    nii_lst, target_lst = imed_inference.segment_volume(path_model, input_filenames, options=options)
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/ivadomed/inference.py", line 264, in segment_volume
    preds = model(img) if fname_model.endswith('.pt') else onnx_inference(fname_model, img)
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/ivadomed/inference.py", line 377, in onnx_inference
    ort_session = onnxruntime.InferenceSession(model_path)
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers or [])
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Type Error: Type 'tensor(bool)' of input parameter (281) of operator (ScatterND) in node (ScatterND_160) is invalid.
```
... which does not happen with the PT version of the model.
@joshuacwnewton : Do you have any idea?
A short term solution would be to use the PT version of the model (even if probably slower, see #3309). @jcohenadad: What do you think?

**Comment by joshuacwnewton** [comment]
> @joshuacwnewton : Do you have any idea?

I've opened an issue for this here https://github.com/ivadomed/ivadomed/issues/749 with the start of an investigation. Is the model definition code hosted anywhere, by chance? (Not sure where I should be looking. :sweat_smile:)

**Comment by charleygros** [comment]
> I've opened an issue for this here [ivadomed/ivadomed#749](https://github.com/ivadomed/ivadomed/issues/749) with the start of an investigation.

Thanks so so much for looking into this @joshuacwnewton !

> Is the model definition code hosted anywhere, by chance? (Not sure where I should be looking. 😅)

Of course, thanks for asking! The full config file used for this model can be found [here](https://github.com/ivadomed/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg/blob/main/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg.json). But essentially, the model architecture is [this one](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/models.py#L462).

**Comment by charleygros** [comment]
With @jcohenadad, we agreed (as a short term solution) to replace the onnx model with the pt model, so that our collaborators can use it while we find a solution for the onnx version.

Everything works on my hand. Ready for review!

**Comment by jcohenadad** [comment]
I'm afraid I have bad news. I tested the latest model on data with the correct orientation, but results are sub-optimal. 

95c93564e4a7286af4513bf40c9341859e1ec68d
Screen Shot 2021-03-31 at 8 57 20 PM

Now, here are results when data are A-P flipped (which is anatomically _incorrect_):
Screen Shot 2021-03-31 at 9 08 42 PM

Here are the results I obtained in the past from master 999674872b1cdb69cc7125ebfad8533057a79dae (note: the data are also incorrectly A-P flipped, which I had to do in order to get better performance):
Screen Shot 2021-03-31 at 8 59 13 PM

As can be seen, the model still performs better when the data are in the incorrect orientation (ie: A-P flipped).

To make it clear what I mean by "A-P" flipped, here is the _incorrect_ orientation:
Screen Shot 2021-03-31 at 9 11 37 PM

And here is the correct orientation (but suboptimal segmentation):
image

**Comment by jcohenadad** [comment]
I'm afraid the "flipped" was maybe R-L flipped?

image

@charleygros could you please clarify how the data was flipped? thank you

**Comment by charleygros** [comment]
> @charleygros could you please clarify how the data was flipped? thank you

Using "sct_image -i IMAGE.nii.gz -setorient-data PSL -o IMAGE_NEW.nii.gz"

**Comment by charleygros** [comment]
[r20210401_v2](https://github.com/ivadomed/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg/releases/tag/r20210401_v2)

**Comment by jcohenadad** [comment]
yay!!! 
Screen Shot 2021-04-01 at 10 06 15 AM

**Review by jcohenadad — APPROVED** [review]
thank you @charleygros !!!

p.s.: I unchecked #3309 as it will be fixed in a subsequent PR

**Pull request merged**
