### PR TITLE
Remove unused dependencies

### LINKED ISSUE #2680: Remove extraneous dependencies
Of the packages listed in `requirements.txt`, `xlrd`, `xlwt`, and `xlutils` are semi-deprecated in favour of `openpyxl` except for compatibility with very old Excel formats.  Of these, only `xlutils` appears in the codebase and only in one place, so at least the other two likely could be removed from the installation.

### PR DESCRIPTION
**Pull request by Drulex**
Cleanup unused dependencies from the project.

This includes: 
- cryptography
- psutil
- xlrd
- xlutils

closes #2680

### CODE REVIEW

**Comment by Drulex** [comment]
```
writer = pd.ExcelWriter(self.excel_name, engine='xlwt')

   File "/repo/python/envs/venv_sct/lib/python3.6/site-packages/pandas/io/excel/_xlwt.py", line 13, in __init__

   import xlwt

   ModuleNotFoundError: No module named 'xlwt'
``` 
^ looks like I was wrong about pandas bundling the excel engine.

Will investigate and possibly create another issue to migrate to `openpyxl`.

**Comment by Drulex** [comment]
@jcohenadad Completely unrelated, but the build for this has completed more than an hour ago and github still shows "waiting for status to be reported".

Just wondering if it's normal? I am assuming that no action is required from me.

image
image

**Comment by jcohenadad** [comment]
> Just wondering if it's normal? I am assuming that no action is required from me.

i've seen that in the past-- i think it's a bug. To overcome this problem i re-launched the job on travis (AFAIR) or i pushed another commit to trigger the hook

**Comment by Drulex** [comment]
> > Just wondering if it's normal? I am assuming that no action is required from me.
> 
> i've seen that in the past-- i think it's a bug. To overcome this problem i re-launched the job on travis (AFAIR) or i pushed another commit to trigger the hook

Yes that did the trick.

**Comment by Drulex** [comment]
@jcohenadad I'm stuck in some kind of buggy loop:
1. CI has some kind of issue and does not update status to Github even though build is successful 
2. I re-trigger CI build via dummy commit, build is successful and status is reported correctly to Github
3. By this time the branch is out of date and I need to update/rebase.
4. The rebase causes CI to run again, build is successful, but again status is not updated correctly on Github -> back to step 1.

@zougloub have you ever seen this? Looks like the symptom is not unheard of (https://github.com/travis-ci/travis-ci/issues/10204), however I don't think the root cause is the same since in my case sometimes the status is updated successfully, sometimes it isn't.

**Comment by jcohenadad** [comment]
@Drulex i've looked around for 20min (i need to stop looking due to other emergencies)-- there are a few weird things:
- the solution proposed [here](https://travis-ci.community/t/travis-ci-branch-expected-waiting-for-status-to-be-reported/829/2) is not doable, because in our repository branch settings, these are not options: 
Screen Shot 2020-06-08 at 10 13 12 AM. 
And i don't know how to get these options activated.
- Another weird thing: when going in the travis neuropoly dashboard, i don't see the spinalcordtoolbox repos listed:
Screen Shot 2020-06-08 at 10 24 42 AM, even though the repository *does* exist [here](https://travis-ci.com/github/neuropoly/spinalcordtoolbox). Maybe this is due to the existence of a "travis" and a "travis pro". I *think* spinalcordtoolbox is under the "old" travis, which does not use the new API shown in the link above (the "solution"). I tried to add spinalcordtoolbox to the "travis pro", but without success.

**Comment by jcohenadad** [comment]
another interesting thing:
Screen Shot 2020-06-08 at 10 33 43 AM

maybe this is due to my attempt to add travis-pro to this repos...

**Comment by jcohenadad** [comment]
ah! maybe this is where the old/new travis are differenciated:
- old: https://travis-ci.org/github/neuropoly/spinalcordtoolbox
- new: https://travis-ci.com/github/neuropoly/spinalcordtoolbox

so i guess a hopeful solution is to try to get spinalcordtoolbox repos to use the new URL

**Comment by jcohenadad** [comment]
hum, and for info, Travis GH Apps is supposed to be installed on the NeuroPoly organization (notice the link to travis.com, not travis.org, in this snapshot):
Screen Shot 2020-06-08 at 10 45 05 AM

**Comment by Drulex** [comment]
Ok looks like it can be merged @jcohenadad

**Pull request merged**
