### PR TITLE
New straightening method

### PR DESCRIPTION
**Pull request by benjamindeleener**
This pull request introduces a new method for straightening the spinal cord. This method is much simpler, faster and gives an analytic solution for straightening an image, based on a centerline. The following steps are applied:

Steps: (everything is done in physical space)

1. open input image and centerline image
2. extract centerline based on nurbs, along with its derivatives. The number of points given by the fitting method is important for next steps. More points improve accuracy.
3. compute length of centerline, in order to adjust image size in inferior-superior direction.
4. compute and generate straight space, by calculating regularly spaced points along straight centerline.
5. compute transformations
   * for each voxel of one space: (done using matrices --> improves speed by a factor x300)
      * (a) determine which plane of spinal cord centreline it is included
      * (b) compute the position of the voxel in the plane (X and Y distance from centreline, along the plane)
      * (c) find the correspondent centreline point in the other space
      * (d) find the correspondence of the voxel in the corresponding plane
6. generate warping fields for each transformations
7. write warping fields and apply them

step 5.b: how to find the corresponding plane?
    The centerline plane corresponding to a voxel correspond to the nearest point of the centerline.
    However, we need to compute the distance between the voxel position and the plane to be sure it is part of the plane and not too distant. If it is more far than a threshold, warping value should be 0. This threshold has been set to 1.0 mm.

step 5.d: how to find the correspondence between centerline point in both images?
    Both centerline have the same length. Therefore, we can map centerline point via their position along the curve.
    If we use the same number of points regularly spaced along the spinal cord (1000 for example), the correspondence is straight-forward.

Results are very good: 
```
Results for "sct_straighten_spinalcord -i t1/t1.nii.gz -s t1/t1_manual_segmentation.nii.gz":
Dataset: /Users/benjamindeleener/data/data_testing/C2-T2/
     subject      dice  dist_max    duration       mse      status
0   errsm_02  0.973405  1.090000  193.614509  0.700000    0.000000
1   errsm_03  0.965981  1.220000  218.204951  0.670000    0.000000
2   errsm_05  0.966570  0.990000  178.866769  0.440000    0.000000
3   errsm_09  0.960326  1.050000  215.570705  0.500000    0.000000
4   errsm_10  0.972896  1.100000  229.149219  0.490000    0.000000
5   errsm_11  0.963362  1.400000  196.756958  0.690000    0.000000
6   errsm_12  0.946886  0.890000  214.832916  0.450000   99.000000
7   errsm_13  0.868424  1.070000  257.340381  0.480000   99.000000
8   errsm_14  0.941916  0.850000  114.052438  0.500000   99.000000
9   errsm_16  0.968347  1.150000  117.916007  0.660000    0.000000
10  errsm_17  0.972887  0.990000  109.058220  0.430000    0.000000
11  errsm_18  0.961078  1.410000  119.175172  0.660000    0.000000
12  errsm_21  0.973868  1.230000   98.834768  0.580000    0.000000
13  errsm_22  0.969226  0.830000  105.533081  0.450000    0.000000
14  errsm_23  0.967887  1.330000   99.549621  0.610000    0.000000
15  errsm_24  0.977020  1.140000   84.754519  0.610000    0.000000
16  errsm_25  0.965738  1.110000   83.367704  0.640000    0.000000
17  errsm_26       NaN       NaN         NaN       NaN  200.000000
18  errsm_30  0.959853  1.180000   76.255920  0.670000    0.000000
19  errsm_31  0.970062  1.520000   89.112414  0.790000    0.000000
20  errsm_32  0.961563  1.340000   76.787529  0.640000    0.000000
21  errsm_33  0.969310  1.210000   74.162983  0.670000    0.000000
22  errsm_34  0.969900  1.230000   83.353025  0.710000    0.000000
23  errsm_35  0.971818  0.980000   69.508597  0.460000    0.000000
24      Mean  0.961666  1.143913  135.032974  0.586957   12.913043
25       STD  0.021935  0.181051   61.301608  0.107384   34.090672
Passed: 20/24
Total duration: 469s
```

```
Results for "sct_straighten_spinalcord -i t2/t2.nii.gz -s t2/t2_manual_segmentation.nii.gz":
Dataset: /Users/benjamindeleener/data/data_testing/C2-T2/
     subject      dice  dist_max    duration       mse     status
0   errsm_02  0.969606  1.220000   32.415626  0.670000   0.000000
1   errsm_03  0.968913  1.690000   69.337504  0.640000   0.000000
2   errsm_05  0.963547  1.260000   61.467433  0.650000   0.000000
3   errsm_09  0.970393  0.820000   73.691494  0.490000   0.000000
4   errsm_10  0.846641  1.090000   90.811963  0.690000  99.000000
5   errsm_11  0.965432  0.990000   68.705855  0.540000   0.000000
6   errsm_12  0.954305  1.380000   73.610079  0.660000   0.000000
7   errsm_13  0.975272  1.100000   89.123860  0.550000   0.000000
8   errsm_14  0.955297  0.880000   78.711567  0.540000   0.000000
9   errsm_16  0.972501  1.200000   95.320153  0.700000   0.000000
10  errsm_17  0.973150  1.230000   93.131958  0.700000   0.000000
11  errsm_18  0.968875  1.240000  101.377686  0.580000   0.000000
12  errsm_21  0.970477  1.160000   80.495066  0.660000   0.000000
13  errsm_22  0.968603  1.210000   93.013072  0.720000   0.000000
14  errsm_23  0.967668  1.360000   97.809592  0.820000   0.000000
15  errsm_24  0.985440  1.000000   92.375242  0.380000   0.000000
16  errsm_25  0.969732  0.980000   96.514691  0.420000   0.000000
17  errsm_26  0.964211  1.340000   78.545863  0.720000   0.000000
18  errsm_30  0.957870  1.150000   84.443004  0.700000   0.000000
19  errsm_31  0.970731  1.040000   97.578216  0.550000   0.000000
20  errsm_32  0.936143  1.400000   81.386216  0.820000  99.000000
21  errsm_33  0.977215  1.180000   83.215493  0.530000   0.000000
22  errsm_34  0.975067  0.790000   85.107665  0.460000   0.000000
23  errsm_35  0.973460  1.190000   71.047439  0.700000   0.000000
24      Mean  0.962523  1.162500   82.051531  0.620417   8.250000
25       STD  0.026466  0.201111   15.117729  0.116076  27.950655
Passed: 22/24
Total duration: 318s
```

```
Results for "sct_straighten_spinalcord -i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz":
Dataset: /Volumes/data_shared/sct_testing/small/
             subject      dice  dist_max    duration       mse     status
0         100_004_s1  0.975245  1.860000  135.105536  0.400000   0.000000
1         200_005_s2  0.970421  0.940000  196.340442  0.500000   0.000000
2    20150910_joshua  0.978242  0.620000  154.643364  0.300000   0.000000
3      20151025_emil  0.952441  0.610000  106.653552  0.240000   0.000000
4       20151025_max  0.969139  5.620000  143.014648  0.690000  99.000000 --> very good despite low large dist_max
5             e25428  0.968089  0.870000  124.731977  0.480000   0.000000
6           errsm_40  0.971983  0.960000  200.718570  0.470000   0.000000
7           errsm_42  0.975571  6.630000  196.347865  0.800000  99.000000
8            sct_002  0.978473  0.860000  111.729113  0.440000   0.000000
9   sct_example_data  0.969728  0.950000   65.244023  0.480000   0.000000
10     vanderbilt_05  0.970836  0.930000   64.621994  0.460000   0.000000
11              Mean  0.970924  1.895455  136.286462  0.478182  18.000000
12               STD  0.007117  2.128527   48.524727  0.156641  40.047472
Passed: 9/11
Total duration: 250s
```

### CODE REVIEW

**Comment by jcohenadad** [comment]
nice! minor comments:
- Time to generate volumes and indexes --> Time to generate volumes and indices
- Time to get in-plan --> Time to get in-plane

**Comment by jcohenadad** [comment]
strange effect on the edge (90° rotation):
on errsm_42:
output_sid3kr

**Comment by benjamindeleener** [comment]
The error on errsm_42 is due to wrong segmentation on upper slice of input image:
errsm_42_last_point
errsm_42_fitting
NURBS fitting is robust towards outliers inside centerline but not at the edges. However, straightening should be more robust to such wrong segmentations, as it happens often.

One solution would be to detect peripheral outliers and remove them.

**Comment by benjamindeleener** [comment]
I implemented two verifications on spinal cord segmentation before straightening in order to remove the issue above:
1. We compute the number of objects on each slice. If this number of objects is higher than 1, we remove the corresponding centerline point.
2. After calculating all distances between adjacent points of centerline, we check if the distance from one point to another is higher than 3 * std(all distances).

The code for the verifications above is the following:
```
distances = []

# get center of mass of the centerline/segmentation and remove outliers
sct.printv('.. Get center of mass of the centerline/segmentation...', verbose)
for iz in range(0, nz_nonz, 1):
    slice = array(data[:, :, z_centerline[iz]])
    labeled_array, num_f = ndimage.measurements.label(slice)
    num_features[iz] = num_f
    x_centerline[iz], y_centerline[iz] = ndimage.measurements.center_of_mass(slice)
    if iz != 0:
        distances.append(sqrt((x_centerline[iz]-x_centerline[iz-1]) ** 2 + (y_centerline[iz]-y_centerline[iz-1]) ** 2))

mean_distances = mean(distances)
std_distances = std(distances)
indices_to_remove = []

# ascending verification
for iz in range(0, nz_nonz/2, 1):
    distance = sqrt((x_centerline[iz]-x_centerline[iz+1]) ** 2 + (y_centerline[iz]-y_centerline[iz+1]) ** 2)
    if num_features[iz] > 1 or abs(distance - mean_distances) > 3 * std_distances:
        indices_to_remove.append(iz)

# descending verification
for iz in range(nz_nonz-1, nz_nonz/2, -1):
    distance = sqrt((x_centerline[iz]-x_centerline[iz-1]) ** 2 + (y_centerline[iz]-y_centerline[iz-1]) ** 2)
    if num_features[iz] > 1 or abs(distance - mean_distances) > 3 * std_distances:
        indices_to_remove.append(iz)

x_centerline = delete(x_centerline, indices_to_remove)
y_centerline = delete(y_centerline, indices_to_remove)
z_centerline = delete(z_centerline, indices_to_remove)
```

Results on small testing dataset have been improved:
```
Results for "sct_straighten_spinalcord -i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz":
Dataset: /Users/benjamindeleener/data/sct_testing/small/
             subject      dice  dist_max    duration       mse  status
0         100_004_s1  0.975767  0.660000  200.410273  0.380000       0
1         200_005_s2  0.970421  0.940000  316.892493  0.500000       0
2    20150910_joshua  0.983363  0.590000  255.342765  0.300000       0
3      20151025_emil  0.952441  0.610000  154.851944  0.240000       0
4       20151025_max  0.973979  0.770000  217.690380  0.400000       0
5             e25428  0.966957  0.990000  189.712123  0.490000       0
6           errsm_40  0.970733  0.960000  320.217446  0.470000       0
7           errsm_42  0.975735  0.920000  316.320731  0.490000       0
8            sct_002  0.978473  0.860000  168.859581  0.440000       0
9   sct_example_data  0.969728  0.950000  102.474512  0.480000       0
10     vanderbilt_05  0.970836  0.930000  100.517369  0.460000       0
11              Mean  0.971676  0.834545  213.026329  0.422727       0
12               STD  0.007877  0.150424   81.041922  0.085451       0
Passed: 11/11
Total duration: 358s
```

**Note: we still need to determine if this algorithm works for a low number of slices!**

**Comment by jcohenadad** [comment]
works better indeed. I'm currently trying on other datasets, but i the meantime i spotted these typos:
- The fitting of the curve was done using  14  points of controle --> 14 control points
- Time to compute distance between voxels and nearest plans --> planes
- Time to get projected voxels on plans --> planes

**Comment by jcohenadad** [comment]
data: **testing_small/20151025_emil**
command:
~~~
sct_straighten_spinalcord -i t2.nii.gz -s t2_seg_manual.nii.gz
~~~

screen shot 2016-03-27 at 10 19 22

**Comment by benjamindeleener** [comment]
**testing_small/20151025_emil** works perfectly when using some parameters (precision and threshold_distance). We need to discuss what are the parameters that work for every images.
```
sct_straighten_spinalcord -i t2.nii.gz -s t2_seg_manual.nii.gz -param precision=5.0,threshold_distance=2.5
```

**Comment by jcohenadad** [comment]
data: testing_small/20151025_emil
command:
~~~
sct_label_vertebrae -i t2.nii.gz -seg t2_seg.nii.gz -initcenter 2
~~~

Results: switching between old/new straightening method. The new methods gives very narrow levels, maybe due to problem in warping field. I'll further investigate comparison with
output_ibbilf
 register to template.

**Comment by jcohenadad** [comment]
~~~
isct_test_function -f sct_register_to_template -d data/sct_testing_small/ -p \"-i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -l t2/labels.nii.gz\"
SpinalCord Toolbox version 2.2_dev
SCT installed in /Users/julien/code/spinalcordtoolbox
PYTHON /Users/julien/code/spinalcordtoolbox/python/bin/python /Users/julien/code/spinalcordtoolbox/python /Users/julien/code/spinalcordtoolbox
running /Users/julien/code/spinalcordtoolbox/scripts/isct_test_function.py -f sct_register_to_template -d data/sct_testing_small/ -p "-i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -l t2/labels.nii.gz"
Check folder existence...
Testing... (started on: 2016-03-27 11:33:55)

Results for "sct_register_to_template -i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -l t2/labels.nii.gz":
Dataset: data/sct_testing_small/
             subject  dice_anat2template  dice_template2anat  duration [s]  status
0         100_004_s1            0.946786            0.954207    880.228752       0
1         200_005_s2            0.944293            0.924217   1097.608569       0
2    20150910_joshua            0.955052            0.939657    696.181612       0
3      20151025_emil            0.970640            0.953655    357.304417       0
4       20151025_max            0.946672            0.947191    910.963149       0
5             e25428            0.944328            0.940625    920.769712       0
6           errsm_40            0.947090            0.935271   1129.116606       0
7           errsm_42            0.938342            0.941063   1032.778892       0
8            sct_002            0.938764            0.933852    846.864773       0
9   sct_example_data            0.940189            0.918588    687.859476       0
10     vanderbilt_05            0.945467            0.919363    427.406627       0
11              Mean            0.947057            0.937063    817.007508       0
12               STD            0.009109            0.012411    253.294861       0
Passed: 11/11
Total duration: 1399s
~~~

A couple of minor issues below that could be addressed later (edge problems):

20151025_max:
screen shot 2016-03-27 at 12 08 15

vanderbilt_05
screen shot 2016-03-27 at 12 07 29

20151025_emil
screen shot 2016-03-27 at 12 05 48

**Comment by jcohenadad** [comment]
second test with sct_label_vertebrae, on **20151025_max**. Similar problem as with errsm_42. There is something weird going on that needs to be investigated:
screen shot 2016-03-27 at 12 30 49

**Comment by jcohenadad** [comment]
actually, after thinking it through, we have several users who rely on the entire warped template to extract metrics. For these users, edge mis-registration will be a problem. Would that be easy to address that problem? e.g., by extrapolating centerline, or by modifying the warping field generation (e.g. regularizing warping field at the border)? Just throwing a couple of ideas...

**Comment by benjamindeleener** [comment]
I agree that this need to be addressed. However, I am not sure it comes from straightening. Could it come from sct_register_to_template, e.g. from slice-wise registration?

**Comment by jcohenadad** [comment]
something strange to look at: inconsistent scaling between curved and straight. The centerline is "stretched" on the straightened spinal cord. I think that's the source of the problems with register_to_template and label_vertebrae

100_004_s1:
output_8uvenl

**Comment by jcohenadad** [comment]
results from isct_test_function:

~~~~
# ====================================================================================
# 2016-04-05
# commit: f23039051c224fda7ddab9a8946a0b6867b57b7c (master)
isct_test_function -f sct_label_vertebrae -d /Volumes/data_raid/data_shared/sct_testing/small/ -p \"-i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -o t2_seg_labeled.nii.gz -r 0\"
# ====================================================================================
Results for "sct_label_vertebrae -i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -o t2_seg_labeled.nii.gz -r 0":
Dataset: /Volumes/data_raid/data_shared/sct_testing/small/
             subject diff_man  duration [s]  max_dist       rmse     status
0         100_004_s1       -1    290.346444  4.567872    1.23143   0.000000
1         200_005_s2       -1    425.550008   15.9904    6.18672  99.000000
2    20150910_joshua       -3    175.163654  26.76464   9.364649  99.000000
3      20151025_emil      NaN    292.159813       NaN        NaN   1.000000
4       20151025_max        0    295.739149  3.693615   1.085138   0.000000
5             e25428       -2    288.165102  15.93342   3.601498  99.000000
6           errsm_40       -1    437.374265  4.288138   1.314949   0.000000
7           errsm_42        0    422.254483  4.242641  0.8944272   0.000000
8            sct_002        0    262.421689  6.324555   1.206045  99.000000
9   sct_example_data       -2    161.588729  1.414214  0.4303315   0.000000
10     vanderbilt_05        0    135.239363  1.953125  0.6089937   0.000000
11              Mean      NaN    289.636609       NaN        NaN  36.090909
12               STD      NaN    105.835780       NaN        NaN  49.876757
Passed: 6/11



# ====================================================================================
# 2016-04-05
# commit: e7480de303c23fe5fc6ad354b95f3b79c7008ed7 (template)
isct_test_function -f sct_label_vertebrae -d /Volumes/data_raid/data_shared/sct_testing/small/ -p \"-i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -o t2_seg_labeled.nii.gz -r 0\"
# ====================================================================================
Results for "sct_label_vertebrae -i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -o t2_seg_labeled.nii.gz -r 0":
Dataset: /Volumes/data_raid/data_shared/sct_testing/small/
             subject diff_man  duration [s]  max_dist       rmse      status
0         100_004_s1       -4    112.210896   50.2389   15.53363   99.000000
1         200_005_s2       -8    183.161650  98.26289   28.84221   99.000000
2    20150910_joshua       -7    139.821677  30.97714   10.95805   99.000000
3      20151025_emil      NaN           NaN       NaN        NaN  200.000000
4       20151025_max       -5    121.707820  62.69607   18.19532   99.000000
5             e25428      NaN     93.871988       NaN        NaN    1.000000
6           errsm_40       -6    187.624413  56.13499   15.34391   99.000000
7           errsm_42      -10    183.579985   92.0326   27.42626   99.000000
8            sct_002        0    168.720065   5.09902   1.370689   99.000000
9   sct_example_data       -2     80.016471  3.162278  0.7698004    0.000000
10     vanderbilt_05       -2     78.225617  17.08422   5.259439   99.000000
11              Mean      NaN    134.894058       NaN        NaN   79.300000
12               STD      NaN     43.771027       NaN        NaN   41.531915
Passed: 1/11
~~~

**Comment by benjamindeleener** [comment]
Concerning the scaling issue: it is now fixed. The problem was that I forgot to take into account the fact that a centerline do not necessary cover the entire image.
Results on 100_004_s1:
output_j9mtqa

**Comment by jcohenadad** [comment]
ok it solved the problem!

also: the new straightening is about 2x faster!

~~~
# ====================================================================================
# 2016-04-06
# commit: 92a3463da36e12adeb9124714ce14eea8b30d745 (template)
isct_test_function -f sct_label_vertebrae -d /Volumes/data_raid/data_shared/sct_testing/small/ -p \"-i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -o t2_seg_labeled.nii.gz -r 0\"
# ====================================================================================
Results for "sct_label_vertebrae -i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -o t2_seg_labeled.nii.gz -r 0":
Dataset: /Volumes/data_raid/data_shared/sct_testing/small/
             subject  diff_man  duration [s]   max_dist       rmse     status
0         100_004_s1  0.000000    102.425962   4.567872   1.231430   0.000000
1         200_005_s2 -1.000000    164.781279  22.692954   8.276480  99.000000
2    20150910_joshua -9.000000    133.988811  30.315373  10.848415  99.000000
3      20151025_emil  0.000000     92.751645   3.129628   1.283253   0.000000
4       20151025_max  0.000000    112.620148  10.015721   3.602052  99.000000
5             e25428 -1.000000    103.038598  15.933416   3.622617  99.000000
6           errsm_40 -2.000000    170.714082  11.631107   2.635749  99.000000
7           errsm_42 -1.000000    164.098500   4.242641   0.930949   0.000000
8            sct_002  0.000000    114.596096   6.324555   1.206045  99.000000
9   sct_example_data -2.000000     72.088179   2.000000   0.638285   0.000000
10     vanderbilt_05 -1.000000     72.206906   4.367320   1.526828   0.000000
11              Mean -1.545455    118.482746  10.474599   3.254737  54.000000
12               STD  2.583162     35.629649   9.101138   3.330617  51.701064
Passed: 5/11
Total duration: 212s



# ====================================================================================
# 2016-04-06
# commit: f23039051c224fda7ddab9a8946a0b6867b57b7c (master)
isct_test_function -f sct_label_vertebrae -d /Volumes/data_raid/data_shared/sct_testing/small/ -p \"-i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -o t2_seg_labeled.nii.gz -r 0\"
# ====================================================================================
Results for "sct_label_vertebrae -i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -o t2_seg_labeled.nii.gz -r 0":
Dataset: /Volumes/data_raid/data_shared/sct_testing/small/
             subject diff_man  duration [s]  max_dist       rmse     status
0         100_004_s1       -1    276.342785  4.567872    1.23143   0.000000
1         200_005_s2       -1    437.236357   15.9904    6.18672  99.000000
2    20150910_joshua       -3    174.660170  26.76464   9.364649  99.000000
3      20151025_emil      NaN    288.782994       NaN        NaN   1.000000
4       20151025_max        0    302.708547  3.693615   1.085138   0.000000
5             e25428       -2    276.427662  15.93342   3.601498  99.000000
6           errsm_40       -1    451.709669  4.288138   1.314949   0.000000
7           errsm_42        0    416.685397  4.242641  0.8944272   0.000000
8            sct_002        0    289.191611  6.324555   1.206045  99.000000
9   sct_example_data       -2    165.944674  1.414214  0.4303315   0.000000
10     vanderbilt_05        0    162.773149  1.953125  0.6089937   0.000000
11              Mean      NaN    294.769365       NaN        NaN  36.090909
12               STD      NaN    104.422975       NaN        NaN  49.876757
Passed: 6/11
Total duration: 468s
~~~

**Comment by jcohenadad** [comment]
Results register_to_template:  Excellent!

~~~
# ====================================================================================
# 2016-04-06
# commit: 35811ea9e1425ea87dfc4a72483c62c326d11475 (template)
isct_test_function -f sct_register_to_template -d /Volumes/data_raid/data_shared/sct_testing/small/ -p \"-i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -l t2/labels.nii.gz\"
# ====================================================================================
Results for "sct_register_to_template -i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -l t2/labels.nii.gz":
Dataset: /Volumes/data_raid/data_shared/sct_testing/small/
             subject  dice_anat2template  dice_template2anat  duration [s]  status
0         100_004_s1            0.946599            0.947879    807.506414       0
1         200_005_s2            0.945281            0.884079    999.203522       0
2    20150910_joshua            0.954958            0.933617    642.971263       0
3      20151025_emil            0.968655            0.967295    335.285431       0
4             e25428            0.947867            0.901973    827.619655       0
5           errsm_40            0.945064            0.907059   1022.855701       0
6           errsm_42            0.940303            0.938934    952.316934       0
7            sct_002            0.938967            0.929556    931.589852       0
8   sct_example_data            0.938119            0.949383    745.997222       0
9      vanderbilt_05            0.944498            0.905785    488.419558       0
10              Mean            0.947031            0.926556    775.376555       0
11               STD            0.009033            0.025965    227.360561       0
Passed: 10/10
Total duration: 1145s



# ====================================================================================
# 2016-04-06
# commit: a65216feb282e4c0f59d60309ee3141eadeddab3 (master)
isct_test_function -f sct_register_to_template -d /Volumes/data_raid/data_shared/sct_testing/small/ -p \"-i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -l t2/labels.nii.gz\"
# ====================================================================================
Results for "sct_register_to_template -i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -l t2/labels.nii.gz":
Dataset: /Volumes/data_raid/data_shared/sct_testing/small/
             subject  dice_anat2template  dice_template2anat  duration [s]  status
0         100_004_s1            0.944605            0.944439    936.202116       0
1         200_005_s2            0.944939            0.930568   1147.287234       0
2    20150910_joshua            0.950648            0.931717    763.433315       0
3      20151025_emil            0.961604            0.954297    385.119473       0
4             e25428            0.941517            0.942521    979.320271       0
5           errsm_40            0.944058            0.933560   1147.652818       0
6           errsm_42            0.932349            0.943303   1076.148096       0
7            sct_002            0.938707            0.936426   1049.970616       0
8   sct_example_data                 NaN                 NaN           NaN     200
9      vanderbilt_05            0.938455            0.942829    661.659702       0
10              Mean            0.944098            0.939962    905.199293       0
11               STD            0.008336            0.007593    255.910080       0
Passed: 9/10
Total duration: 1154s
~~~

**Comment by jcohenadad** [comment]
weird stretching on the top/bottom part of the registered template (100_004_s1):
output_cg3nqi

**Comment by jcohenadad** [comment]
Results straighten_spinalcord:  Bof...

~~~
# ====================================================================================
# 2016-04-06
# commit: 35811ea9e1425ea87dfc4a72483c62c326d11475 (template)
isct_test_function -f sct_straighten_spinalcord -d /Volumes/data_raid/data_shared/sct_testing/small/ -p \"-i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz\"
# ====================================================================================
Results for "sct_straighten_spinalcord -i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz":
Dataset: /Volumes/data_raid/data_shared/sct_testing/small/
             subject      dice  dist_max    duration       mse    status
0         100_004_s1  0.973162  0.970000   72.977128  0.560000   0.00000
1         200_005_s2  0.946854  2.240000  127.225294  0.830000  99.00000
2    20150910_joshua  0.902209  0.910000   94.752192  0.450000  99.00000
3      20151025_emil  0.992132  0.360000   61.651228  0.200000   0.00000
4             e25428  0.959228  1.900000   73.765478  0.840000   0.00000
5           errsm_40  0.944328  1.880000  131.454067  0.790000  99.00000
6           errsm_42  0.937964  2.430000  123.858537  0.910000  99.00000
7            sct_002  0.961090  1.160000  106.897093  0.660000   0.00000
8   sct_example_data  0.937221  1.310000   53.617393  0.790000  99.00000
9      vanderbilt_05  0.772083  1.330000   49.033581  0.840000  99.00000
10              Mean  0.932627  1.449000   89.523199  0.687000  59.40000
11               STD  0.061274  0.649794   31.473652  0.223211  51.12338
Passed: 4/10
Total duration: 144s



# ====================================================================================
# 2016-04-06
# commit: 3eeeccf718d75755dae2a6ecff8a564d6dc32cf7 (master)
isct_test_function -f sct_straighten_spinalcord -d /Volumes/data_raid/data_shared/sct_testing/small/ -p \"-i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz\"
# ====================================================================================
Results for "sct_straighten_spinalcord -i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz":
Dataset: /Volumes/data_raid/data_shared/sct_testing/small/
             subject      dice  dist_max    duration       mse  status
0         100_004_s1  0.962809  1.260000  272.919649  0.720000       0
1         200_005_s2  0.969797  1.530000  399.616862  0.760000       0
2    20150910_joshua  0.982451  0.830000  166.194156  0.480000       0
3      20151025_emil  0.971896  0.350000  311.023729  0.230000       0
4             e25428  0.971585  2.730000  208.597446  0.680000       0
5           errsm_40  0.966323  1.790000  399.060236  0.780000       0
6           errsm_42  0.975020  1.770000  399.474766  0.760000       0
7            sct_002  0.960591  1.260000  388.750937  0.740000       0
8   sct_example_data  0.971225  1.460000  208.362182  0.770000       0
9      vanderbilt_05  0.965716  1.360000  171.206748  0.730000       0
10              Mean  0.969741  1.434000  292.520671  0.665000       0
11               STD  0.006319  0.626723   99.469422  0.176021       0
Passed: 10/10
Total duration: 408s
~~~

**Comment by jcohenadad** [comment]
200_005_s2 (old is the small FOV):
output_cckmmt

**Pull request merged**
