### PR TITLE
Handle 'label_discs' case where SC segmentation has holes/discontinuities

### LINKED ISSUE #3252: ValueError: Array has no mass thrown if segmentation has "holes"
### Description

When running `sct_label_vertebrae` using a segmentation that has discontinuities (ie: empty slices), the function crashes:

<details><summary>Syntax & Error</summary>

```console
julien-macbook:~/Desktop/20210225_Unable_to_warp_to_SC_template $ sct_label_vertebrae -i t2_qform.nii -s t2_seg.nii -c t2 -qc qc -initlabel labelc2c3.nii.gz 

--
Spinal Cord Toolbox (git-master-99f7f9413a7ce2536273b85611aaf8601a96c8da)

sct_label_vertebrae -i t2_qform.nii -s t2_seg.nii -c t2 -qc qc -initlabel labelc2c3.nii.gz
--

Creating temporary folder (/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210225185235.422757-label_vertebrae-fpl18fbm)

Copying input data to tmp folder...

Straighten spinal cord...
Reusing existing warping field which seems to be valid
cp /Users/julien/Desktop/20210225_Unable_to_warp_to_SC_template/warp_curve2straight.nii.gz warp_curve2straight.nii.gz
cp /Users/julien/Desktop/20210225_Unable_to_warp_to_SC_template/warp_straight2curve.nii.gz warp_straight2curve.nii.gz
cp /Users/julien/Desktop/20210225_Unable_to_warp_to_SC_template/straight_ref.nii.gz straight_ref.nii.gz
sct_apply_transfo -i data.nii -w warp_curve2straight.nii.gz -d straight_ref.nii.gz -o data_straight.nii # in /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210225185235.422757-label_vertebrae-fpl18fbm

Resample to 0.5mm isotropic...
sct_resample -i data_straight.nii -mm 0.5x0.5x0.5 -x linear -o data_straightr.nii # in /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210225185235.422757-label_vertebrae-fpl18fbm

Apply straightening to segmentation...
/Users/julien/code/sct/bin/isct_antsApplyTransforms -d 3 -i segmentation.nii -r data_straightr.nii -t warp_curve2straight.nii.gz -o segmentation_straight.nii -n Linear # in /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210225185235.422757-label_vertebrae-fpl18fbm
File /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210225185235.422757-label_vertebrae-fpl18fbm/segmentation_straight.nii already exists. Will overwrite it.

Create label to identify disc...
File /var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210225185235.422757-label_vertebrae-fpl18fbm/labelz.nii.gz already exists. Will overwrite it.

And apply straightening to label...
/Users/julien/code/sct/bin/isct_antsApplyTransforms -d 3 -i labelz.nii.gz -r data_straightr.nii -t warp_curve2straight.nii.gz -o labelz_straight.nii.gz -n NearestNeighbor # in /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210225185235.422757-label_vertebrae-fpl18fbm

Get z and disc values from straight label...
.. [366, 3]
Look for template...
Path template: /Users/julien/code/sct/data/PAM50
Open template and vertebral levels...
Disc values from template: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Z-values for each disc: [963, 938, 907, 870, 833, 800, 769, 735, 692, 646, 600, 551, 500, 449, 396, 342, 289, 231, 168, 104, 79]
Distances between discs (in voxel): [25.0, 31.0, 37.0, 37.0, 33.0, 31.0, 34.0, 43.0, 46.0, 46.0, 49.0, 51.0, 51.0, 53.0, 54.0, 53.0, 58.0, 63.0, 64.0, 25.0]
Detect intervertebral discs...
Current disc: 2 (z=366). Direction: superior
.. Peak found: z=-1 (correlation = 0.5775599626266562)
Current disc: 1 (z=396). Direction: superior
.. correcting factor: 1.0
.. Switching to inferior direction.
Current disc: 3 (z=329). Direction: inferior
.. Peak found: z=-1 (correlation = 0.6188858852022059)
.. correcting factor: 1.0
Current disc: 4 (z=291). Direction: inferior
.. Peak found: z=1 (correlation = 0.6018650498806872)
.. correcting factor: 0.990990990990991
Current disc: 5 (z=259). Direction: inferior
.. Peak found: z=-1 (correlation = 0.52241883515554)
.. correcting factor: 1.0008190008190008
Current disc: 6 (z=227). Direction: inferior
.. Peak found: z=-3 (correlation = 0.49120218164754387)
.. correcting factor: 1.020010039364878
Current disc: 7 (z=189). Direction: inferior
.. Peak found: z=4 (correlation = 0.41771563159212605)
.. correcting factor: 1.001969150451124
Current disc: 8 (z=150). Direction: inferior
.. Peak found: z=2 (correlation = 0.5179913270452637)
.. correcting factor: 0.9950433249713952
Current disc: 9 (z=106). Direction: inferior
.. Peak found: z=0 (correlation = 0.4167839872169406)
.. correcting factor: 0.9956629093499707
Current disc: 10 (z=60). Direction: inferior
.. Peak found: z=2 (correlation = 0.5821969040859959)
.. correcting factor: 0.991313890436689
Current disc: 11 (z=13). Direction: inferior
.. Peak found: z=4 (correlation = 0.5264519084825318)
.. correcting factor: 0.9840192360868978
Adding top disc based on adjusted template distance: #0
.. approximate distance: 25
Traceback (most recent call last):
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 491, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 425, in main
    verbose=verbose, path_template=path_template, path_output=path_output, scale_dist=scale_dist)
  File "/Users/julien/code/sct/spinalcordtoolbox/vertebrae/core.py", line 251, in vertebral_detection
    label_discs(fname_seg, list_disc_z, list_disc_value, verbose=verbose)
  File "/Users/julien/code/sct/spinalcordtoolbox/vertebrae/core.py", line 522, in label_discs
    cx, cy = [int(x) for x in np.round(center_of_mass(slices)).tolist()]
  File "/Users/julien/code/sct/spinalcordtoolbox/vertebrae/core.py", line 259, in center_of_mass
    raise ValueError("Array has no mass")
ValueError: Array has no mass

```

</details>

These discontinuities are caused by issues with the segmentation (`sct_deepseg_sc`).

When "fixing" these holes manually, this fixes the issue. See below how it was fixed: (red: old seg, green: new seg with holes filled):
Screen Shot 2021-02-25 at 7 05 50 PM

Related to https://forum.spinalcordmri.org/t/unable-to-warp-to-sc-template/635

### Steps to Reproduce

I'm trying to reproduce the error using **sct_example_data** dataset, however the first attempts were unsuccessful. First, I've manually created this small discontinuity:

Screen Shot 2021-02-25 at 9 16 51 PM

And then running the following command was successful (ie: no error):
~~~
sct_label_vertebrae -i t2.nii.gz -s t2_seg_discontinuity-large2-disc.nii.gz -c t2
~~~ 

I then decided to increase the discontinuity:

Screen Shot 2021-02-25 at 9 16 03 PM

Again, no error. Then, I suspected that the error might come at the junction between two vertebral levels, where the algorithm is calculating the center of mass to place the disc labels (output for `sct_label_vertebrae`). So I've further increased the discontinuity so that it juxtaposes with a level of a disc:

Screen Shot 2021-02-25 at 9 16 39 PM

Bingo 🎉  I got this:
~~~
[...]
Adding top disc based on adjusted template distance: #0
.. approximate distance: 24
Traceback (most recent call last):
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 491, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 425, in main
    verbose=verbose, path_template=path_template, path_output=path_output, scale_dist=scale_dist)
  File "/Users/julien/code/sct/spinalcordtoolbox/vertebrae/core.py", line 251, in vertebral_detection
    label_discs(fname_seg, list_disc_z, list_disc_value, verbose=verbose)
  File "/Users/julien/code/sct/spinalcordtoolbox/vertebrae/core.py", line 522, in label_discs
    cx, cy = [int(x) for x in np.round(center_of_mass(slices)).tolist()]
  File "/Users/julien/code/sct/spinalcordtoolbox/vertebrae/core.py", line 259, in center_of_mass
    raise ValueError("Array has no mass")
ValueError: Array has no mass
~~~

So the source of the problem is now known. 

### Potential solutions

Given that we compute the spinal cord centerline (for the straightening step), and that the centerline is interpolated at the segmentation discontinuities, we could consider using that centerline for placing the output disc labels. 

<details>
<summary> <bold>EDIT, @joshuacwnewton:</bold> Relevant code snippets for centerline interpolation </summary>

1. The problematic segmented cord (including the discontinuity) gets passed to `sct_straighten_spinalcord`:

https://github.com/neuropoly/spinalcordtoolbox/blob/900d29753117246fbb39d3ea07d642725a004b23/spinalcordtoolbox/scripts/sct_label_vertebrae.py#L306-L311

2. Then it gets used directly as a centerline:

https://github.com/neuropoly/spinalcordtoolbox/blob/900d29753117246fbb39d3ea07d642725a004b23/spinalcordtoolbox/scripts/sct_straighten_spinalcord.py#L203-L205

3. Then the `straighten` method gets called:

https://github.com/neuropoly/spinalcordtoolbox/blob/900d29753117246fbb39d3ea07d642725a004b23/spinalcordtoolbox/straightening.py#L62-L64

4. And the relevant interpolation is here:

https://github.com/neuropoly/spinalcordtoolbox/blob/900d29753117246fbb39d3ea07d642725a004b23/spinalcordtoolbox/straightening.py#L147-L150

https://github.com/neuropoly/spinalcordtoolbox/blob/900d29753117246fbb39d3ea07d642725a004b23/spinalcordtoolbox/centerline/core.py#L86-L88

</details>

### PR DESCRIPTION
**Pull request by joshuacwnewton**
#### GitHub

- [X] I've given this PR a concise, self-descriptive, and meaningful title
- [X] I've linked relevant issues in the PR body
- [X] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [X] I've assigned a reviewer

#### PR contents

- [ ] I've consulted [SCT's internal developer documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki) to ensure my contribution is in line with any relevant design decisions
- [X] I've added [relevant tests](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Tests) for my contribution
- [ ] I've updated the [relevant documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description

I first wrote a failing test to reproduce the problem, then applied a fix which causes the test to pass. 

The fix falls back on an interpolated centerline if the segmentation is missing in places where the disc label should go.

## Linked issues

Fixes #3252.

### CODE REVIEW

**Review by Drulex — APPROVED** [review]
LGTM. Does this method make sense if there are a lot of discontinuities? What I mean is should we check if `slices` is valid before interpolating on something that doesn't make sense?

**Comment by jcohenadad** [comment]
> LGTM. Does this method make sense if there are a lot of discontinuities? What I mean is should we check if `slices` is valid before interpolating on something that doesn't make sense?

the centerline algo is quite robust for this. The output centerline is highly regularized (spline). However, what could happen is that the segmentation is completely wrong, e.g., muscle/fat instead of the SC is segmented. In that case, the centerline would be wrong. But that's something we cannot easily verify, and it is the responsibility of the user to properly QC these events.

**Review by jcohenadad — APPROVED** [review]
this is fantastic. Thank you so much @joshuacwnewton

**Comment by joshuacwnewton** [comment]
> Does this method make sense if there are a lot of discontinuities? What I mean is should we check if `slices` is valid before interpolating on something that doesn't make sense?

Thank you for asking this, @Drulex!

> However, what could happen is that the segmentation is completely wrong, e.g., muscle/fat instead of the SC is segmented. In that case, the centerline would be wrong. But that's something we cannot easily verify, and it is the responsibility of the user to properly QC these events.

To add to this, we now have a more verbose warning message that will hopefully nudge users to trouble-shoot their segmentation if there are severe discontinuities. 

https://github.com/neuropoly/spinalcordtoolbox/blob/d9041fe8f222e4c05dad8c10a2969ba703e3975e/spinalcordtoolbox/vertebrae/core.py#L531-L532

Although now that I read this back, I'm not sure it's clear enough. Maybe instead it should read:

```python
"During disc labeling, center of mass calculation failed due to discontinuities in segmented spinal cord. "
"Please check the quality of your segmentation. Using interpolated centerline as a fallback."
```

**Pull request merged**
