### PR TITLE
Move course materials to "Tutorials" page for visibility

### LINKED ISSUE #3231: courses hard to find in the doc
image

--> not intuitive.

we should move the "course" somewhere else

### PR DESCRIPTION
**Pull request by joshuacwnewton**
#### GitHub

- [X] I've given this PR a concise, self-descriptive, and meaningful title
- [X] I've linked relevant issues in the PR body
- [X] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [X] I've assigned a reviewer

#### PR contents

- [ ] I've consulted [SCT's internal developer documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki) to ensure my contribution is in line with any relevant design decisions
- [ ] I've added [relevant tests](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Tests) for my contribution
- [X] I've updated the [relevant documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description

Courses/tutorials cover mostly the same material (in-depth usage of command line scripts), so I thought to combine them.

## Linked issues

Fixes #3231.

### CODE REVIEW

**Comment by ahill187** [comment]
Looks good to me, makes it a lot clearer :) I would even maybe put `Tutorials and Courses` as is its own header, outside of `User Section`, so you would have 4 main level headers: 
```
Overview
User Section
Tutorials and Courses
Developer Section
```

**Comment by joshuacwnewton** [comment]
Thanks for the kind words! :) 

> I would even maybe put Tutorials and Courses as is its own header, outside of User Section, so you would have 4 main level headers:
> ```
> Overview
> User Section
> Tutorials and Courses
> Developer Section
> ```

Just to clarify, what would the subpages be? Perhaps each of the subgroups would have its own page? e.g.

```diff
Overview
    Introduction
    Overview
    SCT Concepts
    References

User section
    Installation
    Getting Started
    Command-Line Tools
-   Tutorials
    Support

+ Tutorials and Courses
+   Courses            
+   Tutorial pages     
+   Video tutorials    

Developer section
    Contributing to SCT
    Python API
    Changelog
    License
```

I wonder if there's enough material there to even have subpages, hrm. Maybe just the 1 page for now.

**Comment by ahill187** [comment]
> Thanks for the kind words! :)
> 
> > I would even maybe put Tutorials and Courses as is its own header, outside of User Section, so you would have 4 main level headers:
> > ```
> > Overview
> > User Section
> > Tutorials and Courses
> > Developer Section
> > ```
> 
> Just to clarify, what would the subpages be? Perhaps each of the subgroups would have its own page? e.g.
> 
> ```diff
> Overview
>     Introduction
>     Overview
>     SCT Concepts
>     References
> 
> User section
>     Installation
>     Getting Started
>     Command-Line Tools
> -   Tutorials
>     Support
> 
> + Tutorials and Courses
> +   Courses            
> +   Tutorial pages     
> +   Video tutorials    
> 
> Developer section
>     Contributing to SCT
>     Python API
>     Changelog
>     License
> ```
> 
> I wonder if there's enough material there to even have subpages, hrm. Maybe just the 1 page for now.

Yah, exactly!

**Review by ahill187 — APPROVED** [review]
Looks great!!

**Pull request merged**
