### PR TITLE
Force the installation of pip v9.0.1 in the requirements file

### PR DESCRIPTION
**Pull request by peristeri**

### CODE REVIEW

**Comment by jcohenadad** [comment]
pip 9.0.1 is already forced in Conda requirements. Do we really want to duplicate it in the Pip requirements?

**Comment by peristeri** [comment]
There's 2 installation steps, the first step installed the updated pip, and the second step (pip) downgraded the pip version. By matching the version, we make sure that the version matches in both steps.

**Comment by jcohenadad** [comment]
didn't fix the problem:

~~~
./install_sct -d -b -p

Welcome to the SCT installer!
 data directory will not be (re)-installed
 SCT binaries will not be (re)-installed 
 Multiprocessing using MPI activated

SCT version ......... dev
Installation type ... git
Operating system .... linux
sudo mode ........... 0

SCT will be installed here: [/home/jcohen/sct]
Do you agree? yes/no: y
mkdir: cannot create directory ‘/home/jcohen/sct’: File exists

Removing sct and isct softlink from /home/jcohen/sct/bin

Skipping copy of source files (source and destination folders are the same)

Create launchers for Python scripts
>> mkdir -p /home/jcohen/sct/bin
>> cd /home/jcohen/sct/install
>> ./update_bin.sh
#!/bin/bash
$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/sct_launcher $(basename $0).py $@
yes isct_check_detection
yes isct_convert_binary_to_trilinear
yes isct_minc2volume-viewer
yes isct_test_ants
yes isct_warpmovie_generator
yes msct_image
yes msct_multiatlas_seg
yes sct_apply_transfo
yes sct_average_data_within_mask
no sct_change_image_type
yes sct_check_atlas_integrity
yes sct_check_dependencies
yes sct_compute_ernst_angle
yes sct_compute_hausdorff_distance
yes sct_compute_mscc
yes sct_compute_mtr
yes sct_compute_snr
yes sct_concat_transfo
yes sct_convert
yes sct_create_mask
yes sct_crop_image
no sct_denoising_onlm
yes sct_dice_coefficient
yes sct_dmri_compute_dti
yes sct_dmri_concat_bvals
yes sct_dmri_concat_bvecs
yes sct_dmri_create_noisemask
no sct_dmri_eddy_correct
yes sct_dmri_get_bvalue
yes sct_dmri_moco
yes sct_dmri_separate_b0_and_dwi
yes sct_dmri_transpose_bvecs
yes sct_download_data
yes sct_extract_metric
yes sct_flatten_sagittal
yes sct_fmri_compute_tsnr
yes sct_fmri_moco
yes sct_get_centerline
yes sct_image
no sct_invert_image
yes sct_label_utils
yes sct_label_vertebrae
yes sct_make_ground_truth
yes sct_maths
yes sct_merge_images
yes sct_pipeline
yes sct_process_segmentation
yes sct_propseg
yes sct_qc
yes sct_register_graymatter
yes sct_register_multimodal
yes sct_register_to_template
yes sct_resample
yes sct_segment_graymatter
yes sct_smooth_spinalcord
yes sct_straighten_spinalcord
yes sct_testing
yes sct_viewer
yes sct_warp_template

Installing conda...
>> rm -rf /home/jcohen/sct/python
>> mkdir /home/jcohen/sct/python
--2017-06-23 17:12:26--  https://repo.continuum.io/miniconda/Miniconda2-4.1.11-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.16.18.10, 104.16.19.10, 2400:cb00:2048:1::6810:130a, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.16.18.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27792209 (27M) [application/x-sh]
Saving to: ‘/tmp/tmp.2RbeiXnrnd/miniconda.sh’

/tmp/tmp.2RbeiXnrnd/minicon 100%[=========================================>]  26.50M  --.-KB/s    in 0.1s    

2017-06-23 17:12:26 (261 MB/s) - ‘/tmp/tmp.2RbeiXnrnd/miniconda.sh’ saved [27792209/27792209]

exit status is 0
>> bash /tmp/tmp.2RbeiXnrnd/miniconda.sh -p /home/jcohen/sct/python -b -f
PREFIX=/home/jcohen/sct/python
installing: python-2.7.12-1 ...
installing: conda-env-2.5.2-py27_0 ...
installing: openssl-1.0.2h-1 ...
installing: pycosat-0.6.1-py27_1 ...
installing: pyyaml-3.11-py27_4 ...
installing: readline-6.2-2 ...
installing: requests-2.10.0-py27_0 ...
installing: ruamel_yaml-0.11.14-py27_0 ...
installing: sqlite-3.13.0-0 ...
installing: tk-8.5.18-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-3 ...
installing: conda-4.1.11-py27_0 ...
installing: pycrypto-2.6.1-py27_4 ...
installing: pip-8.1.2-py27_0 ...
installing: wheel-0.29.0-py27_0 ...
installing: setuptools-23.0.0-py27_0 ...
Python 2.7.12 :: Continuum Analytics, Inc.
creating default environment...
using -f (force) option
installation finished.
WARNING:
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda2.
    For best results, please verify that your PYTHONPATH only points to
    directories of packages that are compatible with the Python interpreter
    in Miniconda2: /home/jcohen/sct/python
Conda installation successful
>> . /home/jcohen/sct/python/bin/activate /home/jcohen/sct/python

Installing Python dependencies...
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /home/jcohen/sct/python:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          502 B
    jbig-2.1                   |                0          29 KB
    jpeg-9b                    |                0         941 KB
    libffi-3.2.1               |                1          38 KB
    libgfortran-3.0.0          |                1         281 KB
    libiconv-1.14              |                0         2.0 MB
    mkl-11.3.3                 |                0       122.1 MB
    mpich2-1.4.1p1             |                0         2.7 MB
    pixman-0.34.0              |                0         3.8 MB
    xz-5.2.2                   |                1         669 KB
    libpng-1.6.27              |                0         219 KB
    libtiff-4.0.6              |                3         1.5 MB
    libxml2-2.9.4              |                0         3.7 MB
    pcre-8.39                  |                1         656 KB
    decorator-4.0.11           |           py27_0          15 KB
    enum34-1.1.6               |           py27_0          53 KB
    freetype-2.5.5             |                2         2.5 MB
    glib-2.50.2                |                1         5.6 MB
    idna-2.5                   |           py27_0         121 KB
    ipaddress-1.0.18           |           py27_0          31 KB
    mpi4py-2.0.0               |           py27_2         1.8 MB
    numpy-1.11.2               |           py27_0         6.2 MB
    olefile-0.44               |           py27_0          52 KB
    psutil-5.2.2               |           py27_0         260 KB
    pyasn1-0.2.3               |           py27_0          75 KB
    pycparser-2.17             |           py27_0         153 KB
    pyparsing-2.1.4            |           py27_0          70 KB
    pytz-2017.2                |           py27_0         204 KB
    requests-2.12.4            |           py27_0         762 KB
    sip-4.18                   |           py27_0         264 KB
    six-1.10.0                 |           py27_0          16 KB
    xlrd-0.9.4                 |           py27_0         179 KB
    xlwt-1.0.0                 |           py27_0         152 KB
    cffi-1.10.0                |           py27_0         329 KB
    cycler-0.10.0              |           py27_0          11 KB
    fontconfig-2.12.1          |                3         429 KB
    networkx-1.11              |           py27_0         1.1 MB
    pillow-4.1.1               |           py27_0         840 KB
    pip-9.0.1                  |           py27_1         1.6 MB
    python-dateutil-2.6.0      |           py27_0         232 KB
    scipy-0.18.1               |      np111py27_0        30.9 MB
    xlutils-1.7.1              |           py27_0          65 KB
    cairo-1.14.8               |                0         609 KB
    cryptography-1.6           |           py27_0         837 KB
    pandas-0.18.1              |      np111py27_0        13.0 MB
    scikit-learn-0.17.1        |      np111py27_2         8.6 MB
    harfbuzz-0.9.39            |                2         1.2 MB
    pycairo-1.10.0             |           py27_0          81 KB
    pyopenssl-16.2.0           |           py27_0          68 KB
    conda-4.3.22               |           py27_0         493 KB
    pango-1.40.3               |                1         938 KB
    qt-4.8.7                   |                4        32.7 MB
    pyqt-4.11.4                |           py27_4         3.3 MB
    matplotlib-1.5.1           |      np111py27_0         8.4 MB
    scikit-image-0.12.3        |      np111py27_1        26.4 MB
    ------------------------------------------------------------
                                           Total:       288.9 MB

The following NEW packages will be INSTALLED:

    cairo:           1.14.8-0          
    cffi:            1.10.0-py27_0     
    cryptography:    1.6-py27_0        
    cycler:          0.10.0-py27_0     
    decorator:       4.0.11-py27_0     
    enum34:          1.1.6-py27_0      
    fontconfig:      2.12.1-3          
    freetype:        2.5.5-2           
    glib:            2.50.2-1          
    harfbuzz:        0.9.39-2          
    idna:            2.5-py27_0        
    ipaddress:       1.0.18-py27_0     
    jbig:            2.1-0             
    jpeg:            9b-0              
    libffi:          3.2.1-1           
    libgfortran:     3.0.0-1           
    libiconv:        1.14-0            
    libpng:          1.6.27-0          
    libtiff:         4.0.6-3           
    libxml2:         2.9.4-0           
    matplotlib:      1.5.1-np111py27_0 
    mkl:             11.3.3-0          
    mpi4py:          2.0.0-py27_2      
    mpich2:          1.4.1p1-0         
    networkx:        1.11-py27_0       
    numpy:           1.11.2-py27_0     
    olefile:         0.44-py27_0       
    pandas:          0.18.1-np111py27_0
    pango:           1.40.3-1          
    pcre:            8.39-1            
    pillow:          4.1.1-py27_0      
    pixman:          0.34.0-0          
    psutil:          5.2.2-py27_0      
    pyasn1:          0.2.3-py27_0      
    pycairo:         1.10.0-py27_0     
    pycparser:       2.17-py27_0       
    pyopenssl:       16.2.0-py27_0     
    pyparsing:       2.1.4-py27_0      
    pyqt:            4.11.4-py27_4     
    python-dateutil: 2.6.0-py27_0      
    pytz:            2017.2-py27_0     
    qt:              4.8.7-4           
    scikit-image:    0.12.3-np111py27_1
    scikit-learn:    0.17.1-np111py27_2
    scipy:           0.18.1-np111py27_0
    sip:             4.18-py27_0       
    six:             1.10.0-py27_0     
    xlrd:            0.9.4-py27_0      
    xlutils:         1.7.1-py27_0      
    xlwt:            1.0.0-py27_0      
    xz:              5.2.2-1           

The following packages will be UPDATED:

    conda:           4.1.11-py27_0      --> 4.3.22-py27_0
    conda-env:       2.5.2-py27_0       --> 2.6.0-0      
    pip:             8.1.2-py27_0       --> 9.0.1-py27_1 
    requests:        2.10.0-py27_0      --> 2.12.4-py27_0

Fetching packages ...
conda-env-2.6. 100% |##############################################################| Time: 0:00:00 210.74 kB/s
jbig-2.1-0.tar 100% |##############################################################| Time: 0:00:00  10.88 MB/s
jpeg-9b-0.tar. 100% |##############################################################| Time: 0:00:00  38.17 MB/s
libffi-3.2.1-1 100% |##############################################################| Time: 0:00:00  12.09 MB/s
libgfortran-3. 100% |##############################################################| Time: 0:00:00  35.84 MB/s
libiconv-1.14- 100% |##############################################################| Time: 0:00:00  59.11 MB/s
mkl-11.3.3-0.t 100% |##############################################################| Time: 0:00:01  84.16 MB/s
mpich2-1.4.1p1 100% |##############################################################| Time: 0:00:00  48.26 MB/s
pixman-0.34.0- 100% |##############################################################| Time: 0:00:00  49.50 MB/s
xz-5.2.2-1.tar 100% |##############################################################| Time: 0:00:00  38.49 MB/s
libpng-1.6.27- 100% |##############################################################| Time: 0:00:00  25.42 MB/s
libtiff-4.0.6- 100% |##############################################################| Time: 0:00:00  41.67 MB/s
libxml2-2.9.4- 100% |##############################################################| Time: 0:00:00  49.54 MB/s
pcre-8.39-1.ta 100% |##############################################################| Time: 0:00:00  37.89 MB/s
decorator-4.0. 100% |##############################################################| Time: 0:00:00   5.59 MB/s
enum34-1.1.6-p 100% |##############################################################| Time: 0:00:00  16.09 MB/s
freetype-2.5.5 100% |##############################################################| Time: 0:00:00  47.04 MB/s
glib-2.50.2-1. 100% |##############################################################| Time: 0:00:10 572.20 kB/s
idna-2.5-py27_ 100% |##############################################################| Time: 0:00:00  21.35 MB/s
ipaddress-1.0. 100% |##############################################################| Time: 0:00:00   9.86 MB/s
mpi4py-2.0.0-p 100% |##############################################################| Time: 0:00:00  38.99 MB/s
numpy-1.11.2-p 100% |##############################################################| Time: 0:00:03   2.08 MB/s
olefile-0.44-p 100% |##############################################################| Time: 0:00:00  12.74 MB/s
psutil-5.2.2-p 100% |##############################################################| Time: 0:00:00  32.35 MB/s
pyasn1-0.2.3-p 100% |##############################################################| Time: 0:00:00  19.46 MB/s
pycparser-2.17 100% |##############################################################| Time: 0:00:00  21.50 MB/s
pyparsing-2.1. 100% |##############################################################| Time: 0:00:00  17.09 MB/s
pytz-2017.2-py 100% |##############################################################| Time: 0:00:00  25.29 MB/s
requests-2.12. 100% |##############################################################| Time: 0:00:00  37.67 MB/s
sip-4.18-py27_ 100% |##############################################################| Time: 0:00:00  22.27 MB/s
six-1.10.0-py2 100% |##############################################################| Time: 0:00:00   5.67 MB/s
xlrd-0.9.4-py2 100% |##############################################################| Time: 0:00:00  27.82 MB/s
xlwt-1.0.0-py2 100% |##############################################################| Time: 0:00:00  26.35 MB/s
cffi-1.10.0-py 100% |##############################################################| Time: 0:00:00  36.83 MB/s
cycler-0.10.0- 100% |##############################################################| Time: 0:00:00   4.37 MB/s
fontconfig-2.1 100% |##############################################################| Time: 0:00:00  31.30 MB/s
networkx-1.11- 100% |##############################################################| Time: 0:00:00  43.87 MB/s
pillow-4.1.1-p 100% |##############################################################| Time: 0:00:02 420.90 kB/s
pip-9.0.1-py27 100% |##############################################################| Time: 0:00:00  45.12 MB/s
python-dateuti 100% |##############################################################| Time: 0:00:00  26.05 MB/s
scipy-0.18.1-n 100% |##############################################################| Time: 0:00:06   5.15 MB/s
xlutils-1.7.1- 100% |##############################################################| Time: 0:00:00  14.62 MB/s
cairo-1.14.8-0 100% |##############################################################| Time: 0:00:00  37.70 MB/s
cryptography-1 100% |##############################################################| Time: 0:00:00  45.95 MB/s
pandas-0.18.1- 100% |##############################################################| Time: 0:00:02   6.45 MB/s
scikit-learn-0 100% |##############################################################| Time: 0:00:00  22.63 MB/s
harfbuzz-0.9.3 100% |##############################################################| Time: 0:00:00  42.47 MB/s
pycairo-1.10.0 100% |##############################################################| Time: 0:00:00  14.93 MB/s
pyopenssl-16.2 100% |##############################################################| Time: 0:00:00  18.22 MB/s
conda-4.3.22-p 100% |##############################################################| Time: 0:00:00  43.14 MB/s
pango-1.40.3-1 100% |##############################################################| Time: 0:00:00  54.31 MB/s
qt-4.8.7-4.tar 100% |##############################################################| Time: 0:00:11   3.00 MB/s
pyqt-4.11.4-py 100% |##############################################################| Time: 0:00:00  43.27 MB/s
matplotlib-1.5 100% |##############################################################| Time: 0:00:10 849.51 kB/s
scikit-image-0 100% |##############################################################| Time: 0:00:10   2.69 MB/s
Extracting packages ...
[      COMPLETE      ]|#################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#################################################################################| 100%
Collecting nipy==0.4.0 (from -r /home/jcohen/sct/install/requirements/requirementsPip.txt (line 1))
  Using cached nipy-0.4.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting nibabel==2.1.0 (from -r /home/jcohen/sct/install/requirements/requirementsPip.txt (line 2))
Collecting dipy==0.11.0 (from -r /home/jcohen/sct/install/requirements/requirementsPip.txt (line 3))
  Using cached dipy-0.11.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting distribute2mpi==0.3.0 (from -r /home/jcohen/sct/install/requirements/requirementsPip.txt (line 4))
  Using cached distribute2mpi-0.3.0-py2.py3-none-any.whl
Collecting tqdm==4.11.2 (from -r /home/jcohen/sct/install/requirements/requirementsPip.txt (line 5))
  Using cached tqdm-4.11.2-py2.py3-none-any.whl
Collecting pip==9.0.1 (from -r /home/jcohen/sct/install/requirements/requirementsPip.txt (line 6))
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 205kB/s 
Collecting sympy>=0.7.0 (from nipy==0.4.0->-r /home/jcohen/sct/install/requirements/requirementsPip.txt (line 1))
Collecting dill (from distribute2mpi==0.3.0->-r /home/jcohen/sct/install/requirements/requirementsPip.txt (line 4))
Collecting psutil (from distribute2mpi==0.3.0->-r /home/jcohen/sct/install/requirements/requirementsPip.txt (line 4))
Collecting mpi4py (from distribute2mpi==0.3.0->-r /home/jcohen/sct/install/requirements/requirementsPip.txt (line 4))
Collecting mpmath>=0.19 (from sympy>=0.7.0->nipy==0.4.0->-r /home/jcohen/sct/install/requirements/requirementsPip.txt (line 1))
Installing collected packages: nibabel, mpmath, sympy, nipy, dipy, dill, psutil, mpi4py, distribute2mpi, tqdm, pip
Successfully installed dill-0.2.6 dipy-0.11.0 distribute2mpi-0.3.0 mpi4py-2.0.0 mpmath-0.19 nibabel-2.1.0 nipy-0.4.0 pip-8.1.2 psutil-5.2.2 sympy-1.0 tqdm-4.11.2
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/jcohen/sct/python:

The following packages will be UPDATED:

    numpy: 1.11.2-py27_0 --> 1.12.1-py27_0

numpy-1.12.1-p 100% |##############################################################| Time: 0:00:00  73.75 MB/s
Processing /home/jcohen/sct
Requirement already satisfied (use --upgrade to upgrade): nipy==0.4.0 in /home/jcohen/sct/python/lib/python2.7/site-packages (from spinalcordtoolbox===dev)
Requirement already satisfied (use --upgrade to upgrade): nibabel==2.1.0 in /home/jcohen/sct/python/lib/python2.7/site-packages (from spinalcordtoolbox===dev)
Requirement already satisfied (use --upgrade to upgrade): dipy==0.11.0 in /home/jcohen/sct/python/lib/python2.7/site-packages (from spinalcordtoolbox===dev)
Requirement already satisfied (use --upgrade to upgrade): distribute2mpi==0.3.0 in /home/jcohen/sct/python/lib/python2.7/site-packages (from spinalcordtoolbox===dev)
Requirement already satisfied (use --upgrade to upgrade): tqdm==4.11.2 in /home/jcohen/sct/python/lib/python2.7/site-packages (from spinalcordtoolbox===dev)
Collecting pip==9.0.1 (from spinalcordtoolbox===dev)
  Using cached pip-9.0.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): sympy>=0.7.0 in /home/jcohen/sct/python/lib/python2.7/site-packages (from nipy==0.4.0->spinalcordtoolbox===dev)
Requirement already satisfied (use --upgrade to upgrade): dill in /home/jcohen/sct/python/lib/python2.7/site-packages (from distribute2mpi==0.3.0->spinalcordtoolbox===dev)
Requirement already satisfied (use --upgrade to upgrade): psutil in /home/jcohen/sct/python/lib/python2.7/site-packages (from distribute2mpi==0.3.0->spinalcordtoolbox===dev)
Requirement already satisfied (use --upgrade to upgrade): mpi4py in /home/jcohen/sct/python/lib/python2.7/site-packages (from distribute2mpi==0.3.0->spinalcordtoolbox===dev)
Requirement already satisfied (use --upgrade to upgrade): mpmath>=0.19 in /home/jcohen/sct/python/lib/python2.7/site-packages (from sympy>=0.7.0->nipy==0.4.0->spinalcordtoolbox===dev)
Installing collected packages: pip, spinalcordtoolbox
  Found existing installation: pip 8.1.2
    Uninstalling pip-8.1.2:
Exception:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/python2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/python2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/home/jcohen/sct/python/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 30] Read-only file system: '/cvmfs/soft.computecanada.ca/nix/store/77fv9dp9v8vjcg70zj66f997lay1sdvc-python2.7-pip-8.1.2/lib/python2.7/site-packages/pip-8.1.2.dist-info/DESCRIPTION.rst'
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
SCT binaries will not be (re)-install
All requirements installed!
data/ will not be (re)-install

Do you want to add the sct_* scripts to your PATH environment? yes/no: y



Run sct_check_dependencies...

--
Spinal Cord Toolbox (fix-pip/31b410f3a9aa9dfe69b49f91b3b523b1bb8eca0e)
Running /home/jcohen/sct/scripts/sct_check_dependencies.py

OS: linux (Linux-3.10.0-514.21.1.el7.x86_64-x86_64-with-centos-7.3.1611-Core)
CPU cores: Available: 32, Used by SCT: 32
RAM: MemTotal:       264035648 kB
total        used        free      shared  buff/cache   available
Mem:         257847        4404      120014         423      133427      234795
Swap:          4095           0        4095
SCT path: /home/jcohen/sct
Installation type: git
  commit: 31b410f3a9aa9dfe69b49f91b3b523b1bb8eca0e
  branch: fix-pip
Check Python path...................................[OK]
Check if data are installed.........................[OK]
Check if xlwt (1.0.0) is installed..................[OK]
Check if xlutils (1.7.1) is installed...............[OK]
Check if cryptography (1.6) is installed............[OK]
Check if scikit-learn (0.17.1) is installed.........[OK]
Check if scikit-image (0.12.3) is installed.........[OK]
Check if pyqt (4.11.4) is installed.................[OK]
Check if psutil (5.2.2) is installed................[OK]
Check if matplotlib (1.5.1) is installed............[OK]
Check if pip (9.0.1) is installed...................[WARNING]
  Detected version: 8.1.2. Required version: 9.0.1
Check if requests (2.12.4) is installed.............[OK]
Check if xlrd (0.9.4) is installed..................[OK]
Check if pandas (0.18.1) is installed...............[OK]
Check if mpi4py (2.0.0) is installed................[OK]
Check if dipy (0.11.0) is installed.................[OK]
Check if tqdm (4.11.2) is installed.................[OK]
Check if nibabel (2.1.0) is installed...............[OK]
Check if nipy (0.4.0) is installed..................[OK]
Check if pip (9.0.1) is installed...................[WARNING]
  Detected version: 8.1.2. Required version: 9.0.1
Check if distribute2mpi (0.3.0) is installed........[OK]
Check if numpy is installed.........................[OK]
Check if scipy is installed.........................[OK]
Check if spinalcordtoolbox is installed.............[FAIL]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if figure can be opened.......................[FAIL]
(<type 'exceptions.RuntimeError'>, RuntimeError(u'Invalid DISPLAY variable',), <traceback object at 0x7ff91dceeb48>)

INSTALLATION ERROR!
Please copy the historic of this Terminal (starting with the command install_sct) and paste it in the SCT Help forum under a new ticket:
https://sourceforge.net/p/spinalcordtoolbox/discussion/help/
~~~

**Comment by peristeri** [comment]
More complete solution in #1384

**Pull request closed without merging**
