### PR TITLE
Update API documentation

### LINKED ISSUE #2742: API documentation: internal vs external code
I am in the process of working on API improvements for the project. To get familiar with the API I decided to revive the RTD API documentation and update it.

I noticed that some API modules have multiple files, sometimes with similar names (for example `core.py`) and I was wondering if there is some type of convention to separate internal code vs external code.

I understand that everything called from `/scripts/sct_*` should be documented as those scripts are consuming the API, however I am wondering if there is some code in `/spinalcordtoolbox` that is not meant to be included in the external API docs.

Relates to #1656

### PR DESCRIPTION
**Pull request by Drulex**
- In the scope of https://github.com/neuropoly/spinalcordtoolbox/projects/7
- Fixes #2742 

The purpose of this PR is to update the documentation build system and docs themselves to reflect the current state of the code base. This is a stepping stone in the large effort to refactor the core code as library code.

Update documentation:
- Fix sphinx build
- Add all missing modules
- Fix broken dosctrings
- Fix sphinx warnings

This PR does not validate the content/correctness of the docs, but merely validates that the docs build, display correctly and are up to date.

Some observations picked up along the way:
- `deepseg_sc.cnn_models.py` -> no docstrings, excluded from docs for the moment
- `deepseg_sc.cnn_models_3d.py` -> no docstrings, excluded from docs for the moment
- `centerline.nurbs.py` -> no docstrings + comments written in french, excluded from docs for the moment
- `download.py` -> not sure it should be part of core API

**Note:**
Due to the fact that we use the `sphinxcontrib.programoutput` sphinx extension, sphinx needs to import the project's python code which means that the project's dependencies must be installed prior to building the documentation. This isn't normally a problem, but given that we install the dependencies in a custom environment (conda) and that `pip install -r requirements.txt` does not simply work out of the box outside that environment, this adds complexity to the documentation build as we need to use the same environment to be able to install the dependencies.

### CODE REVIEW

**Comment by Drulex** [comment]
Due to the fact that we use the sphinxcontrib.programoutput sphinx extension, sphinx needs to import the project's python code which means that the project's dependencies must be installed prior to building the documentation. 

This isn't normally a problem, but given that we install the dependencies in a custom environment (conda) and that `pip install -r requirements.txt` does not simply work out of the box outside that environment, this adds complexity to the documentation build as we need to use the same environment to be able to install the dependencies.

**Comment by jcohenadad** [comment]
> Due to the fact that we use the `sphinxcontrib.programoutput` sphinx extension, sphinx needs to import the project's python code which means that the project's dependencies must be installed prior to building the documentation.
> 
> This isn't normally a problem, but given that we install the dependencies in a custom environment (conda) and that `pip install -r requirements.txt` does not simply work out of the box outside that environment, this adds complexity to the documentation build as we need to use the same environment to be able to install the dependencies.
> 
> edit: looks like this was already observed before: [#1683 (comment)](https://github.com/neuropoly/spinalcordtoolbox/pull/1683#issuecomment-386704299)

Trying to pip install with a conda virtual environment (i don't have native python3 on my macOS).

<details><summary></summary>

~~~
julien-macbook:~ $ conda activate py3.6
(py3.6) julien-macbook:~/code/sct $ pip install -r requirements.txt 
Ignoring torch: markers 'sys_platform != "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform != "darwin"' don't match your environment
Looking in links: https://download.pytorch.org/whl/cpu/torch_stable.html
Requirement already satisfied: numpy in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (1.16.4)
Collecting colored (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/b2/16/04827e24c14266d9161bd86bad50069fea453fa006c3d2b31da39251184a/colored-1.4.2.tar.gz
Collecting dipy (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/2f/8e/7a1bacd3dd742aaecbeea0519a3b10119195a2d71c760bd7de93be23575d/dipy-1.1.1-cp36-cp36m-macosx_10_6_intel.whl
Collecting futures (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/05/80/f41cca0ea1ff69bce7e7a7d76182b47bb4e1a494380a532af3e8ee70b9ec/futures-3.1.1-py3-none-any.whl
Collecting h5py (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/ec/7f/a833846f5628d00f82ad87010f98294257535f1052e4a466888deba29f94/h5py-2.10.0-cp36-cp36m-macosx_10_6_intel.whl
Collecting ivadomed==2.0.2 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/79/7c/a3243b95f1b8ce55d54be78d24f1f05716257fbca27464b635e644003606/ivadomed-2.0.2-py3-none-any.whl
Collecting Keras==2.1.5 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/ba/65/e4aff762b8696ec0626a6654b1e73b396fcc8b7cc6b98d78a1bc53b85b48/Keras-2.1.5-py2.py3-none-any.whl
Requirement already satisfied: matplotlib in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from -r requirements.txt (line 8)) (3.2.2)
Requirement already satisfied: nibabel in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from -r requirements.txt (line 9)) (2.4.1)
Requirement already satisfied: pandas in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from -r requirements.txt (line 10)) (0.24.2)
Collecting pyqt5==5.11.3 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/31/22/e79a35bab2221b7bdbb3cdadb25bc9b492080b7529eec5fcbfd3f2d57606/PyQt5-5.11.3-5.11.2_a-cp35.cp36.cp37.cp38-abi3-macosx_10_6_intel.whl
Collecting pytest (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/9f/f3/0a83558da436a081344aa6c8b85ea5b5f05071214106036ce341b7769b0b/pytest-5.4.3-py3-none-any.whl
Collecting pytest-cov (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/3d/13/ae3dec587b1cc07fb9f294e52ea9ad140266aea55adb9e12eade3625bd27/pytest_cov-2.10.0-py2.py3-none-any.whl
Collecting raven (from -r requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/bd/8e/62e26a88c0a1bbae677200baf0767c1022321a6555634f8129e6d55c5ddc/raven-6.10.0-py2.py3-none-any.whl
Requirement already satisfied: requests in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from -r requirements.txt (line 15)) (2.22.0)
Collecting requirements-parser (from -r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/03/80/eb6ba1dd0429089436e90e556db50884ea21da060b10f2e5668c4cac99da/requirements-parser-0.2.0.tar.gz
Requirement already satisfied: scipy in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from -r requirements.txt (line 17)) (1.3.0)
Collecting scikit-image (from -r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/17/1f/bea69a3a5d7efb0e22993d08c4328678e5f6a513cad55247142be8473142/scikit_image-0.17.2-cp36-cp36m-macosx_10_13_x86_64.whl
Requirement already satisfied: scikit-learn in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from -r requirements.txt (line 19)) (0.21.2)
Collecting tensorflow==1.5.0 (from -r requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/f2/0b/da4f6379f12ca375b1155f542d0d36803ba2c6b406d39e6bde5eaa2f0abe/tensorflow-1.5.0-cp36-cp36m-macosx_10_11_x86_64.whl
Collecting torch==1.5.0 (from -r requirements.txt (line 27))
  Using cached https://files.pythonhosted.org/packages/c9/e0/12f7c10e6b932f5e5d39f4ed5697b41b7751443a652d8c1c031e12e197f0/torch-1.5.0-cp36-none-macosx_10_9_x86_64.whl
Collecting torchvision==0.6.0 (from -r requirements.txt (line 29))
  Using cached https://files.pythonhosted.org/packages/68/22/edc555cc6ad8a5e17d508da8447fe60d1e29207ae63164b35853d072774e/torchvision-0.6.0-cp36-cp36m-macosx_10_9_x86_64.whl
Collecting xlwt (from -r requirements.txt (line 30))
  Using cached https://files.pythonhosted.org/packages/44/48/def306413b25c3d01753603b1a222a011b8621aed27cd7f89cbc27e6b0f4/xlwt-1.3.0-py2.py3-none-any.whl
Requirement already satisfied: tqdm in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from -r requirements.txt (line 31)) (4.32.2)
Collecting transforms3d (from -r requirements.txt (line 32))
Requirement already satisfied: urllib3[secure] in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from -r requirements.txt (line 33)) (1.25.3)
Requirement already satisfied: six in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from h5py->-r requirements.txt (line 5)) (1.12.0)
Collecting bids-neuropoly>=0.2 (from ivadomed==2.0.2->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/86/52/6ed521248862d5447490d52f6b6ffaa4588d56096fe91a415d28f4a80249/bids_neuropoly-0.2-py3-none-any.whl
Collecting onnxruntime (from ivadomed==2.0.2->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/ca/b6/1010e41402e06c8f2d6277a4875ce2bdac27c913de0e00f24cf320171872/onnxruntime-1.3.0-cp36-cp36m-macosx_10_12_x86_64.whl
Collecting pillow>=7.0.0 (from ivadomed==2.0.2->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/04/8f/c42f534b73680f501858a8c7171705a55c7347c86419b74fa585370c8306/Pillow-7.2.0-cp36-cp36m-macosx_10_10_x86_64.whl
Collecting tensorboard (from ivadomed==2.0.2->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/1d/74/0a6fcb206dcc72a6da9a62dd81784bfdbff5fedb099982861dc2219014fb/tensorboard-2.2.2-py3-none-any.whl
Requirement already satisfied: joblib in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from ivadomed==2.0.2->-r requirements.txt (line 6)) (0.13.2)
Collecting seaborn (from ivadomed==2.0.2->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/c7/e6/54aaaafd0b87f51dfba92ba73da94151aa3bc179e5fe88fc5dfb3038e860/seaborn-0.10.1-py3-none-any.whl
Requirement already satisfied: pyyaml in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from Keras==2.1.5->-r requirements.txt (line 7)) (5.3.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from matplotlib->-r requirements.txt (line 8)) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from matplotlib->-r requirements.txt (line 8)) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from matplotlib->-r requirements.txt (line 8)) (2.8.0)
Requirement already satisfied: cycler>=0.10 in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from matplotlib->-r requirements.txt (line 8)) (0.10.0)
Requirement already satisfied: pytz>=2011k in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from pandas->-r requirements.txt (line 10)) (2019.1)
Collecting PyQt5_sip<4.20,>=4.19.11 (from pyqt5==5.11.3->-r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/47/f7/b018d47f5665f149404f3ccf91ebc6d95123732edefadd5d3abcd0bf86e2/PyQt5_sip-4.19.19-cp36-cp36m-macosx_10_6_intel.whl
Collecting attrs>=17.4.0 (from pytest->-r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting importlib-metadata>=0.12; python_version < "3.8" (from pytest->-r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/8e/58/cdea07eb51fc2b906db0968a94700866fc46249bdc75cac23f9d13168929/importlib_metadata-1.7.0-py2.py3-none-any.whl
Collecting packaging (from pytest->-r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/46/19/c5ab91b1b05cfe63cccd5cfc971db9214c6dd6ced54e33c30d5af1d2bc43/packaging-20.4-py2.py3-none-any.whl
Collecting more-itertools>=4.0.0 (from pytest->-r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/ef/9b/6c35ec5483710492e21252465160ee508170159f7e0e2d6cd769022f52f6/more_itertools-8.4.0-py3-none-any.whl
Collecting py>=1.5.0 (from pytest->-r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/68/0f/41a43535b52a81e4f29e420a151032d26f08b62206840c48d14b70e53376/py-1.9.0-py2.py3-none-any.whl
Collecting wcwidth (from pytest->-r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/59/7c/e39aca596badaf1b78e8f547c807b04dae603a433d3e7a7e04d67f2ef3e5/wcwidth-0.2.5-py2.py3-none-any.whl
Collecting pluggy<1.0,>=0.12 (from pytest->-r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/a0/28/85c7aa31b80d150b772fbe4a229487bc6644da9ccb7e427dd8cc60cb8a62/pluggy-0.13.1-py2.py3-none-any.whl
Collecting coverage>=4.4 (from pytest-cov->-r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/be/07/cb3af47015e09befbb733cfde894f638d011a575ddacbea1ec54adc3ceba/coverage-5.2-cp36-cp36m-macosx_10_13_x86_64.whl
Requirement already satisfied: certifi>=2017.4.17 in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from requests->-r requirements.txt (line 15)) (2019.6.16)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from requests->-r requirements.txt (line 15)) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from requests->-r requirements.txt (line 15)) (3.0.4)
Collecting networkx>=2.0 (from scikit-image->-r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/41/8f/dd6a8e85946def36e4f2c69c84219af0fa5e832b018c970e92f2ad337e45/networkx-2.4-py3-none-any.whl
Collecting imageio>=2.3.0 (from scikit-image->-r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/6e/57/5d899fae74c1752f52869b613a8210a2480e1a69688e65df6cb26117d45d/imageio-2.9.0-py3-none-any.whl
Collecting tifffile>=2019.7.26 (from scikit-image->-r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/1e/ad/820377e280e3b0773b723b4b27b77a089443d2750f3ab8b8df2f9c849ed7/tifffile-2020.7.4-py3-none-any.whl
Collecting PyWavelets>=1.1.1 (from scikit-image->-r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/28/cd/0d96e765d793ae0e2fa291250ab98c27c0c574b0044c5a6ec3f6ae2afa91/PyWavelets-1.1.1-cp36-cp36m-macosx_10_9_x86_64.whl
Collecting tensorflow-tensorboard<1.6.0,>=1.5.0 (from tensorflow==1.5.0->-r requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/cc/fa/91c06952517b4f1bc075545b062a4112e30cebe558a6b962816cb33efa27/tensorflow_tensorboard-1.5.1-py3-none-any.whl
Collecting absl-py>=0.1.6 (from tensorflow==1.5.0->-r requirements.txt (line 20))
Requirement already satisfied: protobuf>=3.4.0 in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from tensorflow==1.5.0->-r requirements.txt (line 20)) (3.8.0)
Requirement already satisfied: wheel>=0.26 in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from tensorflow==1.5.0->-r requirements.txt (line 20)) (0.33.4)
Collecting future (from torch==1.5.0->-r requirements.txt (line 27))
Collecting cryptography>=1.3.4; extra == "secure" (from urllib3[secure]->-r requirements.txt (line 33))
  Using cached https://files.pythonhosted.org/packages/0f/ed/93c2217e732e75c21477c350b2d10a77e08fe2e0065c14644bdb110acfdd/cryptography-2.9.2-cp35-abi3-macosx_10_9_x86_64.whl
Collecting pyOpenSSL>=0.14; extra == "secure" (from urllib3[secure]->-r requirements.txt (line 33))
  Using cached https://files.pythonhosted.org/packages/9e/de/f8342b68fa9e981d348039954657bdf681b2ab93de27443be51865ffa310/pyOpenSSL-19.1.0-py2.py3-none-any.whl
Requirement already satisfied: pybids>=0.6.5 in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from bids-neuropoly>=0.2->ivadomed==2.0.2->-r requirements.txt (line 6)) (0.9.1)
Collecting onnx>=1.2.3 (from onnxruntime->ivadomed==2.0.2->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/31/ca/b41d3b5c3b72ad62c3b3ab164820c545fda1b1328268a1c3b61e34986535/onnx-1.7.0-cp36-cp36m-macosx_10_9_x86_64.whl
Collecting werkzeug>=0.11.15 (from tensorboard->ivadomed==2.0.2->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/cc/94/5f7079a0e00bd6863ef8f1da638721e9da21e5bacee597595b318f71d62e/Werkzeug-1.0.1-py2.py3-none-any.whl
Collecting google-auth-oauthlib<0.5,>=0.4.1 (from tensorboard->ivadomed==2.0.2->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/7b/b8/88def36e74bee9fce511c9519571f4e485e890093ab7442284f4ffaef60b/google_auth_oauthlib-0.4.1-py2.py3-none-any.whl
Collecting markdown>=2.6.8 (from tensorboard->ivadomed==2.0.2->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/a4/63/eaec2bd025ab48c754b55e8819af0f6a69e2b1e187611dd40cbbe101ee7f/Markdown-3.2.2-py3-none-any.whl
Collecting tensorboard-plugin-wit>=1.6.0 (from tensorboard->ivadomed==2.0.2->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/b6/85/5c5ac0a8c5efdfab916e9c6bc18963f6a6996a8a1e19ec4ad8c9ac9c623c/tensorboard_plugin_wit-1.7.0-py3-none-any.whl
Collecting google-auth<2,>=1.6.3 (from tensorboard->ivadomed==2.0.2->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/09/4b/a25adc25200de0f558749908ffa78eb8d4b8750775c9c944ffc0dc2e661c/google_auth-1.19.0-py2.py3-none-any.whl (91kB)
     |████████████████████████████████| 92kB 1.1MB/s 
Collecting grpcio>=1.24.3 (from tensorboard->ivadomed==2.0.2->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/c7/20/bbeff7c8895f27b781ce1624c21ef26b35507d1ef039c19f8d1c553fa42b/grpcio-1.30.0-cp36-cp36m-macosx_10_9_x86_64.whl
Requirement already satisfied: setuptools>=41.0.0 in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from tensorboard->ivadomed==2.0.2->-r requirements.txt (line 6)) (41.0.1)
Collecting zipp>=0.5 (from importlib-metadata>=0.12; python_version < "3.8"->pytest->-r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/b2/34/bfcb43cc0ba81f527bc4f40ef41ba2ff4080e047acb0586b56b3d017ace4/zipp-3.1.0-py3-none-any.whl
Collecting decorator>=4.3.0 (from networkx>=2.0->scikit-image->-r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Collecting html5lib==0.9999999 (from tensorflow-tensorboard<1.6.0,>=1.5.0->tensorflow==1.5.0->-r requirements.txt (line 20))
Collecting bleach==1.5.0 (from tensorflow-tensorboard<1.6.0,>=1.5.0->tensorflow==1.5.0->-r requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/33/70/86c5fec937ea4964184d4d6c4f0b9551564f821e1c3575907639036d9b90/bleach-1.5.0-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography>=1.3.4; extra == "secure"->urllib3[secure]->-r requirements.txt (line 33))
  Using cached https://files.pythonhosted.org/packages/d2/ff/0574f409c8ccabec9a93f0a01646f7e998f586c8e7099baee35710119df5/cffi-1.14.0-cp36-cp36m-macosx_10_9_x86_64.whl
Requirement already satisfied: bids-validator in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from pybids>=0.6.5->bids-neuropoly>=0.2->ivadomed==2.0.2->-r requirements.txt (line 6)) (1.2.4)
Requirement already satisfied: SQLAlchemy in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from pybids>=0.6.5->bids-neuropoly>=0.2->ivadomed==2.0.2->-r requirements.txt (line 6)) (1.3.5)
Requirement already satisfied: num2words in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from pybids>=0.6.5->bids-neuropoly>=0.2->ivadomed==2.0.2->-r requirements.txt (line 6)) (0.5.10)
Requirement already satisfied: patsy in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from pybids>=0.6.5->bids-neuropoly>=0.2->ivadomed==2.0.2->-r requirements.txt (line 6)) (0.5.1)
Collecting typing-extensions>=3.6.2.1 (from onnx>=1.2.3->onnxruntime->ivadomed==2.0.2->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/0c/0e/3f026d0645d699e7320b59952146d56ad7c374e9cd72cd16e7c74e657a0f/typing_extensions-3.7.4.2-py3-none-any.whl
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->ivadomed==2.0.2->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/a3/12/b92740d845ab62ea4edf04d2f4164d82532b5a0b03836d4d4e71c6f3d379/requests_oauthlib-1.3.0-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.2.1 (from google-auth<2,>=1.6.3->tensorboard->ivadomed==2.0.2->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/95/de/214830a981892a3e286c3794f41ae67a4495df1108c3da8a9f62159b9a9d/pyasn1_modules-0.2.8-py2.py3-none-any.whl
Collecting rsa<5,>=3.1.4; python_version >= "3" (from google-auth<2,>=1.6.3->tensorboard->ivadomed==2.0.2->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/1c/df/c3587a667d6b308fadc90b99e8bc8774788d033efcc70f4ecaae7fad144b/rsa-4.6-py3-none-any.whl
Collecting cachetools<5.0,>=2.0.0 (from google-auth<2,>=1.6.3->tensorboard->ivadomed==2.0.2->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/cd/5c/f3aa86b6d5482f3051b433c7616668a9b96fbe49a622210e2c9781938a5c/cachetools-4.1.1-py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=1.3.4; extra == "secure"->urllib3[secure]->-r requirements.txt (line 33))
  Using cached https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl
Requirement already satisfied: docopt>=0.6.2 in /Users/julien/miniconda3/envs/py3.6/lib/python3.6/site-packages (from num2words->pybids>=0.6.5->bids-neuropoly>=0.2->ivadomed==2.0.2->-r requirements.txt (line 6)) (0.6.2)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->ivadomed==2.0.2->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/05/57/ce2e7a8fa7c0afb54a0581b14a65b56e62b5759dbc98e80627142b8a3704/oauthlib-3.1.0-py2.py3-none-any.whl
Collecting pyasn1<0.5.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard->ivadomed==2.0.2->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl
Building wheels for collected packages: colored, requirements-parser
  Building wheel for colored (setup.py) ... done
  Stored in directory: /Users/julien/Library/Caches/pip/wheels/ec/10/5e/d17d5ef644e1051a753bd98f3796789ec39bc3337cd36637f3
  Building wheel for requirements-parser (setup.py) ... done
  Stored in directory: /Users/julien/Library/Caches/pip/wheels/c6/e5/ef/a12b26033eee476b7ebdd797528faa1765feae6e3b33a3954b
Successfully built colored requirements-parser
ERROR: dipy 1.1.1 has requirement nibabel>=3.0.0, but you'll have nibabel 2.4.1 which is incompatible.
ERROR: onnxruntime 1.3.0 has requirement numpy>=1.16.6, but you'll have numpy 1.16.4 which is incompatible.
Installing collected packages: colored, h5py, dipy, futures, bids-neuropoly, decorator, networkx, pillow, imageio, tifffile, PyWavelets, scikit-image, typing-extensions, onnx, onnxruntime, attrs, zipp, importlib-metadata, packaging, more-itertools, py, wcwidth, pluggy, pytest, future, torch, torchvision, absl-py, werkzeug, pyasn1, pyasn1-modules, rsa, cachetools, google-auth, oauthlib, requests-oauthlib, google-auth-oauthlib, markdown, tensorboard-plugin-wit, grpcio, tensorboard, seaborn, ivadomed, Keras, PyQt5-sip, pyqt5, coverage, pytest-cov, raven, requirements-parser, html5lib, bleach, tensorflow-tensorboard, tensorflow, xlwt, transforms3d, pycparser, cffi, cryptography, pyOpenSSL
  Found existing installation: bids-neuropoly 0.1
    Uninstalling bids-neuropoly-0.1:
      Successfully uninstalled bids-neuropoly-0.1
  Found existing installation: Pillow 6.0.0
    Uninstalling Pillow-6.0.0:
      Successfully uninstalled Pillow-6.0.0
  Found existing installation: torch 1.1.0.post2
    Uninstalling torch-1.1.0.post2:
      Successfully uninstalled torch-1.1.0.post2
  Found existing installation: torchvision 0.3.0
    Uninstalling torchvision-0.3.0:
      Successfully uninstalled torchvision-0.3.0
Successfully installed Keras-2.1.5 PyQt5-sip-4.19.19 PyWavelets-1.1.1 absl-py-0.9.0 attrs-19.3.0 bids-neuropoly-0.2 bleach-1.5.0 cachetools-4.1.1 cffi-1.14.0 colored-1.4.2 coverage-5.2 cryptography-2.9.2 decorator-4.4.2 dipy-1.1.1 future-0.18.2 futures-3.1.1 google-auth-1.19.0 google-auth-oauthlib-0.4.1 grpcio-1.30.0 h5py-2.10.0 html5lib-0.9999999 imageio-2.9.0 importlib-metadata-1.7.0 ivadomed-2.0.2 markdown-3.2.2 more-itertools-8.4.0 networkx-2.4 oauthlib-3.1.0 onnx-1.7.0 onnxruntime-1.3.0 packaging-20.4 pillow-7.2.0 pluggy-0.13.1 py-1.9.0 pyOpenSSL-19.1.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.20 pyqt5-5.11.3 pytest-5.4.3 pytest-cov-2.10.0 raven-6.10.0 requests-oauthlib-1.3.0 requirements-parser-0.2.0 rsa-4.6 scikit-image-0.17.2 seaborn-0.10.1 tensorboard-2.2.2 tensorboard-plugin-wit-1.7.0 tensorflow-1.5.0 tensorflow-tensorboard-1.5.1 tifffile-2020.7.4 torch-1.5.0 torchvision-0.6.0 transforms3d-0.3.1 typing-extensions-3.7.4.2 wcwidth-0.2.5 werkzeug-1.0.1 xlwt-1.3.0 zipp-3.1.0
~~~

</details>

With successful import:
~~~
(py3.6) julien-macbook:~/code/sct $ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import spinalcordtoolbox
>>> spinalcordtoolbox.__version__
'git-jv/2637-interleaved-dmri-moco-048c0a5c4703c48ad1aab52838bf4200f3666101'
~~~

@Drulex you mentioned in private communication you had issue with the pip install. Could you please document your error?

Note, maybe this suggestion would solve the tensorflow problem? https://github.com/neuropoly/spinalcordtoolbox/pull/2624

**Comment by Drulex** [comment]
> @Drulex you mentioned in private communication you had issue with the pip install. Could you please document your error?

```
[drulex@drupad-p1 ~]  $  python --version
Python 3.8.3
[drulex@drupad-p1 ~]  $  pip install --user tensorflow==1.5.0
ERROR: Could not find a version that satisfies the requirement tensorflow==1.5.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1)
ERROR: No matching distribution found for tensorflow==1.5.0
```

It is an environment problem and the same thing occurs on RTD when using the regular  installation via `pip install -r requirements.txt` (https://readthedocs.org/projects/spinalcordtoolbox/builds/11459453/).

Normally we should be able to work around by using the same conda venv in RTD, but I couldn't get it to work even after 1+ hour of messing around (their documentation isn't exactly perfect..).

**Comment by jcohenadad** [comment]
I see. Are you able to run `pip install --user tensorflow==1.15.2`, as per https://github.com/neuropoly/spinalcordtoolbox/pull/2624

**Comment by Drulex** [comment]
> I see. Are you able to run `pip install --user tensorflow==1.15.2`, as per #2624? If so, we could consider bump TF

No, I can only install after v2.2 (see previous pip output)

Related: https://github.com/tensorflow/tensorflow/issues/39380

I can try to set python to 3.6 on the RTD instead of using conda.

**Comment by Drulex** [comment]
> I can try to set python to 3.6 on the RTD instead of using conda.

Looks like that solved it. -> https://spinalcordtoolbox.readthedocs.io/en/aj-update-api-documentation/

**Comment by Drulex** [comment]
> > I can try to set python to 3.6 on the RTD instead of using conda.
> 
> Looks like that solved it. -> https://spinalcordtoolbox.readthedocs.io/en/aj-update-api-documentation/

At least partly... https://spinalcordtoolbox.readthedocs.io/en/aj-update-api-documentation/command-line.html

**Comment by jcohenadad** [comment]
> At least partly... https://spinalcordtoolbox.readthedocs.io/en/aj-update-api-documentation/command-line.html

yeah i've seen that, but that should be manageable (not a dealbreaker, right?)

**Comment by Drulex** [comment]
> yeah i've seen that, but that should be manageable (not a dealbreaker, right?)

I'll investigate. It would be nice to keep the scripts outputs in the docs, one less thing to maintain.

**Comment by jcohenadad** [comment]
> > yeah i've seen that, but that should be manageable (not a dealbreaker, right?)
> 
> I'll investigate. It would be nice to keep the scripts outputs in the docs, one less thing to maintain.

could we reproduce what's done here: https://ivadomed.org/en/latest/scripts.html ?

**Comment by Drulex** [comment]
@jcohenadad Even though the docs still have some issues (see https://github.com/neuropoly/spinalcordtoolbox/pull/2781#issuecomment-658860896), I propose to merge now to avoid potential conflicts.

**Pull request merged**
