### PR TITLE
fsleyes: allow user to specify output folder

### LINKED ISSUE #2579: fsleyes integration saves outputs to directory from which fsleyes is opened
### Description

When run `sct_deepseg_sc` or `sct_deepseg_gm` from FSLeyes integration, segmentations are saved into directory where I have FSLeyes opened from, not to directory where the image is from. 

### Steps to Reproduce

0.  `sct_check_dependencies` output: 

> SCT info:
> version: git-master-9d0cdbc7df413ee68da3ec254b8566d379511e3c
> path: /usr/local/sct
> OS: osx (Darwin-18.7.0-x86_64-i386-64bit)`

1. Go to any directory in the terminal (e.g. /Users/user/Documents) and type `fsleyes`

2. Open some image (e.g. /Users/user/Documents/ExampleData/t1w.nii.gz)

3. Run `sct_deepseg_sc` from FSLeyes integration

**Expected behavior:** <What you expect to happen>
It makes more sense to me, if final segmentation would be saved in same directory as input image (i.e. /Users/user/Documents/ExampleData/).
**Actual behavior:** <What actually happens>
Final segmentation is saved to directory where the FSLeyes is opened from (i.e.  /Users/user/Documents/).

### PR DESCRIPTION
**Pull request by Drulex**
Closes #2579 

Implement: https://github.com/neuropoly/spinalcordtoolbox/issues/2579#issuecomment-705004337

### CODE REVIEW

**Comment by Drulex** [comment]
Do you mind giving the updated GUI a try @valosekj ?

**Comment by valosekj** [comment]
> Do you mind giving the updated GUI a try @valosekj ?

Sure! But now I am somehow struggling with running the `sct_plugin.py` script from fsleyes. I start fsleyes from terminal, then i do `File/Run script` and then I get invalid syntax error on line 110:

https://github.com/neuropoly/spinalcordtoolbox/blob/bacf0325eaafa71e3f6cfa4be83f0996c903dd3b/contrib/fsl_integration/sct_plugin.py#L110

It is probably related to [f-strings ](https://www.geeksforgeeks.org/formatted-string-literals-f-strings-python/) formatting. This formatting is available from Python3.6, right? It is possible that fsleyes tries to run the `sct_plugin.py` by older version of python?
How do you run fsleyes and the plugin? Thanks!

**Comment by jcohenadad** [comment]
@valosekj i just tried and it works fine. What version/os are you on? Me:
- OS: macOs 10.15.7
- fsleyes/FSLeyes version 0.31.0+build0

**Comment by valosekj** [comment]
macOS Catalina 10.15.7
fsleyes/FSLeyes version 0.27.3+build0

I am going to update FSLeyes and I will see.

**Comment by Drulex** [comment]
> It is probably related to [f-strings ](https://www.geeksforgeeks.org/formatted-string-literals-f-strings-python/) formatting. This formatting is available from Python3.6, right?

Yes it is a feature from 3.6. Considering that the python version we bundle with `install_sct` is 3.6 I assumed it was ok.

**Comment by valosekj** [comment]
I have updated FSLeyes to 0.34.2 and now I am able to run `sct_plugin.py` but when I click on `Run` button e.g. for `sct_propseg` I get:
image
Probably some other problem with my environment. I will try to figure out what is reason.

**Comment by Drulex** [comment]
> Probably some other problem with my environment. I will try to figure out what is reason.

I was running `0.33`, but I upgraded to `0.34.2` and confirm that the feature still works as expected (python 3.8.5 on Linux 5.4)

**Comment by Drulex** [comment]
@valosekj I think if you run `fsleyes` from the conda environment it will pickup the 3.6 version.

```bash
source $SCT_DIR/python/etc/profile.d/conda.sh && conda activate venv_sct && fsleyes
```

**Comment by valosekj** [comment]
> @valosekj I think if you run `fsleyes` from the conda environment it will pickup the 3.6 version.
> 
> ```shell
> source $SCT_DIR/python/etc/profile.d/conda.sh && conda activate venv_sct && fsleyes
> ```

I was running fsleyes in conda environment in https://github.com/neuropoly/spinalcordtoolbox/pull/2941#issuecomment-705156390. Strange. It will be probably something related to MacOS Catalina - https://stackoverflow.com/a/59150657. I am digging into it.

**Comment by Drulex** [comment]
> I was running fsleyes in conda environment in [#2941 (comment)](https://github.com/neuropoly/spinalcordtoolbox/pull/2941#issuecomment-705156390). Strange. It will be probably something related to MacOS Catalina - https://stackoverflow.com/a/59150657. I am digging into it.

Ah ok. That's a weird one.. good luck. :grimacing:

**Comment by Drulex** [comment]
Any luck @valosekj ?

**Comment by valosekj** [comment]
> Any luck @valosekj ?

Unfortunatelly not. But I think, PR can me merger, because it is working for you and also for Julien who has MacOS. It looks that my issue is probably caused by some problem related to my computer and SW versions.

**Comment by Drulex** [comment]
> Unfortunatelly not. But I think, PR can me merger, because it is working for you and also for Julien who has MacOS. It looks that my issue is probably caused by some problem related to my computer and SW versions.

@jcohenadad ok with the changes to be merged?

**Review by jcohenadad — APPROVED** [review]

**Pull request merged**
