### PR TITLE
Change Error type so program doesn't quit when labels are too high

### LINKED ISSUE #2607: ValueError thrown if label value is too high
### Description

When trying to run the function in lumbar FOV, if specifying a starting point at label =19 (corresponding to T11-T12 disc), the code crashes with a ValueError. The reason being that the labels on the template are not going high enough.

### Steps to Reproduce

~~~
# here we use sct_testing_data/t2.nii.gz image, even if it is centered in the cervical cord, but the crash is independent from the image content anyways.
cd sct_testing_data/t2
sct_label_vertebrae -i t2.nii.gz -s t2_seg.nii.gz -c t2 -initz 25,19
...
Current disc: 19 (z=50). Direction: superior
.. Peak found: z=0 (correlation = 0.24951264940910967)
.. Switching to inferior direction.
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_label_vertebrae.py", line 427, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_label_vertebrae.py", line 372, in main
    verbose=verbose, path_template=path_template, path_output=path_output, scale_dist=scale_dist)
  File "/Users/julien/code/sct/spinalcordtoolbox/vertebrae/core.py", line 222, in vertebral_detection
    current_z = init_disc[0] - list_distance[list_disc_value_template.index(current_disc)]
ValueError: 20 is not in list
~~~

### Possible solution

Increase the number of labels from the template.

### PR DESCRIPTION
**Pull request by lrouhier**
#### GitHub

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [x] I've assigned a reviewer

#### PR contents

- [x] I've consulted [SCT's internal developer documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki) to ensure my contribution is in line with any relevant design decisions
- [x] I've added [relevant tests](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Tests) for my contribution
- [ ] I've updated the [relevant documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description
In `sct_label_vertebrae`, there is an exception designed for very high-value labels to provide the user the opportunity to label the lumbar part of the vertebrae. This is needed because our PAM50 template only has labels from 1 to 20. 
This PR changes the error type for the exception. It is needed because the `try` statement throws a `ValueError`.

## Linked issues
fix #2607

### CODE REVIEW

**Review by joshuacwnewton — DISMISSED** [review]

**Review by joshuacwnewton — COMMENTED** [review]
I'm wondering if changes like this should be tested. It would be a somewhat time-consuming test (because `t2_seg.nii.gz` must be generated first) just to check a small error. 

But, maybe that means we should include a `t2_seg.nii.gz` file inside `sct_testing_data`. That way, we could more easily write a quick test for the `vertebral_detection` function to ensure that the warning is raised instead of an error. 

What do you think, @lrouhier?

**Comment by joshuacwnewton** [comment]
Ah, my apologies, there already are segmented spinal cord images in `sct_testing_data`. They're just named differently than `t2_seg.nii.gz`.

In that case, I think it would be good to write a test for this.

**Comment by lrouhier** [comment]
I'll get on it.

**Comment by lrouhier** [comment]
@joshuacwnewton done in 84e9ece

**Review by joshuacwnewton — APPROVED** [review]
Thanks much @lrouhier!

**Pull request merged**
