### PR TITLE
Fix docs API section rendering.

### PR DESCRIPTION
**Pull request by Drulex**
This fixes the rendering of the `API` section in the rst docs: https://spinalcordtoolbox.com/en/aj-fix-docs-api-render/dev_section/api.html

### CODE REVIEW

**Comment by jcohenadad** [comment]
it doesn't seem to render:

image

**Comment by Drulex** [comment]
same link:

image

**Comment by Drulex** [comment]
ahhh I broke it.  2m

**Comment by Drulex** [comment]
Should be ok now @jcohenadad

**Comment by jcohenadad** [comment]
@Drulex should we merge this PR, and then move to this other PR (because we need to do something with this version.txt file): https://github.com/neuropoly/spinalcordtoolbox/pull/2833

**Comment by Drulex** [comment]
> @Drulex should we merge this PR, and then move to this other PR (because we need to do something with this version.txt file): #2833

Sure, but I suspect that the version problem is part of a bigger effort to properly package the project.

**Pull request merged**
