### PR TITLE
[REFACTOR] Spacing around the operators.

### PR DESCRIPTION
**Pull request by peristeri**

### CODE REVIEW

**Comment by jcohenadad** [comment]
i don't have a strong opinion between PO's and GP's approach, but yes, standard would be nice. 
@peristeri: if PEP does not require space around operators (according to PO), do you have other incentive to do so?

BTW: i will not be able to review these changes (not humanly possible ;-) )-- i'd rather make sure our tests cover any possible bug related to these changes, and if not, i'd like the tests to be implemented.

**Comment by peristeri** [comment]
@poquirion you are right, it is optional. I wanted to introduce tools like flake8 and wanted to avoid too many exceptions. @jcohenadad, this PR request only introduces spaces, nothing more.

**Comment by jcohenadad** [comment]
@peristeri can you please update the wiki to explicit new standard wrt. space
thanks

**Comment by peristeri** [comment]
@jcohenadad will do.

**Pull request merged**
