### PR TITLE
Adapt concat and apply transfo to work on 2d images

### LINKED ISSUE #1419: concat and apply transfo not working on 2d images
### Prerequisites

* [x] Did you check past issues for similar issue(s) ?
* [x] Can you reproduce the issue with any of the files found in `sct_testing_data` ?
* [x] If you are using a development environment, is your environment updated ?

### Description
Even on 2D images the script uses 
`isct_ComposeMultiTransform 3`

### Steps to Reproduce

1. data here:
Django/folder_shared/sct_issue/20170725_harris
2. `sct_concat_transfo -d warp_sym_510to515.nii.gz -w warp_sym_510to515.nii.gz,warp_sym_515to520.nii.gz -o warp_510to520.nii.gz`

**Expected behavior:**

output is 3.4e+38 everywhere

**Actual behavior:**

What actually happens

**Reproduces how often:**

What percentage of the time does it reproduce?

### State of spinalcordtoolbox

Include the first 3 lines printed when running the command.
Example:

```
$ sct_qc

--
Spinal Cord Toolbox (github-templates/a63f51caa065655ad1b926901adf7ef144d2cc2b)
Running /Users/geper/devel/spinalcordtoolbox/scripts/sct_qc.py

...
```

### Additional Information

Screen-shots, error logs and output files.

### PR DESCRIPTION
**Pull request by SaraDupont**
### Requirements
Allow `sct_concat_transfo` to work on 2D warping fields

### Description of the Change
When warping field is 2D, use `isct_ComposeMultiTransform` with dimensionality at 2 instead of 3. 
Only the first warping field of the list is check because we assume all the warping fields are in the same dimensionality (i.e. 2D or 3D) to avoid opening them all. 

### Applicable Issues

Fixes #1419

### CODE REVIEW

**Comment by tanguyduval** [comment]
👍  Thx! Just need to do the same for sct_apply_transfo

**Comment by jcohenadad** [comment]
i've modified issue #1419 and this PR to include `sct_apply_transfo` as well.

**Comment by jcohenadad** [comment]
i've also changed card back to "WORK IN PROGRESS" as Travis crashes. Also please test this PR with batch_processing to make sure it runs smoothly. This PR seems sensitive. Thanks.

**Comment by SaraDupont** [comment]
Indeed, it seems more sensitive than I thought it was. I'll run extra checks !

**Comment by SaraDupont** [comment]
This should be fixed now, however since the tests on master are failing, here too, but the tests of `sct_concat_transfo` and `sct_apply_transfo` are passing.

**Comment by jcohenadad** [comment]
@SaraDupont: could you please run a `batch_processing.sh -nodisplay` and copy/paste results here (with comparison with results from master). Thanks

**Comment by SaraDupont** [comment]
Results on Master: 
```Results:
ID, label name [total fractional volume of the label in number of voxels]:    metric value +/- metric STDEV within label
4, WM left lateral corticospinal tract [73.51]:    0.697803707903 +/- 0.156472189285
5, WM right lateral corticospinal tract [74.01]:    0.741739108652 +/- 0.132849278874

Saving results in: fa_in_cst.txt ...
	Done.
Ended at: 31.07.2017_

t2/CSA:   77.336978, 1.698544
mt/MTR:   51, white matter, 2927.144075, 21.948131, 0.000000
mt/CSA_GM:   18.523568, 1.645447
mt/CSA_WM:   60.838360, 2.460520
dmri/FA:  4, WM left lateral corticospinal tract, 73.509947, 0.697804, 0.156472
dmri/FA:  5, WM right lateral corticospinal tract, 74.011204, 0.741739, 0.132849

Running /Users/saradupont/Neuropoly/code/spinalcordtoolbox/scripts/sct_qc.py -folder /Users/saradupont/qc_batch_processing
Check folder existence...
QC viewer started on:
http://127.0.0.1:8888
Copy and paste the address into your web browser
Press "Ctrl" + "C" to stop sct_qc
```

**Pull request merged**
