### PR TITLE
Conversion issue for float32 images with large dynamic

### LINKED ISSUE #1449: Conversion issue for float32 images with large dynamic
### Description

For certain types of images with float32 and large dynamic, the int16 conversion is inadapted, resulting in failing of OptiC algorithm. 

### Steps to Reproduce

Data: **sct_testing/large/ucl_2017-grussu_01/t2s**
~~~
# this will fail:
sct_get_centerline -i t2s.nii.gz -c t2s
# this will work, after rescaling the image:
sct_maths -i t2s.nii.gz -div 100000 -o t2s_scaled.nii.gz
sct_get_centerline -i t2s_scaled.nii.gz -c t2s
~~~

### State of spinalcordtoolbox

v3.0.7

### Additional Information

Conversion to int16:
screen shot 2017-09-09 at 14 57 36

Conversion to int16 after rescaling:
screen shot 2017-09-09 at 14 57 40

### PR DESCRIPTION
**Pull request by charleygros**
### Description of the Change

- [x] Apply a scaling in case of float32 and large dynamic images
- [x] Remove the file "_int16_RPI" at the end and output a roi file only when needed

### Applicable Issues

Fixes #1449

### CODE REVIEW

**Comment by charleygros** [comment]
Totally agree with that !

I can work on a scaling using percentile.
Not sure to understand what you mean by "normalize before..". Could you please explain?

**Comment by jcohenadad** [comment]
How does OptiC work? Does it require images to be scaled (in terms of pixel values) in a particular way? does OptiC re-scale the dynamic of the input image? Any knowledge would be useful to adopt the best strategy for pre-preprocessing functions.

**Comment by jcohenadad** [comment]
maybe one simple option would be to normalize the input image according to:
- min --> -32768
- max --> +32767
and then convert to int16.

Just a tought... will probably require some testing...

**Comment by charleygros** [comment]
OptiC does not require a specific voxel value range: the only requirement is the conversion to int16 as input --> required by the opencv functions integrated in the algorithm

I agree that a scaling using percentiles before conversion to int16 should adress the issue.

I will test it

**Comment by jcohenadad** [comment]
thinking of refactoring changeType@msct_image so that images are intensity-rescaled before conversion, using scikit-image exposure:
http://scikit-image.org/docs/dev/user_guide/data_types.html#rescaling-intensity-values
any thoughts?

**Comment by benjamindeleener** [comment]
I think it is a good idea to use scikit-image for this. They probably manage the boundaries better that what we've been using so far.

**Comment by jcohenadad** [comment]
actually it doesn't work (i.e., they don't touch the boundaries but clip).
I'm implementing a rescaling based on the min/max and output type

**Comment by jcohenadad** [comment]
@charleygros: what is the best way to compare results of `sct_get_centerline` between this PR and the current master version?

**Comment by charleygros** [comment]
A quick test could be to run the test function related to sct_get_centerline

(If you would like a more extensive validation, I could run it across subjects involved in OptiC manuscript and compare the results!)

**Comment by jcohenadad** [comment]
i was thinking more of an extensive test-- if you have trouble connecting to the vpn, could you please let me know the best procedure?
Or can I simply use sct_testing/large?

**Comment by jcohenadad** [comment]
is there any way to test all contrasts in a single test or should i run t2, t2s and t1 separately?

**Comment by benjamindeleener** [comment]
From my knowledge, `sct_pipeline` does not allow to run the testing on multiple contrast at the same time. It would be good to have an option to do so, but we would lose the results info separated by contrast. Need to be discussed.

**Comment by jcohenadad** [comment]
is the appropriate test `test_sct_get_centerline`?
Because it currently fails:
https://github.com/neuropoly/spinalcordtoolbox/issues/1452

**Comment by jcohenadad** [comment]
the test for get_centerline will be addressed in PR #1453

**Pull request merged**
