### PR TITLE
Adding rules for in-segmentation errors

### PR DESCRIPTION
**Pull request by benjamindeleener**
Fixing issue #1109

### CODE REVIEW

**Comment by benjamindeleener** [comment]
```
Command: sct_propseg -i t1/t1.nii.gz -c t1
Dataset: /Volumes/data_raid/data_shared/sct_testing/large/
```

Branch `master`:
```
Duration: 948s
Passed: 19/104
Crashed: 0/104
Mean: {'dice_segmentation': 0.6654290104106925, 'duration [s]': 49.302188210762466}
STD: {'dice_segmentation': 0.28345675950310223, 'duration [s]': 21.601589883353494}
```

Branch `bdl_issue1109`:
```
Duration: 890s
Passed: 22/104
Crashed: 0/104
Mean: {'dice_segmentation': 0.6806839305569934, 'duration [s]': 46.17467857553409}
STD: {'dice_segmentation': 0.2849778960362751, 'duration [s]': 20.130472328107732}
```

```
Command: sct_propseg -i t2/t2.nii.gz -c t2
Dataset: /Volumes/data_raid/data_shared/sct_testing/large/
```

Branch `master`:
```
Duration: 1184s
Passed: 89/201
Crashed: 33/201
Mean: {'dice_segmentation': 0.7481998235241972, 'duration [s]': 39.712681209757214}
STD: {'dice_segmentation': 0.3428954806394332, 'duration [s]': 14.97347618773706}
```

Branch `bdl_issue1109`:
```
Duration: 1220s
Passed: 91/201
Crashed: 33/201
Mean: {'dice_segmentation': 0.7505215534976936, 'duration [s]': 41.08509090684709}
STD: {'dice_segmentation': 0.3412622611137723, 'duration [s]': 15.688839628699897}
```

**Comment by jcohenadad** [comment]
where do the 33/201 crashes come from on the T2 images?

**Comment by benjamindeleener** [comment]
@jcohenadad It crashes when no spinal cord has been detected.

**Comment by jcohenadad** [comment]
wouldn't it be fairly straightforward to detect the crash (with a try/except) and exit the program with exit status 0 and a printout that tells the user that "spinal cord could not be detected, please do a manual initialization using -init-mask viewer, or -init-centerline viewer"?

**Pull request merged**
