### PR TITLE
sct_graymatter_segmentation re-coding

### PR DESCRIPTION
**Pull request by SaraDupont**
New code for sct_segment_graymatter, msct_multiatlas_seg, msct_gmseg_utils. New features:

- Registration performed with sct_register_multimodal --> totally modular, with the same type of parameters : "step=1,type=seg,..."
- Model computed with scikit-learn: choice between pca or isomap
- Data pre-processing performed with interpolation to a reference image (=combines resampling and cropping to a square centered on SC)
- New data added to the model (now 80 subjects in total): 
     - training data from GM seg challenge (40 subjects)
     - Toronto HC (3 subject)
     - Montreal (22 subjects)
     - AMU (15 subjects)

--> Need to update the GM model as we merge this branch to master

### CODE REVIEW

**Comment by jcohenadad** [comment]
issue of WM/GM shape:
batch_processing.sh
Spinal Cord Toolbox (version dev-d4689cf19a5e2f74237afbddcfbe2bdd8e80d238)
output_acjyhh

**Comment by jcohenadad** [comment]
data: **batch_processing.sh**
Spinal Cord Toolbox (version dev-4564fa005de7f5167c08271aa8ace1914ab97f3c)
~~~
t2/CSA:   /Users/julien/sct_example_data/t2/t2_seg.nii.gz, 76.650632, 2.337186
mt/MTR:   51, white matter, 373.916628, 33.555483, 0.000000
mt/mt_cst_dorsal_csa_mean.txt: 17.171928, 1.068900
dmri/FA:  4, WM left lateral corticospinal tract, 23.947482, 0.689269, 0.000000
dmri/FA:  5, WM right lateral corticospinal tract, 22.141698, 0.767769, 0.000000
~~~

**Comment by SaraDupont** [comment]
**Data model: 37 subjects (22 errsm, 15 amu)
Code version: OLD
Results:**
```
         subject   dice_gm   dice_wm  duration_[s]  hausdorff  med_dist  status
0   d_sp_pain_01  0.693429  0.893351    591.261113   1.164313  0.334771       0
1   d_sp_pain_02  0.748480  0.913317    616.970800   1.115883  0.309686       0
2   d_sp_pain_03  0.721351  0.904814    609.494194   0.879117  0.309247       0
3   d_sp_pain_04  0.529599  0.849851    610.984031   1.505534  0.472094      99
4   d_sp_pain_06  0.645637  0.889847    611.157140   1.325373  0.383786       0
5   d_sp_pain_07  0.665559  0.885077    616.895152   1.284236  0.402083       0
6   d_sp_pain_08  0.732272  0.910212    614.024048   1.044911  0.316248       0
7   d_sp_pain_09  0.747048  0.909203    606.896574   1.013946  0.273747       0
8   d_sp_pain_10  0.704484  0.910674    566.046051   1.180044  0.326382       0
9   d_sp_pain_11  0.650336  0.878465    582.626944   1.184886  0.398884       0
10  d_sp_pain_12  0.760579  0.914281    584.791747   1.063840  0.288644       0
11  d_sp_pain_13  0.723517  0.909846    570.842019   1.028614  0.296158       0
12  d_sp_pain_14  0.755304  0.918920    589.330575   1.123873  0.299266       0
13  d_sp_pain_15  0.699658  0.907874    569.365407   1.016366  0.351108       0
14  d_sp_pain_17  0.717036  0.913344    583.117593   1.294511  0.329411       0
15  d_sp_pain_18  0.718574  0.916147    577.479766   0.777167  0.293401       0
16  d_sp_pain_19  0.703583  0.905682    565.557882   1.263401  0.348858       0
17  d_sp_pain_21  0.722996  0.921120    561.542683   1.046294  0.324970       0
18  d_sp_pain_22  0.575126  0.889451    569.726796   1.276092  0.393592       0
19  d_sp_pain_23  0.752446  0.919256    556.897240   1.089579  0.298957       0
20  d_sp_pain_24  0.770120  0.892765    559.509942   0.929591  0.293833       0
21  d_sp_pain_25  0.801927  0.925660    557.954541   0.914864  0.269574       0
22  d_sp_pain_28  0.731116  0.908441    564.047362   0.976206  0.296698       0
23  d_sp_pain_29  0.555430  0.871873    562.342208   1.561422  0.500179      99
24          Mean  0.701067  0.902478    583.285909   1.127503  0.337982     NaN
25           STD  0.067797  0.017935     21.328527   0.188420  0.059612     NaN
```

**Data model: 37 subjects (22 errsm, 15 amu)
Code version: NEW
Results:**
```
         subject   dice_gm   dice_wm  duration_[s]  hausdorff  med_dist  status
0   d_sp_pain_01  0.720291  0.911643    264.489288   1.130637  0.303372       0
1   d_sp_pain_02  0.760931  0.933223    266.472983   1.053090  0.245524       0
2   d_sp_pain_03  0.758723  0.936385    264.996881   0.953960  0.291160       0
3   d_sp_pain_04  0.594734  0.897543    264.341024   1.300660  0.410719       0
4   d_sp_pain_06  0.717876  0.923516    263.908264   1.222405  0.323345       0
5   d_sp_pain_07  0.688163  0.909570    270.111237   1.373068  0.358413       0
6   d_sp_pain_08  0.722131  0.919092    266.082412   1.083351  0.322636       0
7   d_sp_pain_09  0.717146  0.927732    261.726619   1.372249  0.331811       0
8   d_sp_pain_10  0.690008  0.928546    257.775921   1.234862  0.320416       0
9   d_sp_pain_11  0.678800  0.908508    270.713776   1.026795  0.369412       0
10  d_sp_pain_12  0.725997  0.920916    262.951316   1.184762  0.332585       0
11  d_sp_pain_13  0.757926  0.935034    269.807014   0.942837  0.281431       0
12  d_sp_pain_14  0.753735  0.940785    262.163614   0.934243  0.269990       0
13  d_sp_pain_15  0.729683  0.932690    271.027243   1.061960  0.287151       0
14  d_sp_pain_17  0.749209  0.927417    262.081056   1.348255  0.308503       0
15  d_sp_pain_18  0.711177  0.934540    264.575663   1.038893  0.264721       0
16  d_sp_pain_19  0.714848  0.929238    268.710457   1.007980  0.339369       0
17  d_sp_pain_21  0.753931  0.940779    272.675691   0.990738  0.275871       0
18  d_sp_pain_22  0.670949  0.921850    268.148744   0.989505  0.320112       0
19  d_sp_pain_23  0.779652  0.943784    273.049035   1.006545  0.250407       0
20  d_sp_pain_24  0.747425  0.940472    265.509731   1.014360  0.263394       0
21  d_sp_pain_25  0.771630  0.942907    273.980669   0.838453  0.296619       0
22  d_sp_pain_28  0.758725  0.927600    270.761759   1.012888  0.267995       0
23  d_sp_pain_29  0.613076  0.907841    273.069195   1.279799  0.438648       0
24          Mean  0.720282  0.926734    267.047066   1.100096  0.311400     NaN
25           STD  0.046449  0.012577      4.340486   0.152572  0.048138     NaN
```

**Comment by SaraDupont** [comment]
Data model: **37 subjects (22 errsm, 15 amu)**
Code version: NEW
Results:
```
         subject   dice_gm   dice_wm  duration_[s]  hausdorff  med_dist  status
0   d_sp_pain_01  0.720291  0.911643    264.489288   1.130637  0.303372       0
1   d_sp_pain_02  0.760931  0.933223    266.472983   1.053090  0.245524       0
2   d_sp_pain_03  0.758723  0.936385    264.996881   0.953960  0.291160       0
3   d_sp_pain_04  0.594734  0.897543    264.341024   1.300660  0.410719       0
4   d_sp_pain_06  0.717876  0.923516    263.908264   1.222405  0.323345       0
5   d_sp_pain_07  0.688163  0.909570    270.111237   1.373068  0.358413       0
6   d_sp_pain_08  0.722131  0.919092    266.082412   1.083351  0.322636       0
7   d_sp_pain_09  0.717146  0.927732    261.726619   1.372249  0.331811       0
8   d_sp_pain_10  0.690008  0.928546    257.775921   1.234862  0.320416       0
9   d_sp_pain_11  0.678800  0.908508    270.713776   1.026795  0.369412       0
10  d_sp_pain_12  0.725997  0.920916    262.951316   1.184762  0.332585       0
11  d_sp_pain_13  0.757926  0.935034    269.807014   0.942837  0.281431       0
12  d_sp_pain_14  0.753735  0.940785    262.163614   0.934243  0.269990       0
13  d_sp_pain_15  0.729683  0.932690    271.027243   1.061960  0.287151       0
14  d_sp_pain_17  0.749209  0.927417    262.081056   1.348255  0.308503       0
15  d_sp_pain_18  0.711177  0.934540    264.575663   1.038893  0.264721       0
16  d_sp_pain_19  0.714848  0.929238    268.710457   1.007980  0.339369       0
17  d_sp_pain_21  0.753931  0.940779    272.675691   0.990738  0.275871       0
18  d_sp_pain_22  0.670949  0.921850    268.148744   0.989505  0.320112       0
19  d_sp_pain_23  0.779652  0.943784    273.049035   1.006545  0.250407       0
20  d_sp_pain_24  0.747425  0.940472    265.509731   1.014360  0.263394       0
21  d_sp_pain_25  0.771630  0.942907    273.980669   0.838453  0.296619       0
22  d_sp_pain_28  0.758725  0.927600    270.761759   1.012888  0.267995       0
23  d_sp_pain_29  0.613076  0.907841    273.069195   1.279799  0.438648       0
24          Mean  0.720282  0.926734    267.047066   1.100096  0.311400     NaN
25           STD  0.046449  0.012577      4.340486   0.152572  0.048138     NaN
```
Average value with the same testing subjects as below:

```
        dice_gm    dice_wm    duration_[s]  hausdorff  med_dist 
Mean    0.72585    0.93157    267.67407     1.07006    0.30190
STD     0.03388    0.00785    4.29003       0.11501    0.03415
```


Data model: **80 subjects (22 errsm, 15 amu, 40 GMchallenge, 3 Toronto)**
Code version: NEW
Results:
```
         subject   dice_gm   dice_wm  duration_[s]  hausdorff  med_dist  status
0   d_sp_pain_06  0.691252  0.914350    346.589980   1.652309  0.334204      99
1   d_sp_pain_10  0.699877  0.924572    335.205595   0.854216  0.282514       0
2   d_sp_pain_14  0.744373  0.934931    349.050411   1.266680  0.309065       0
3   d_sp_pain_15  0.716673  0.921241    346.996215   1.338044  0.341264       0
4   d_sp_pain_17  0.696911  0.917997    345.974970   1.531640  0.370377      99
5   d_sp_pain_18  0.762917  0.944356    342.943484   1.252222  0.300000       0
6   d_sp_pain_19  0.700768  0.922620    347.111356   1.298972  0.342549       0
7   d_sp_pain_21  0.707072  0.929584    345.485278   1.331689  0.355556       0
8   d_sp_pain_22  0.640501  0.909010    348.961270   1.140129  0.342368       0
9   d_sp_pain_23  0.762465  0.934424    349.184621   1.147053  0.317203       0
10  d_sp_pain_24  0.689414  0.918908    341.827983   1.130077  0.321010       0
11  d_sp_pain_25  0.792425  0.942449    349.401185   1.062186  0.296700       0
12  d_sp_pain_28  0.770519  0.923603    223.759132   1.353293  0.294140       0
13  d_sp_pain_29  0.528306  0.886036    219.868483   1.436722  0.507404       0
14          Mean  0.707391  0.923149    328.025712   1.271088  0.336740     NaN
15           STD  0.065707  0.014767     45.161957   0.201257  0.055336     NaN

```

**Comment by SaraDupont** [comment]
Results after merging master:
  - centermass_rot have been updated
  - bug with WM shape in bash_processing have been fixed: bug was related to the interpolation of the image to segment to the model space in the preprocessing, the rotation in the image header wasn't correctly accounted for.

```
Results for "sct_segment_graymatter -i t2star/t2star.nii.gz -s t2star/t2star_seg.nii.gz -ref t2star/t2star_manual_gmseg.nii.gz -vertfile t2star/MNI-Poly-AMU_level.nii.gz -model /Users/saradupont/Neuropoly/data/2016-09-09-gmseg_model_80sub":
Dataset: /Users/saradupont/Neuropoly/data/2016-09-10_pain_data/not_used_in_model/
Passed: 14/14
Total duration: 699s

         subject   dice_gm   dice_wm  duration_[s]  hausdorff  med_dist  status
0   d_sp_pain_06  0.678796  0.914902    411.236435   1.597281  0.344126       0
1   d_sp_pain_10  0.731936  0.927800    401.017748   0.850637  0.270711       0
2   d_sp_pain_14  0.748942  0.938830    413.647001   1.213291  0.290860       0
3   d_sp_pain_15  0.704760  0.920075    404.899128   1.303371  0.325766       0
4   d_sp_pain_17  0.704390  0.927204    412.883730   1.583511  0.358521       0
5   d_sp_pain_18  0.743537  0.934191    404.246385   1.367673  0.326055       0
6   d_sp_pain_19  0.696549  0.921770    408.257181   1.280874  0.343527       0
7   d_sp_pain_21  0.744530  0.936909    407.962723   1.398833  0.334197       0
8   d_sp_pain_22  0.610474  0.903803    290.037083   1.373252  0.423055       0
9   d_sp_pain_23  0.752594  0.937193    288.225876   1.354351  0.307530       0
10  d_sp_pain_24  0.717128  0.923216    286.030066   1.128713  0.327088       0
11  d_sp_pain_25  0.768177  0.941247    289.270463   1.233291  0.315349       0
12  d_sp_pain_28  0.768439  0.931980    289.388985   1.379388  0.321806       0
13  d_sp_pain_29  0.523400  0.897623    284.224551   1.614184  0.520038       0
14          Mean  0.706690  0.925482    356.523383   1.334189  0.343473     NaN
15           STD  0.067233  0.013089     61.808850   0.200707  0.061595     NaN
Status: 0: Passed | 1: Crashed | 99: Failed | 200: File(s) missing
 ```

**Comment by SaraDupont** [comment]
Same test with re-computed model:
```
Results for "sct_segment_graymatter -i t2star/t2star.nii.gz -s t2star/t2star_seg.nii.gz -ref t2star/t2star_manual_gmseg.nii.gz -vertfile t2star/MNI-Poly-AMU_level.nii.gz -model /Users/saradupont/Neuropoly/data/2016-09-15-gmseg_model_80sub":
Dataset: /Users/saradupont/Neuropoly/data/2016-09-10_pain_data/not_used_in_model/
Passed: 14/14
Total duration: 652s

         subject   dice_gm   dice_wm  duration_[s]  hausdorff  med_dist  status
0   d_sp_pain_06  0.676495  0.914044    372.507610   1.489739  0.373790       0
1   d_sp_pain_10  0.731116  0.933216    362.825534   1.101172  0.246040       0
2   d_sp_pain_14  0.755153  0.937224    375.272380   1.170351  0.290825       0
3   d_sp_pain_15  0.708268  0.923201    374.000409   1.348445  0.343874       0
4   d_sp_pain_17  0.710057  0.929361    376.068160   1.585706  0.335388       0
5   d_sp_pain_18  0.738007  0.941937    357.662749   1.444680  0.306011       0
6   d_sp_pain_19  0.703518  0.925197    369.296430   1.356713  0.353257       0
7   d_sp_pain_21  0.753171  0.942181    367.269347   1.305294  0.336534       0
8   d_sp_pain_22  0.612418  0.905876    282.831767   1.260235  0.437954       0
9   d_sp_pain_23  0.754894  0.940493    278.940405   1.251985  0.318409       0
10  d_sp_pain_24  0.728988  0.929602    274.193769   1.136788  0.321032       0
11  d_sp_pain_25  0.792036  0.946740    277.498639   1.379144  0.266429       0
12  d_sp_pain_28  0.756970  0.933955    277.588795   1.275523  0.315482       0
13  d_sp_pain_29  0.540567  0.893978    275.534413   1.567877  0.531247       0
14          Mean  0.711547  0.928357    330.106458   1.333832  0.341162     NaN
15           STD  0.065521  0.015002     47.317814   0.150286  0.071661     NaN
Status: 0: Passed | 1: Crashed | 99: Failed | 200: File(s) missing

```

**Comment by SaraDupont** [comment]
Results with 
  - corrected binarization (impact on data co-registration and registration to the model). 
  - corrected header for model images from UCL 

```
Results for "sct_segment_graymatter -i t2star/t2star.nii.gz -s t2star/t2star_seg.nii.gz -ref t2star/t2star_manual_gmseg.nii.gz -vertfile t2star/MNI-Poly-AMU_level.nii.gz -model /Users/saradupont/Neuropoly/data/2016-09-19_gmseg_model_80sub_reg_corr":
Dataset: /Users/saradupont/Neuropoly/data/2016-09-10_pain_data/not_used_in_model/
Passed: 14/14
Total duration: 659s

         subject   dice_gm   dice_wm  duration_[s]  hausdorff  med_dist  status
0   d_sp_pain_06  0.668349  0.912044    368.651902   1.461431  0.360055       0
1   d_sp_pain_10  0.658447  0.921783    365.502569   1.326278  0.338074       0
2   d_sp_pain_14  0.773392  0.942722    369.320941   1.060855  0.272993       0
3   d_sp_pain_15  0.723135  0.928926    370.826876   1.201143  0.322165       0
4   d_sp_pain_17  0.713769  0.930411    374.677824   1.385096  0.317899       0
5   d_sp_pain_18  0.763422  0.946255    365.352651   1.057707  0.280000       0
6   d_sp_pain_19  0.732756  0.930452    366.954138   1.004468  0.300480       0
7   d_sp_pain_21  0.750710  0.939147    365.990966   0.992938  0.287699       0
8   d_sp_pain_22  0.604336  0.907362    289.189845   1.129048  0.393945       0
9   d_sp_pain_23  0.793750  0.945702    285.642939   1.140817  0.241202       0
10  d_sp_pain_24  0.743078  0.929377    284.739957   0.965073  0.301981       0
11  d_sp_pain_25  0.799600  0.948372    289.263161   1.132952  0.249193       0
12  d_sp_pain_28  0.784760  0.941346    288.212901   1.011811  0.259324       0
13  d_sp_pain_29  0.557763  0.898289    287.294176   1.521629  0.503841       0
14          Mean  0.719091  0.930156    333.687203   1.170803  0.316346     NaN
15           STD  0.072609  0.015522     41.690102   0.182803  0.068770     NaN
Status: 0: Passed | 1: Crashed | 99: Failed | 200: File(s) missing
```

**Pull request merged**
