### PR TITLE
New function: sct_deepseg_lesion

### PR DESCRIPTION
**Pull request by charleygros**
### TODO
* [x] Add models on OSF
* [ ] Create testing function --> to Discuss
* [x] Create `sct_deepseg_lesion` GH label

### Description of the Change

- MANDATORY ARGS:
```
sct_deepseg_lesion.py -i t2s.nii.gz -c t2s
```

- AVAILABLE CONTRASTS: `{t2,t2s,t2_ax}`
`-c t2_ax` --> was train on ~200 3D T2-w volumes with anisotropic resolution, axial orientation.
`-c t2` --> was train on 3D T2-w volumes with anisotropic resolution, both axial orientation and sagittal orientation.

- CENTERLINE DETECTION: 2 available ways to do it --> via the flag `-ctr`
`-ctr svm` --> OptiC initialized with SVM+HoG maps (former version, currently the one integrated in master). Avantages: faster, more robust to exotic / new contrasts.
`-ctr cnn` --> OptiC initialized with CNN_1 maps. Avantages: more robust to compressed cord and/or sagittal images.

- DEALING WITH THE PRESENCE OF THE BRAIN:
`-brain 0` --> The algorithm will go through all the axial slices. Currently the version running in master. Note that this option is always set with -ctr svm.
`-brain 1` --> If brain is detected (using the CNN1 previously mentioned), the segmentation algorithm will ignore axial slices above the brainstem. PROS: (i) speed up the segmentation (especially for sagittal images), (ii) Less false positive 'blobs' in the brain. CONS: The segmentation could sometimes stop below the brainstem.

### Steps and Constraints
/!\ Please re-install the toolbox: data folder

### CODE REVIEW

**Comment by abtahizadeh** [comment]
@charleygros Logs (sct_download_data):

```
'deepseg_lesion_models': ['https://osf.io/eg7v9/?action=download',
                          ^
SyntaxError: invalid syntax
```

**Comment by charleygros** [comment]
@jcohenadad : It should be fixed now.
@abtahizadeh : Merci!

**Comment by jcohenadad** [comment]
error with this commit fba8c8635a5fcfc8f6644b82f1d8874d1ea57ecf
~~~
IOError: Unable to open file (Unable to open file: name = '/users/julien/code/sct/data/deepseg_lesion_models/t2_lesion.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
~~~

probably because the model is not installed during SCT installation. It would need to be added.

**Comment by charleygros** [comment]
(The models should now be available, except if I missed something else)

**Comment by jcohenadad** [comment]
@abtahizadeh could you please create a test for this function before we merge it?  in the same vein as the other testing functions that already exist. No need for integrity testing at this point (but we can open an issue to address it in the future). Thanks!

**Comment by abtahizadeh** [comment]
@jcohenadad okay, please allow me some time to understand the function.

**Comment by jcohenadad** [comment]
test added in https://github.com/neuropoly/spinalcordtoolbox/pull/1850/commits/b5bd69ebe86a1aaf342f8969b5d5b0746ab30425
integrity test to do (another PR): https://github.com/neuropoly/spinalcordtoolbox/issues/1915

**Pull request merged**
