### PR TITLE
sct_get_centerline - new manual feature

### PR DESCRIPTION
**Pull request by benjamindeleener**
### New method in sct_get_centerline

This Pull Request introduces a new manual approach to extract the spinal cord centerline from images. The method is straight-forward:

1. open a viewer to click on a few slices (the gap between slices is 10mm by default and can be change using `-gap` option)
2. use smooth_centerline to approximate the centerline with NURBS
3. generate an image with the centerline

### Steps and Constraints

On example data:

```
sct_download_data -d sct_example_data
cd sct_example_data/t2/
sct_get_centerline -i t2.nii.gz -method viewer
```

### Applicable Issues

Implements #1461

### CODE REVIEW

**Comment by benjamindeleener** [comment]
Indeed, the viewer at the end should probably be removed by default. And the new viewer would be more than welcome on this project.

**Comment by jcohenadad** [comment]
great feature! comments for e2435d11a15c7e5f2f6782eed6805cd27d892e36:
- no need to have the fitted plot appear by default (let's keep that for verbose 2)
- possible to also save a txt file with non-discrete centerline values? (as in optic method). Might be useful for template generation (slightly more precise).
- how easy would it be to have the possibility to create a centerline by pointing labels on a sagittal view (instead of axial), centered in the median plane. That would notably be useful for Ryan's project.

**Comment by benjamindeleener** [comment]
@jcohenadad @charleygros I fixed the issues you mentioned. Review requested.

Concerning the sagittal viewer, I'll wait for George's implementation, as it will be much easier to use his code to allow that feature (and I don't want to spend too much time on something that will be throw away soon).

**Comment by benjamindeleener** [comment]
As for the txt file, OptiC does not seem to output this information, but I added it for the viewer.

**Pull request merged**
