### PR TITLE
Fixed up/down dysfunction in the qc report 

### LINKED ISSUE #2476: The up/down arrow is dysfunctional when search mode is activatede
When using the search mode to filter the entries in the QC report (i.e. rows that appear), the up/down keys does not seem to work appropriately anymore. It seems like the up/down keys refer to the unfiltered entries. 

See screen recording [here](https://www.dropbox.com/s/ms2nxvonntxf083/20191006_SCT_issue2476_QC.mov?dl=0).

To reproduce, download [this QC report](https://www.dropbox.com/s/60aawmnzii3l4gv/20191005_SCT_issue2464_qc.zip?dl=0).

### PR DESCRIPTION
**Pull request by TommyBoshkovski**
Fixes #2476,  up/down dysfunction when search mode is activated. 

Replaced the html search input with bootstrap-table's embedded search input.

### CODE REVIEW

**Comment by jcohenadad** [comment]
@TommyBoshkovski I am getting this error:
~~~
julien-macbook:~ $ sct_testing -f sct_qc

--
Spinal Cord Toolbox (git-TommyBoshkovski-master-354f788baa2fa5ec3b8ace81d2f3a2b7c36815f7)

Will run through the following tests:
- in parallel with 1 jobs: sct_qc
Checking sct_qc.....................................[FAIL]
   
   ====================================================================================================
   sct_qc -i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -p sct_deepseg_sc -qc-dataset sct_testing_data -qc-subject dummy
   ====================================================================================================
   
   
   --
   Spinal Cord Toolbox (git-TommyBoshkovski-master-354f788baa2fa5ec3b8ace81d2f3a2b7c36815f7)
   
   
   *** Generate Quality Control (QC) html report ***
   Resample images to 0.6x0.6 mm
   QcImage: layout with Axial slice
   Compute center of mass at each slice
   Traceback (most recent call last):
   File "/Users/julien/code/sct/scripts/sct_qc.py", line 86, in <module>
   main(arguments)
   File "/Users/julien/code/sct/scripts/sct_qc.py", line 79, in main
   process=args.p)
   File "/Users/julien/code/sct/spinalcordtoolbox/reports/qc.py", line 613, in generate_qc
   stretch_contrast_method='equalized',
   File "/Users/julien/code/sct/spinalcordtoolbox/reports/qc.py", line 503, in add_entry
   layout(qcslice)
   File "/Users/julien/code/sct/spinalcordtoolbox/reports/qc.py", line 293, in wrapped_f
   self.qc_report.update_description_file(img.shape)
   File "/Users/julien/code/sct/spinalcordtoolbox/reports/qc.py", line 444, in update_description_file
   self._update_html_assets(get_json_data_from_path(path_json))
   File "/Users/julien/code/sct/spinalcordtoolbox/reports/qc.py", line 453, in _update_html_assets
   output = template.substitute(sct_json_data=json.dumps(json_data))
   File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/string.py", line 130, in substitute
   return self.pattern.sub(convert, self.template)
   File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/string.py", line 127, in convert
   self._invalid(mo)
   File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/string.py", line 103, in _invalid
   (lineno, colno))
   ValueError: Invalid placeholder in string: line 252, col 3
status: [1]
Failures: sct_qc
Finished! Elapsed time: 1s
~~~

**Comment by TommyBoshkovski** [comment]
@jcohenadad  Could you send me the data's json file

**Comment by jcohenadad** [comment]
here you go: 
[qc_2019_10_06_153303.227727.json.zip](https://github.com/neuropoly/spinalcordtoolbox/files/3694830/qc_2019_10_06_153303.227727.json.zip)

**Comment by jcohenadad** [comment]
if that helps, you can easily reproduce the error by running the testing:
~~~
sct_testing -f sct_qc
~~~

**Comment by TommyBoshkovski** [comment]
Should be OK now :)

**Comment by jcohenadad** [comment]
Tested 6545854abef9b700e9f2a77e85bd80923cfbd87e, a few comments:
- all columns are shown (with sliding option at the bottom), which is inconvenient because people need to be able to only select the relevant columns (hence the button "display column")
- consequently, the height of each row is larger, which is suboptimal in terms of display
- when typing something in the search module, and then pressing top/down arrow key does not work anymore (it used to work)

Here are the two QCs for comparison:
TommyBoshkovski-master 6545854abef9b700e9f2a77e85bd80923cfbd87e:
[qc_TommyBoshkovski-master.zip](https://github.com/neuropoly/spinalcordtoolbox/files/3695171/qc_TommyBoshkovski-master.zip)

master 6f50fd8e917e8e255a0004daa1966c4a1fec49bf:
[qc_master.zip](https://github.com/neuropoly/spinalcordtoolbox/files/3695172/qc_master.zip)

**Comment by TommyBoshkovski** [comment]
@jcohenadad can you please test it again. I've tested it, and I think now it addresses all of your comments.

**Pull request merged**
