### PR TITLE
Explicitly set verbose in calls to generate_output_file

### LINKED ISSUE #2851: Some scripts are incorrectly calling generate_output_file (`squeeze_data` is set by verbose parameter)
### Description

In some calls to `sct_utils.generate_output_file`, verbose is specified as a positional arg rather than a keyword arg. This is a problem, because this is actually setting `squeeze_data` instead. 

This can cause bugs when `verbose==False`, because it inadvertently sets `squeeze_data` to False. See below for an example of such a bug:

<details>
<summary> Original issue description hidden. Click to show </summary>

### Original description

While working on #2676, I noticed this bug. Modiying this line here to use the `-v` option:

https://github.com/neuropoly/spinalcordtoolbox/blob/bf3de687c20ac86717de3584296af1931e247784/testing/test_sct_dmri_separate_b0_and_dwi.py#L24

With `True`, `1`, `2`, etc. tests pass successfully:

```bash
Will run through the following tests:
- in parallel with 1 jobs: sct_dmri_separate_b0_and_dwi
Checking sct_dmri_separate_b0_and_dwi...............[OK]
status: [0]
Finished! Elapsed time: 3s
```

With `False`/`0`, tests give a warning because of an extra dimension in the output image:

```bash
Checking sct_dmri_separate_b0_and_dwi...............[WARNING]
   
   ====================================================================================================
   sct_dmri_separate_b0_and_dwi -i dmri/dmri.nii.gz -bvec dmri/bvecs.txt -a 1 -r 0
   ====================================================================================================
   
   
   --
   Spinal Cord Toolbox (git-jn/2676-change-verbosity-c8d4c656f96f9c9b3627381cd09285d22b0d1b61*)
   
   sct_convert -i /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/dmri/dmri.nii.gz -o /tmp/sct-20200818101936.565183-dmri_separate-h4ctjg0v/dmri.nii
   
   WARNING: File /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/dmri_b0.nii.gz already exists. Deleting it...
   File created: /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/dmri_b0.nii.gz
   WARNING: File /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/dmri_dwi.nii.gz already exists. Deleting it...
   File created: /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/dmri_dwi.nii.gz
   WARNING: File /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/dmri_b0_mean.nii.gz already exists. Deleting it...
   File created: /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/dmri_b0_mean.nii.gz
   WARNING: File /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/dmri_dwi_mean.nii.gz already exists. Deleting it...
   File created: /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/dmri_dwi_mean.nii.gz
   
   ====================================================================================================
   INTEGRITY TESTING
   ====================================================================================================
   
   Checking DWI
   --> PASSED
   
   Checking b=0
   operands could not be broadcast together with shapes (40,42,5) (40,42,5,1) 
status: [99]
Failures: sct_dmri_separate_b0_and_dwi
Finished! Elapsed time: 3s
```

I'm not sure why verbosity would have an effect like this, but I am investigating the cause.

</details>

### PR DESCRIPTION
**Pull request by joshuacwnewton**
### Reference issues/PRs

Fixes #2851.

### What does this implement/fix? Explain your changes.

This explicitly sets `verbose` to prevent `squeeze_data` from incorrectly being set instead.

### CODE REVIEW

**Comment by joshuacwnewton** [comment]
> We could merge your PR, but I see that as a short-term bandage to the bigger problem.

I agree!

For more context, this issue (i.e. #2851) is currently affecting my work in #2676. Because using `action="store_true"` for verbose sets `False` as the default, one of my tests is showing warnings because of this bug.

So, if the goal is to get #2676 done by the 5.0.0 release (1-2 weeks), then this PR might be okay for now. We can consider the long-term future of verbose once we have a bit more time, perhaps?

**Comment by joshuacwnewton** [comment]
Thanks for taking a look and giving approval, @jcohenadad! Does anything else need to be done to merge? GitHub tells me I don't have authorization to merge, so I thought I'd ask. :slightly_smiling_face:

**Comment by jcohenadad** [comment]
> GitHub tells me I don't have authorization to merge, so I thought I'd ask.

that's weird... you have write permission on this repos.

**Comment by joshuacwnewton** [comment]
It is odd...

Screenshot from 2020-08-26 19-35-25

I'm not sure what the settings are like on the admin end of SCT, though. I'll msg the dev Slack.

**Comment by jcohenadad** [comment]
i've upgraded you from write to maintain. Maybe this will solve it?

**Comment by joshuacwnewton** [comment]
That fixed it. :smile:

**Pull request merged**
