### PR TITLE
Add HPC templates (slurm and PBS)

### LINKED ISSUE #1348: Add documentation and templates for sct_pipeline
### Description

Document how to setup and run a pipeline on both HPC and locally. With the documentation, provide a template script for the most common use cases.

### PR DESCRIPTION
**Pull request by poquirion**
### Description of the Change
Add supercomputer template for `guillimin`, `mammouth`, `scinet-gpc`, and `cedar` 

### Steps and Constraints

The templates are in the install folders, might be better to put them somewhere else

### Applicable Issues

Implements or Fixes #1348 to some extent. Still need to better document the wiki...

### CODE REVIEW

**Comment by jcohenadad** [comment]
how about putting these into a new folder called "hpc", and the folder would include a README.md to explain what the folder is about.

**Comment by poquirion** [comment]
Yep, I'll add something in the Readme. For the hpc folder, maybe in documentation/hpc?

**Comment by jcohenadad** [comment]
i meant creating another specific readme within the hcp folder (because when someone wants to use your template, he will have the info right there)

**Comment by poquirion** [comment]
Yes, absolutely, I got that on the second reading!

**Comment by poquirion** [comment]
I've added a readme and the HPC directory.

**Pull request merged**
