### PR TITLE
Improvements on centerline and template generation

### PR DESCRIPTION
**Pull request by benjamindeleener**
### Description of the Change

This Pull Request introduces changes on the framework for generating spinal cord MRI templates. While many commits are included, only a few files have been significantly changed. For example, new functions on the `Centerline` object have been introduced, so that one can easily extract information from spinal cord image. Centerlines can also be saved and loaded, which can gain a lot of time (mainly lost due to NURBS approximation).

### CODE REVIEW

**Comment by benjamindeleener** [comment]
@jcohenadad @peristeri Yes there are some cleaning to do, mainly because I merged a branch with the viewer from @alexandrospopov, thinking that it would be integrated into Master... That is why I added "Work in progress" on top of the description. I will clean it up next week.

This Pull Request includes some very nice improvements on Centerline, that need to be merged.

**Comment by benjamindeleener** [comment]
@jcohenadad @peristeri this PR is now clean and should be ready to merge if the tests pass. Review are welcome.

**Comment by jcohenadad** [comment]
the title of the PR is confusing: it suggests that the PAM50 has been modified, however the description says otherwise. Please update the title or description. This will help decide whether to merge this now (before 3.0.8, which is supposed to happen today) or later (for 3.1). Thanks.

**Comment by benjamindeleener** [comment]
@jcohenadad Done. The improvements on centerline would be useful for processing data along the spinal cord, as image feature characterization (Charley's work).

**Comment by jcohenadad** [comment]
@benjamindeleener: could you please run `batch_processing.sh -nodisplay` and report numbers in this PR, along with numbers from the master branch?
@peristeri: after merging this PR, you can prepare 3.0.8 and copy/paste these results on the release notes as usual.
thank you everyone

**Comment by benjamindeleener** [comment]
Branch PAM50:
```
t2/CSA:   77.336978, 1.698544
mt/MTR:   51, white matter, 2909.539055, 21.950534, 0.000000
mt/CSA_GM:   18.656204, 1.643710
mt/CSA_WM:   60.487054, 2.473967
dmri/FA:  4, WM left lateral corticospinal tract, 72.751803, 0.697896, 0.156813
dmri/FA:  5, WM right lateral corticospinal tract, 74.051164, 0.741508, 0.132873
```

Branch Master:
```
t2/CSA:   77.336978, 1.698544
mt/MTR:   51, white matter, 2927.144075, 21.948131, 0.000000
mt/CSA_GM:   18.523568, 1.645447
mt/CSA_WM:   60.838360, 2.460520
dmri/FA:  4, WM left lateral corticospinal tract, 73.509947, 0.697804, 0.156472
dmri/FA:  5, WM right lateral corticospinal tract, 74.011204, 0.741739, 0.132849
```

**Pull request merged**
