### PR TITLE
Replace instances of 'sct_convert.convert' with 'image.convert'

### LINKED ISSUE #3282: image.convert function is called incorrectly, causing error during registration
A user on the forum is reporting an error: https://forum.spinalcordmri.org/t/register-template-to-mt1/654

The bug is from this line of code:

https://github.com/neuropoly/spinalcordtoolbox/blob/0b7be07b7e64a57a303824e85930fbceb8b890f0/spinalcordtoolbox/registration/register.py#L373

The usage of this function doesn't match its parameters:

https://github.com/neuropoly/spinalcordtoolbox/blob/0b7be07b7e64a57a303824e85930fbceb8b890f0/spinalcordtoolbox/image.py#L1341-L1348

I believe `image.convert` came about in #2871/#2812. I'll dig into that and find out what the correct usage should be.

### PR DESCRIPTION
**Pull request by joshuacwnewton**
#### GitHub

- [X] I've given this PR a concise, self-descriptive, and meaningful title
- [X] I've linked relevant issues in the PR body
- [X] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [X] I've applied a [release milestone](https://github.com/neuropoly/spinalcordtoolbox/milestones) (major, minor, patch) in line with [Semantic Versioning guidelines](https://github.com/neuropoly/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release#convention-for-naming-releases) 
- [X] I've assigned a reviewer

#### PR contents

- [X] I've consulted [SCT's internal developer documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki) to ensure my contribution is in line with any relevant design decisions
- [ ] I've added [relevant tests](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Tests) for my contribution
- [ ] I've updated the [relevant documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description

In #2812, a bug was introduced due to 2 identically-named `convert` functions. 

This PR fixes the bug. It also removes the CLI `convert` function and replaces all instances with the API `convert` function to remove any ambiguity.

## Linked issues

Fixes #3282.

### CODE REVIEW

**Comment by joshuacwnewton** [comment]
Actually, it might also be good to add a test that includes the `-m` option of `sct_register_to_template`. The exact command used was:

```
sct_register_multimodal -i /home/forest/sct/data/PAM50/template/PAM50_t2.nii.gz -iseg /home/forest/sct/data/PAM50/template/PAM50_cord.nii.gz -d mt1.nii.gz -dseg mt1_seg.nii.gz -param step=1,type=seg,algo=centermass:step=2,type=seg,algo=bsplinesyn,slicewise=1,iter=3 -m mask_mt1.nii.gz -initwarp ../t2/warp_template2anat.nii.gz -qc /home/forest/qc_singleSubj
```

And, I believe this is tied to the SCT course instructions, so the command to generate `mt1_mask.nii.gz` was probably:

```
sct_create_mask -i mt1.nii.gz -p centerline,mt1_seg.nii.gz -size 35mm -f cylinder -o mask_mt1.nii.gz
```

(from p74 of the [course materials](https://www.icloud.com/keynote/0th8lcatyVPkM_W14zpjynr5g#SCT%5FCourse%5F20200121))

**Review by Drulex — COMMENTED** [review]
Looks good, but I still see 2 scripts that import `sct_convert.convert()` (ignoring `moco.py`):
- `sct_propseg.py`
- `sct_smooth_spinalcord.py`

Is this intentional?

**Comment by joshuacwnewton** [comment]
> Looks good, but I still see 2 scripts that import `sct_convert.convert()` (ignoring `moco.py`):
> 
>   * `sct_propseg.py`
>   * `sct_smooth_spinalcord.py`
> 
> Is this intentional?

They should be included in this PR, unless I'm missing something. :thinking: 

Screenshot from 2021-03-16 10-53-38

**Comment by Drulex** [comment]
> > Looks good, but I still see 2 scripts that import `sct_convert.convert()` (ignoring `moco.py`):
> > 
> > * `sct_propseg.py`
> > * `sct_smooth_spinalcord.py`
> > 
> > Is this intentional?
> 
> They should be included in this PR, unless I'm misunderstanding. 
> 
> Screenshot from 2021-03-16 10-53-38

My apologies, I was looking at my fork instead of this repo :sweat_smile:

**Review by Drulex — APPROVED** [review]

**Comment by joshuacwnewton** [comment]
Sorry to request a re-review, @Drulex.

I've written a very basic test to at least confirm that `-m` can be called correctly. It fails on master, and passes here. 

The reason I haven't written a more in-depth check is that there are other `sct_register_multimodal` tests in #3246:

https://github.com/neuropoly/spinalcordtoolbox/blob/ef9ee9f7dedc74d61286ee8c9acba93945b61ec2/unit_testing/cli/test_cli_sct_register_multimodal.py#L14-L22

So, I want to think about how best to organize this logic over there.

**Review by gisellemartel — APPROVED** [review]
Test code is clean, good work! Tested locally and new test case passes.

**Pull request merged**
