### PR TITLE
SCT logo fix in FSLeyes

### PR DESCRIPTION
**Pull request by valosekj**
Fix of wrong SCT logo appearance when using `sct_plugin.py` in FSLeyes under Debian 10 Buster.
For me (under Debian 10), it looks that `SetSize` method crop image instead of rescale it. `Scale` method works fine.
I have not tested Docker behavior, however.

Fixes https://github.com/neuropoly/spinalcordtoolbox/issues/2586

### CODE REVIEW

**Comment by jcohenadad** [comment]
On OSX, the proposed change reduces the quality of the displayed SCT logo.

On master (637d0f2a0ff476389257309a69adc64cad36926c):
Screen Shot 2020-04-04 at 9 27 17 PM

On jv/2586-sct-logo-fix (8ee7318c9264bc8ee8eeda04469f1f2262f4252e):
Screen Shot 2020-04-04 at 9 26 47 PM

**Comment by valosekj** [comment]
I increased logo quality by changing of interpolation method. Unfortunately, quality is still lower compared to original. 

Snímek obrazovky 2020-04-05 v 19 26 16

I have also tried `wx.Image.Resize` and `wx.Image.Size` methods, but both only crop image instead of resize it on OSX. I will think about it.

**Comment by valosekj** [comment]
So, based on recommendation from wxPython maintainer Robin Dunn, `wx.Image.Scale` (jv/2586-sct-logo-fix - https://github.com/neuropoly/spinalcordtoolbox/commit/8ee7318c9264bc8ee8eeda04469f1f2262f4252e) should be used instead of `wx.Bitmap.SetSize` (master  - https://github.com/neuropoly/spinalcordtoolbox/commit/637d0f2a0ff476389257309a69adc64cad36926c).

https://github.com/wxWidgets/Phoenix/issues/1588#event-3211026274

**Comment by jcohenadad** [comment]
> So, based on recommendation from wxPython maintainer Robin Dunn, wx.Image.Scale (jv/2586-sct-logo-fix - 8ee7318) should be used instead of wx.Bitmap.SetSize (master - 637d0f2).

right, but "Scale" looks ugly, so (i) can you please follow-up in your other thread to explain what the problem is so maybe he will have a solution or (ii) find a workaround while using Scale or (iii) do an OS-specific call (not a nice solution)

**Comment by valosekj** [comment]
> > So, based on recommendation from wxPython maintainer Robin Dunn, wx.Image.Scale (jv/2586-sct-logo-fix - [8ee7318](https://github.com/neuropoly/spinalcordtoolbox/commit/8ee7318c9264bc8ee8eeda04469f1f2262f4252e)) should be used instead of wx.Bitmap.SetSize (master - [637d0f2](https://github.com/neuropoly/spinalcordtoolbox/commit/637d0f2a0ff476389257309a69adc64cad36926c)).
> 
> right, but "Scale" looks ugly, so (i) can you please follow-up in your other thread to explain what the problem is so maybe he will have a solution or (ii) find a workaround while using Scale or (iii) do an OS-specific call (not a nice solution)

(i) sure, I have asked him.
(ii) I tried other interpolations offered for Scale (https://wxpython.org/Phoenix/docs/html/wx.ImageResizeQuality.enumeration.html). All decrease quality. 
(iii) you are right, it is not the best solution

I will continue in finding the solution.

**Comment by valosekj** [comment]
The easiest workaround could be to use manually rescaled logo (similar approach like used [here](https://github.com/neuropoly/axondeepseg/blob/73f0c90b882ea645acac8a069a0e5010a96c52f8/ads_plugin.py#L962)). However, it is tricky to resize current .png [SCT logo](https://github.com/neuropoly/spinalcordtoolbox/blob/master/documentation/imgs/logo_sct.png) without losing quality. Is the SCT logo available in vector graphics format?

**Comment by jcohenadad** [comment]
> The easiest workaround could be to use manually rescaled logo (similar approach like used [here](https://github.com/neuropoly/axondeepseg/blob/73f0c90b882ea645acac8a069a0e5010a96c52f8/ads_plugin.py#L962)). However, it is tricky to resize current .png [SCT logo](https://github.com/neuropoly/spinalcordtoolbox/blob/master/documentation/imgs/logo_sct.png) without losing of quality. Is the SCT logo available in vector graphics format?

[https://drive.google.com/file/d/1OX3q4AJ24mEBvjiI7Sx-pYUD7derdsTt/view?usp=sharing](here) is a pdf version of the logo. But the one you created is actually not too bad!

**Comment by valosekj** [comment]
pdf logo has also limited ability to be rescaled without losing quality how I found out. So I deployed logo from previous post.
Looks fine for me now on OSX 10.14 and Debian 10.

**Comment by valosekj** [comment]
@jcohenadad 👍
I wanted to merge this PR to master. But, it was not allowed to me:

Snímek obrazovky 2020-05-10 v 17 02 09

So, I clicked on _Update branch_, causing https://github.com/neuropoly/spinalcordtoolbox/pull/2657/commits/1d6bc1461ddfc4895550a4867258b060feddc2fd. After it, integrity test failed:

unit_testing/test_qc_parallel.py::test_many_qc FAILED                    [ 91%]

**Comment by jcohenadad** [comment]
@cfhammill looks like we got another Travis failure on the Mojave build due to the multithread json writing.

**Pull request merged**
