### PR TITLE
Install SCT in conda's site packages.

### PR DESCRIPTION
**Pull request by peristeri**
First step towards moving towards installing SCT through pipy.

### CODE REVIEW

**Comment by jcohenadad** [comment]
i'm testing it  now-- cloning this branch and running install_sct. Is there anything particular that should be checked/tested?

**Comment by peristeri** [comment]
Yes, you can run `source python/bin/activate; pip freeze`. You should see spinalcordtoolbox in the list of packages

**Comment by jcohenadad** [comment]
i don't see it, see below:
~~~
source python/bin/activate
(root) julien-macbook:~/temp/sct $ 
(root) julien-macbook:~/temp/sct $ pip freeze
appdirs==1.4.2
cffi==1.9.1
conda==4.3.13
cryptography==1.7.1
cycler==0.10.0
decorator==4.0.11
dipy==0.11.0
enum34==1.1.6
idna==2.2
ipaddress==1.0.18
matplotlib==1.5.1
mpmath==0.19
networkx==1.11
nibabel==2.1.0
nipy==0.4.0
numpy==1.11.2
olefile==0.44
packaging==16.8
pandas==0.18.1
Pillow==4.0.0
pyasn1==0.1.9
pycosat==0.6.1
pycparser==2.17
pycrypto==2.6.1
pyOpenSSL==16.2.0
pyparsing==2.1.10
python-dateutil==2.6.0
pytz==2016.10
PyYAML==3.11
requests==2.12.4
ruamel-yaml===-VERSION
scikit-image==0.12.3
scikit-learn==0.17.1
scipy==0.18.1
six==1.10.0
sympy==1.0
xlrd==0.9.4
xlutils==1.7.1
xlwt==1.0.0
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
~~~

**Comment by peristeri** [comment]
Was there an error during the installation? I assume that there was an error and the installation continued anyways.

**Comment by jcohenadad** [comment]
below is the copy/paste of the installation. There does not seem to be an error:
~~~
./install_sct

Welcome to the SCT installer!

SCT version ......... dev
Installation type ... git
Operating system .... osx
sudo mode ........... 0

SCT will be installed here: [/Users/julien/temp/sct]
Do you agree? yes/no: y
mkdir: /Users/julien/temp/sct: File exists

Removing sct and isct softlink from /Users/julien/temp/sct/bin
find: /Users/julien/temp/sct/bin: No such file or directory
find: /Users/julien/temp/sct/bin: No such file or directory

Skipping copy of source files (source and destination folders are the same)

Create launchers for Python scripts
>> mkdir -p /Users/julien/temp/sct/bin
>> cd /Users/julien/temp/sct/install
>> ./update_bin.sh
#!/bin/bash
$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/sct_launcher $(basename $0).py $@
yes isct_check_detection
yes isct_convert_binary_to_trilinear
yes isct_minc2volume-viewer
yes isct_test_ants
yes isct_test_function
yes isct_warpmovie_generator
yes msct_image
yes msct_multiatlas_seg
yes sct_apply_transfo
yes sct_average_data_within_mask
no sct_change_image_type
yes sct_check_atlas_integrity
yes sct_check_dependencies
yes sct_compute_ernst_angle
yes sct_compute_hausdorff_distance
yes sct_compute_mscc
yes sct_compute_mtr
yes sct_compute_snr
yes sct_concat_transfo
yes sct_convert
yes sct_create_mask
yes sct_crop_image
no sct_denoising_onlm
yes sct_dice_coefficient
yes sct_dmri_compute_dti
yes sct_dmri_concat_bvals
yes sct_dmri_concat_bvecs
yes sct_dmri_create_noisemask
no sct_dmri_eddy_correct
yes sct_dmri_get_bvalue
yes sct_dmri_moco
yes sct_dmri_separate_b0_and_dwi
yes sct_dmri_transpose_bvecs
yes sct_download_data
yes sct_extract_metric
yes sct_flatten_sagittal
yes sct_fmri_compute_tsnr
yes sct_fmri_moco
no sct_get_centerline
yes sct_image
no sct_invert_image
yes sct_label_utils
yes sct_label_vertebrae
yes sct_maths
yes sct_process_segmentation
yes sct_propseg
yes sct_register_graymatter
yes sct_register_multimodal
yes sct_register_to_template
yes sct_resample
yes sct_segment_graymatter
yes sct_smooth_spinalcord
yes sct_straighten_spinalcord
yes sct_testing
yes sct_viewer
yes sct_warp_template
yes test_regist

Installing conda...
>> rm -rf /Users/julien/temp/sct/python
>> mkdir /Users/julien/temp/sct/python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20.3M  100 20.3M    0     0  1573k      0  0:00:13  0:00:13 --:--:-- 1754k
exit status is 0
>> bash /var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/TMP_DIR.XK52W4hp/miniconda.sh -p /Users/julien/temp/sct/python -b -f
PREFIX=/Users/julien/temp/sct/python
installing: python-2.7.12-1 ...
installing: conda-env-2.5.2-py27_0 ...
installing: openssl-1.0.2h-1 ...
installing: pycosat-0.6.1-py27_1 ...
installing: pyyaml-3.11-py27_4 ...
installing: readline-6.2-2 ...
installing: requests-2.10.0-py27_0 ...
installing: ruamel_yaml-0.11.14-py27_0 ...
installing: sqlite-3.13.0-0 ...
installing: tk-8.5.18-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-3 ...
installing: conda-4.1.11-py27_0 ...
installing: pycrypto-2.6.1-py27_4 ...
installing: pip-8.1.2-py27_0 ...
installing: wheel-0.29.0-py27_0 ...
installing: setuptools-23.0.0-py27_0 ...
Python 2.7.12 :: Continuum Analytics, Inc.
creating default environment...
using -f (force) option
installation finished.
WARNING:
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda2.
    For best results, please verify that your PYTHONPATH only points to
    directories of packages that are compatible with the Python interpreter
    in Miniconda2: /Users/julien/temp/sct/python
Conda installation successful
>> . /Users/julien/temp/sct/python/bin/activate /Users/julien/temp/sct/python

Installing Python dependencies...
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /Users/julien/temp/sct/python:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          601 B
    jbig-2.1                   |                0          31 KB
    jpeg-9b                    |                0         240 KB
    mkl-11.3.3                 |                0       101.4 MB
    xz-5.2.2                   |                1         212 KB
    libpng-1.6.27              |                0         240 KB
    libtiff-4.0.6              |                3         756 KB
    decorator-4.0.11           |           py27_0          13 KB
    enum34-1.1.6               |           py27_0          54 KB
    freetype-2.5.5             |                2         738 KB
    idna-2.2                   |           py27_0         121 KB
    ipaddress-1.0.18           |           py27_0          30 KB
    numpy-1.11.2               |           py27_0         3.1 MB
    olefile-0.44               |           py27_0          51 KB
    pyasn1-0.1.9               |           py27_0          54 KB
    pycparser-2.17             |           py27_0         153 KB
    pyparsing-2.1.4            |           py27_0          70 KB
    pytz-2016.10               |           py27_0         181 KB
    requests-2.13.0            |           py27_0         776 KB
    sip-4.18                   |           py27_0         245 KB
    six-1.10.0                 |           py27_0          16 KB
    xlrd-0.9.4                 |           py27_0         179 KB
    xlwt-1.0.0                 |           py27_0         152 KB
    cffi-1.9.1                 |           py27_0         193 KB
    cycler-0.10.0              |           py27_0          11 KB
    networkx-1.11              |           py27_0         1.1 MB
    pillow-4.0.0               |           py27_1         485 KB
    python-dateutil-2.6.0      |           py27_0         232 KB
    qt-4.8.7                   |                4        37.1 MB
    scipy-0.18.1               |      np111py27_0        13.4 MB
    xlutils-1.7.1              |           py27_0          65 KB
    cryptography-1.7.1         |           py27_0         468 KB
    pandas-0.18.1              |      np111py27_0         7.1 MB
    pyqt-4.11.4                |           py27_4         4.0 MB
    scikit-learn-0.17.1        |      np111py27_2         3.7 MB
    matplotlib-1.5.1           |      np111py27_0         5.9 MB
    pyopenssl-16.2.0           |           py27_0          68 KB
    conda-4.3.13               |           py27_0         481 KB
    scikit-image-0.12.3        |      np111py27_1        18.0 MB
    ------------------------------------------------------------
                                           Total:       201.1 MB

The following NEW packages will be INSTALLED:

    cffi:            1.9.1-py27_0      
    cryptography:    1.7.1-py27_0      
    cycler:          0.10.0-py27_0     
    decorator:       4.0.11-py27_0     
    enum34:          1.1.6-py27_0      
    freetype:        2.5.5-2           
    idna:            2.2-py27_0        
    ipaddress:       1.0.18-py27_0     
    jbig:            2.1-0             
    jpeg:            9b-0              
    libpng:          1.6.27-0          
    libtiff:         4.0.6-3           
    matplotlib:      1.5.1-np111py27_0 
    mkl:             11.3.3-0          
    networkx:        1.11-py27_0       
    numpy:           1.11.2-py27_0     
    olefile:         0.44-py27_0       
    pandas:          0.18.1-np111py27_0
    pillow:          4.0.0-py27_1      
    pyasn1:          0.1.9-py27_0      
    pycparser:       2.17-py27_0       
    pyopenssl:       16.2.0-py27_0     
    pyparsing:       2.1.4-py27_0      
    pyqt:            4.11.4-py27_4     
    python-dateutil: 2.6.0-py27_0      
    pytz:            2016.10-py27_0    
    qt:              4.8.7-4           
    scikit-image:    0.12.3-np111py27_1
    scikit-learn:    0.17.1-np111py27_2
    scipy:           0.18.1-np111py27_0
    sip:             4.18-py27_0       
    six:             1.10.0-py27_0     
    xlrd:            0.9.4-py27_0      
    xlutils:         1.7.1-py27_0      
    xlwt:            1.0.0-py27_0      
    xz:              5.2.2-1           

The following packages will be UPDATED:

    conda:           4.1.11-py27_0      --> 4.3.13-py27_0
    conda-env:       2.5.2-py27_0       --> 2.6.0-0      
    requests:        2.10.0-py27_0      --> 2.13.0-py27_0

Fetching packages ...
conda-env-2.6. 100% |####################################################| Time: 0:00:00 716.33 kB/s
jbig-2.1-0.tar 100% |####################################################| Time: 0:00:00   1.29 MB/s
jpeg-9b-0.tar. 100% |####################################################| Time: 0:00:00   1.77 MB/s
mkl-11.3.3-0.t 100% |####################################################| Time: 0:00:57   1.85 MB/s
xz-5.2.2-1.tar 100% |####################################################| Time: 0:00:00 780.88 kB/s
libpng-1.6.27- 100% |####################################################| Time: 0:00:00   1.89 MB/s
libtiff-4.0.6- 100% |####################################################| Time: 0:00:00   1.70 MB/s
decorator-4.0. 100% |####################################################| Time: 0:00:00 238.80 kB/s
enum34-1.1.6-p 100% |####################################################| Time: 0:00:00 716.13 kB/s
freetype-2.5.5 100% |####################################################| Time: 0:00:00   1.66 MB/s
idna-2.2-py27_ 100% |####################################################| Time: 0:00:00   1.64 MB/s
ipaddress-1.0. 100% |####################################################| Time: 0:00:00   1.48 MB/s
numpy-1.11.2-p 100% |####################################################| Time: 0:00:01   1.95 MB/s
olefile-0.44-p 100% |####################################################| Time: 0:00:00 703.32 kB/s
pyasn1-0.1.9-p 100% |####################################################| Time: 0:00:00   1.13 MB/s
pycparser-2.17 100% |####################################################| Time: 0:00:00 768.90 kB/s
pyparsing-2.1. 100% |####################################################| Time: 0:00:00 663.83 kB/s
pytz-2016.10-p 100% |####################################################| Time: 0:00:00 972.24 kB/s
requests-2.13. 100% |####################################################| Time: 0:00:00   1.20 MB/s
sip-4.18-py27_ 100% |####################################################| Time: 0:00:00 653.91 kB/s
six-1.10.0-py2 100% |####################################################| Time: 0:00:00 767.20 kB/s
xlrd-0.9.4-py2 100% |####################################################| Time: 0:00:00   1.27 MB/s
xlwt-1.0.0-py2 100% |####################################################| Time: 0:00:00 895.80 kB/s
cffi-1.9.1-py2 100% |####################################################| Time: 0:00:00 678.61 kB/s
cycler-0.10.0- 100% |####################################################| Time: 0:00:00 808.55 kB/s
networkx-1.11- 100% |####################################################| Time: 0:00:01 911.43 kB/s
pillow-4.0.0-p 100% |####################################################| Time: 0:00:00 896.62 kB/s
python-dateuti 100% |####################################################| Time: 0:00:00 966.08 kB/s
qt-4.8.7-4.tar 100% |####################################################| Time: 0:00:21   1.78 MB/s
scipy-0.18.1-n 100% |####################################################| Time: 0:00:08   1.58 MB/s
xlutils-1.7.1- 100% |####################################################| Time: 0:00:00 631.56 kB/s
cryptography-1 100% |####################################################| Time: 0:00:00 967.27 kB/s
pandas-0.18.1- 100% |####################################################| Time: 0:00:04   1.63 MB/s
pyqt-4.11.4-py 100% |####################################################| Time: 0:00:02   1.88 MB/s
scikit-learn-0 100% |####################################################| Time: 0:00:02   1.86 MB/s
matplotlib-1.5 100% |####################################################| Time: 0:00:03   1.64 MB/s
pyopenssl-16.2 100% |####################################################| Time: 0:00:00 616.72 kB/s
conda-4.3.13-p 100% |####################################################| Time: 0:00:00   1.84 MB/s
scikit-image-0 100% |####################################################| Time: 0:00:11   1.65 MB/s
Extracting packages ...
[      COMPLETE      ]|#######################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#######################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#######################################################################| 100%
Collecting nipy==0.4.0 (from -r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 1))
  Using cached nipy-0.4.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting nibabel==2.1.0 (from -r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 2))
Collecting dipy==0.11.0 (from -r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 3))
  Using cached dipy-0.11.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting requests[security]==2.12.4 (from -r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 4))
  Downloading requests-2.12.4-py2.py3-none-any.whl (576kB)
    100% |████████████████████████████████| 583kB 801kB/s 
Collecting sympy>=0.7.0 (from nipy==0.4.0->-r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 1))
Collecting scipy>=0.9 (from dipy==0.11.0->-r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 3))
  Using cached scipy-0.18.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting idna>=2.0.0; extra == "security" (from requests[security]==2.12.4->-r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 4))
  Downloading idna-2.3-py2.py3-none-any.whl (55kB)
    100% |████████████████████████████████| 61kB 1.6MB/s 
Collecting cryptography>=1.3.4; extra == "security" (from requests[security]==2.12.4->-r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 4))
  Downloading cryptography-1.7.2-cp27-cp27m-macosx_10_6_intel.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 388kB/s 
Collecting pyOpenSSL>=0.14; extra == "security" (from requests[security]==2.12.4->-r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 4))
  Downloading pyOpenSSL-16.2.0-py2.py3-none-any.whl (43kB)
    100% |████████████████████████████████| 51kB 2.6MB/s 
Collecting mpmath>=0.19 (from sympy>=0.7.0->nipy==0.4.0->-r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 1))
Collecting numpy>=1.7.1 (from scipy>=0.9->dipy==0.11.0->-r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 3))
  Using cached numpy-1.12.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting six>=1.4.1 (from cryptography>=1.3.4; extra == "security"->requests[security]==2.12.4->-r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 4))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting cffi>=1.4.1 (from cryptography>=1.3.4; extra == "security"->requests[security]==2.12.4->-r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 4))
  Downloading cffi-1.9.1-cp27-cp27m-macosx_10_10_intel.whl (214kB)
    100% |████████████████████████████████| 215kB 1.2MB/s 
Collecting setuptools>=11.3 (from cryptography>=1.3.4; extra == "security"->requests[security]==2.12.4->-r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 4))
  Downloading setuptools-34.3.0-py2.py3-none-any.whl (389kB)
    100% |████████████████████████████████| 399kB 1.0MB/s 
Collecting ipaddress (from cryptography>=1.3.4; extra == "security"->requests[security]==2.12.4->-r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 4))
  Downloading ipaddress-1.0.18-py2-none-any.whl
Collecting enum34 (from cryptography>=1.3.4; extra == "security"->requests[security]==2.12.4->-r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 4))
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting pyasn1>=0.1.8 (from cryptography>=1.3.4; extra == "security"->requests[security]==2.12.4->-r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 4))
  Downloading pyasn1-0.2.3-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 2.8MB/s 
Collecting pycparser (from cffi>=1.4.1->cryptography>=1.3.4; extra == "security"->requests[security]==2.12.4->-r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 4))
  Downloading pycparser-2.17.tar.gz (231kB)
    100% |████████████████████████████████| 235kB 1.0MB/s 
Collecting appdirs>=1.4.0 (from setuptools>=11.3->cryptography>=1.3.4; extra == "security"->requests[security]==2.12.4->-r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 4))
  Downloading appdirs-1.4.2-py2.py3-none-any.whl
Collecting packaging>=16.8 (from setuptools>=11.3->cryptography>=1.3.4; extra == "security"->requests[security]==2.12.4->-r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 4))
  Downloading packaging-16.8-py2.py3-none-any.whl
Collecting pyparsing (from packaging>=16.8->setuptools>=11.3->cryptography>=1.3.4; extra == "security"->requests[security]==2.12.4->-r /Users/julien/temp/sct/install/requirements/requirementsPip.txt (line 4))
  Downloading pyparsing-2.1.10-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 3.2MB/s 
Building wheels for collected packages: pycparser
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /Users/julien/Library/Caches/pip/wheels/a8/0b/41/dc95621f9d3a0da7bc191b8a71f0e8182ffd3cc5f33ac55005
Successfully built pycparser
Installing collected packages: mpmath, sympy, nibabel, nipy, numpy, scipy, dipy, idna, six, pycparser, cffi, appdirs, pyparsing, packaging, setuptools, ipaddress, enum34, pyasn1, cryptography, pyOpenSSL, requests
Successfully installed appdirs-1.4.2 cffi-1.9.1 cryptography-1.7.1 dipy-0.11.0 enum34-1.1.6 idna-2.2 ipaddress-1.0.18 mpmath-0.19 nibabel-2.1.0 nipy-0.4.0 numpy-1.11.2 packaging-16.8 pyOpenSSL-16.2.0 pyasn1-0.1.9 pycparser-2.17 pyparsing-2.1.10 requests-2.12.4 scipy-0.18.1 setuptools-23.0.0 six-1.10.0 sympy-1.0
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Installing binaries...
>> . /Users/julien/temp/sct/python/bin/activate /Users/julien/temp/sct/python
>> python ../scripts/sct_download_data.py -d binaries_osx -o /Users/julien/temp/sct/bin
Check folder existence...
Downloading 20161123_sct_binaries_osx.tar.gz


Download complete 20161123_sct_binaries_osx.tar.gz
Copy binaries to /Users/julien/temp/sct/bin/

Unzip dataset...

Remove temporary file...

Done! Folder created: /Users/julien/temp/sct/bin/

All requirements installed!
>> . /Users/julien/temp/sct/python/bin/activate /Users/julien/temp/sct/python

Installing data...
>> rm -rf /Users/julien/temp/sct/data
>> mkdir -p /Users/julien/temp/sct/data
>> cd /Users/julien/temp/sct/data
>> python ../scripts/sct_download_data.py -d PAM50
Downloading 20170101_PAM50.zip


Download complete 20170101_PAM50.zip
Copy binaries to /Users/julien/temp/sct/data

Unzip dataset...

Remove temporary file...

Done! Folder created: /Users/julien/temp/sct/data

>> python ../scripts/sct_download_data.py -d gm_model
Downloading 20160922_gm_model.zip


Download complete 20160922_gm_model.zip
Copy binaries to /Users/julien/temp/sct/data

Unzip dataset...

Remove temporary file...

Done! Folder created: /Users/julien/temp/sct/data


Do you want to add the sct_* scripts to your PATH environment? yes/no: y



Run sct_check_dependencies...

--
Spinal Cord Toolbox (master/56d03f1d4e164f0398a52e54b5da4a2265a4abf3)
Running /Users/julien/temp/sct/scripts/sct_check_dependencies.py

OS: osx (Darwin-14.5.0-x86_64-i386-64bit)
CPU cores: Available: 8, Used by SCT: 8
RAM: Primary memory available: 16.00 gigabytes
SCT path: /Users/julien/temp/sct
Installation type: git
  commit: 56d03f1d4e164f0398a52e54b5da4a2265a4abf3
  branch: master
Check Python path...................................[OK]
Check if data are installed.........................[OK]
Check if xlwt (1.0.0) is installed..................[OK]
Check if xlutils (1.7.1) is installed...............[OK]
Check if scikit-learn (0.17.1) is installed.........[OK]
Check if scikit-image (0.12.3) is installed.........[OK]
Check if pyqt (4.11.4) is installed.................[OK]
Check if matplotlib (1.5.1) is installed............[OK]
Check if pip (8.1.2) is installed...................[OK]
Check if xlrd (0.9.4) is installed..................[OK]
Check if pandas (0.18.1) is installed...............[OK]
Check if dipy (0.11.0) is installed.................[OK]
Check if nibabel (2.1.0) is installed...............[OK]
Check if requests (2.12.4) is installed.............[OK]
Check if nipy (0.4.0) is installed..................[OK]
Check if numpy is installed.........................[OK]
Check if scipy is installed.........................[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if figure can be opened.......................[OK]

INSTALLATION DONE!

Open a new Terminal window to load environment variables, or run:
 source /Users/julien/.bashrc
~~~

**Comment by jcohenadad** [comment]
apart from that, the batch_processing fails (first error is):
~~~
ERROR: The file warp_template2mt1_gmseg.nii.gz does not exist. Exit program.
~~~
this is caused by recent modifications on `sct_register_graymatter`, but the branch `jca_newExampleData` will solve this.

**Pull request closed without merging**
