### PR TITLE
Fix Timer with progress 

### LINKED ISSUE #1507: deal with carriage return with new logger
with previous behaviour, some of the message was put on the same line. Now, it creates a new line, yielding this behaviour:
~~~
Split destination volume...
0/128..
1/128..
2/128..
3/128..
4/128..
5/128..
6/128..
7/128..
8/128..
9/128..
10/128..
11/128..
12/128..
13/128..
14/128..
15/128..
16/128..
17/128..
18/128..
19/128..
20/128..
21/128..
22/128..
23/128..
24/128..
25/128..
26/128..
27/128..
28/128..
29/128..
30/128..
31/128..
32/128..
33/128..
34/128..
35/128..
36/128..
~~~

or this:
~~~
Remaining time: 00:00:21.07 (1265/1600)                      
Remaining time: 00:00:21.01 (1266/1600)                      
Remaining time: 00:00:20.95 (1267/1600)                      
Remaining time: 00:00:20.88 (1268/1600)                      
Remaining time: 00:00:20.82 (1269/1600)                      
Remaining time: 00:00:20.75 (1270/1600)                      
Remaining time: 00:00:20.69 (1271/1600)                      
Remaining time: 00:00:20.63 (1272/1600)                      
Remaining time: 00:00:20.57 (1273/1600)                      
Remaining time: 00:00:20.51 (1274/1600)                      
Remaining time: 00:00:20.44 (1275/1600)                      
Remaining time: 00:00:20.38 (1276/1600)                      
Remaining time: 00:00:20.31 (1277/1600)                      
Remaining time: 00:00:20.25 (1278/1600)                      
Remaining time: 00:00:20.19 (1279/1600)                      
Remaining time: 00:00:20.13 (1280/1600)                      
Remaining time: 00:00:20.06 (1281/1600)                      
Remaining time: 00:00:20.00 (1282/1600)                      
Remaining time: 00:00:19.94 (1283/1600)                      
Remaining time: 00:00:19.87 (1284/1600)                      
Remaining time: 00:00:19.81 (1285/1600)                      
Remaining time: 00:00:19.75 (1286/1600)                      
Remaining time: 00:00:19.68 (1287/1600)
...
~~~

### PR DESCRIPTION
**Pull request by poquirion**
Fix #1507

### CODE REVIEW

**Comment by jcohenadad** [comment]
I tested `poq_issue_1507_progress/32a1bf244dc13569d53ae9ec6550ebd2392151c3`

The issue with the timer is fixed. Tested with:
~~~
sct_process_segmentation -i t2_seg.nii.gz -p shape
~~~
However, this issue remain:
https://github.com/neuropoly/spinalcordtoolbox/issues/1507#issuecomment-350116091

**Comment by poquirion** [comment]
Should be good to go now

**Comment by perone** [comment]
I added [tqdm](https://github.com/tqdm/tqdm) on SCT in the past for some progress bars, estimated time left, etc. I think that it can be easier to use instead of doing this manually.

**Comment by poquirion** [comment]
We can use tqdm, but we still need to add a wrapper for the logger...
https://github.com/tqdm/tqdm/issues/313

I'll see how to do that best.

**Pull request merged**
