### PR TITLE
Enhancement on sct_extract_metric + fix for sct_process_segmentation

### PR DESCRIPTION
**Pull request by slevyrosetti**
Adresses issues:

- 1017 (MAP a priori clusters defined in info_label.txt) --> `sct_extract_metric`, `sct_warp_template`
- 1018 (flag -mask-weighted)--> `sct_extract_metric`
- 958 (fix a label to a specific value + output metric map estimation)--> `sct_extract_metric`
- 1037 (CSA computation) --> `sct_process_segmentation`

### CODE REVIEW

**Comment by jcohenadad** [comment]
WARNING: This merge requires reinstallation of SCT (PAM50 has been updated)

**Comment by jcohenadad** [comment]
Spinal Cord Toolbox (master/fa7698aacd0c799e350ab926fed1bc5fec6d204f)
~~~
t2/CSA:   /Users/julien/sct_example_data/t2/t2_seg.nii.gz, 76.753884, 2.049822
mt/MTR:   51, white matter, 387.801068, 33.744919, 0.000000
mt/CSA:   /Users/julien/sct_example_data/mt/dorsal_column.nii.gz, nan, nan
dmri/FA:  4, WM left lateral corticospinal tract, 22.799808, 0.734177, 0.000000
dmri/FA:  5, WM right lateral corticospinal tract, 20.828494, 0.790546, 0.000000
~~~

**Comment by jcohenadad** [comment]
Spinal Cord Toolbox (master/73e29b174eb1ced5f3fd69ff34bcd5ea96675091) (OLD VERSION)
~~~
grep: t2/csa_mean.txt: No such file or directory
t2/CSA:  
mt/MTR:   51, white matter, 381.213413, 33.917972, 0.000000
mt/CSA:   /Users/jcohen/sct_example_data/mt/dorsal_column.nii.gz, nan, nan
dmri/FA:  4, WM left lateral corticospinal tract, 21.756573, 0.740961, 0.000000
dmri/FA:  5, WM right lateral corticospinal tract, 18.279087, 0.768280, 0.000000
~~~

**Comment by slevyrosetti** [comment]
Spinal Cord Toolbox (master/fa7698aacd0c799e350ab926fed1bc5fec6d204f) with fix
~~~
t2/CSA:   /Users/slevy_local/test_batch_processing/sct_example_data/t2/t2_seg.nii.gz, 76.753884, 2.049822
mt/MTR:   51, white matter, 387.801068, 33.744919, 0.000000
mt/CSA:   /Users/slevy_local/test_batch_processing/sct_example_data/mt/dorsal_column.nii.gz, 20.052757, 1.286250
dmri/FA:  4, WM left lateral corticospinal tract, 22.799808, 0.734177, 0.000000
dmri/FA:  5, WM right lateral corticospinal tract, 20.828494, 0.790546, 0.000000
~~~

**Pull request merged**
